### PR TITLE
Refactor LoadInView to functional component with hooks

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
**What kind of change does this PR introduce?**
Update LoadInView to functional component with Hooks

**What is the current behavior?**
Class component

**What is the new behavior?**
Functional component with Hooks

**Checklist**:
- [ ] Documentation N/A
- [x] Tests
- [x] Ready to be merged 
- [ ] Added myself to contributors table  N/A

### CODE REVIEW

**Comment by SaraVieira** [comment]
Hey

Unfortunately, it's not quite working you can test this by starting the homepage with:

```
yarn start:home
```

If you scroll to the framework part you can see the iframe never loads
Screenshot 2019-05-22 at 11 31 35

**Comment by MichaelDeBoey** [comment]
Really stupid things 😓

Needed to access `elPos.current` instead of `elPos` since it's a `ref` and also forgot to need a `false` `show` before setting it to `true`😓

```diff
- if (show && elPos && getScrollPos().y + 600 > elPos) {
+ if (!show && elPos.current && getScrollPos().y + 600 > elPos.current) {
```

**Comment by SaraVieira** [comment]
Aweeeesome!

Thank yoU!

**Comment by MichaelDeBoey** [comment]
Thanks for merging this one so late in the evening @SaraVieira! 🙂

**Pull request merged**
