### PR TITLE
fix: add max 50 for number input in Patron Page

### PR DESCRIPTION
**Pull request by jyash97**
## What kind of change does this PR introduce?
Bug Fix

## What is the current behavior?
Currently when we press Arrow up price gets over 50 but range slider is limited to 50 only.

## What is the new behavior?
After setting `max={50}` it limits the input to 50 when increasing from Arrow up Key.

## What steps did you take to test this?
Tested it locally on `localhost:3000/patron`

## Checklist

- [ ] Documentation
- [x] Testing 
- [x] Ready to be merged 
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by CompuIves** [comment]
Thanks for the contribution! It's a good catch.

In our case this bug is actually a feature ™️! We have had one patron who wanted to donate more than 50$, so they were able to do this by using the arrow keys. If we would disable the arrow key functionality as well, we would disable paying more than 50$ month altogether. That's why I prefer to keep this the way it is.

**Comment by jyash97** [comment]
Right! This won't allow increasing more than 50$ using Arrow Up key but I think can be done by manually entering the amount. 

If this is the expected behavior we can close this PR. 
Thanks :)

**Comment by MichaelDeBoey** [comment]
I think the whole Patron section needs to be rethought eventually so people can pay whatever they want (even if they want to pay $100+/month) in an easy way.

**Comment by jyash97** [comment]
True, I think having a slider limited to $50 creates a confusion.

**Comment by christianalfoni** [comment]
Thanks for bringing this to our attention @jyash97! I have added this to our user experience improvement docs and will close the PR for now. Thanks again :)

**Pull request closed without merging**
