### PR TITLE
fix(Tooltip): fix overlapping and use tippy singletons where applicable

### PR DESCRIPTION
**Pull request by atomiks**
## What kind of change does this PR introduce?

Improves UX of tooltips and fixes overlapping issues. `updateDuration` (position update transition) can be changed to a more suitable value if need be

## What is the current behavior?

See #3059 

## What is the new behavior?

See #3059 

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

Unfortunately it seems like importing CSS files in `Tooltip/index.tsx` is breaking Jest. Any help on this? 

```bash
yarn test
yarn lint
```

## Checklist

- [ ] Documentation
- [ ] Testing 
- [ ] Ready to be merged
      
- [ ] Added myself to contributors table

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3065/commits/8031d3ed8a5f31412c2a6450521fd955a6ba207a is at https://pr3065.build.csb.dev/s/new.

**Comment by CompuIves** [comment]
Nice!! Thanks for this contribution, I really appreciate it, especially since you're the author of the library and helping us with this. 

I pushed a fix for the tests. Did you also test the behaviour by running locally? As soon as that's confirmed we can merge this!

**Comment by atomiks** [comment]
> Did you also test the behaviour by running locally? As soon as that's confirmed we can merge this!

I'm not sure what you mean here. I developed it locally but couldn't run the Jest tests as I mentioned :-(. You can manually test it in the deployed preview to see the behavior.

Also something to note: there is an accessibility problem. We added `tabindex="0"` to the wrapping `<span>` in the prev major, but now that doesn't get added anymore. It should be added back, or preferrably the wrapper `<span>` is removed so that `<Tippy />` uses the native element which is much better for the screen readers and keyboard nav

**Comment by arthurdenner** [comment]
@atomiks, could you solve the conflicts here to see if we can get it merged, please?

**Comment by SaraVieira** [comment]
All seems to work great and I fixed the conflicts 🗡 


Thank you so much!

**Pull request merged**
