### PR TITLE
Add james to team page

### PR DESCRIPTION
**Pull request by JamesACS**
## What kind of change does this PR introduce?

Adds James to team page

## What is the current behavior?

James isn't on team page

## What is the new behavior?

James is on team page

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

N/A

## Checklist

- [X] Documentation
- [N/A] Testing
- [X] Ready to be merged
      
- [ ] Added myself to contributors table

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/6152/commits/9f863175c90a6d0c5586be93ddcd532c45500278 failed.

**Review by JamesACS — COMMENTED** [review]
Missing comma - fixed

**Review by JamesACS — COMMENTED** [review]
Missed another comma!

**Review by JamesACS — COMMENTED** [review]
Compressed image

**Review by JamesACS — COMMENTED** [review]
Fixed resolution of image

**Pull request merged**
