### PR TITLE
🔨 Switch CollectionInfo to use useOvermind

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Follow-up of #2639

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/2858/commits/47e3e244412566e1e7c0821615c0594befd3d109 is at https://pr2858.build.csb.dev/s/new.

**Comment by MichaelDeBoey** [comment]
I think this one can be deleted after 167365c1, no? 🤔

**Comment by MichaelDeBoey** [comment]
I think this component can be deleted after @CompuIves' 167365c1 (since it's not used anymore), no? 🤔

**Comment by MichaelDeBoey** [comment]
Ping @CompuIves @SaraVieira @christianalfoni

**Comment by christianalfoni** [comment]
Yeah, I can not find any usage of this component. Closing it. Sorry and please reopen if I did anything wrong here 😄

**Pull request closed without merging**
