### PR TITLE
style(new-design): Remove Projects Banner

### PR DESCRIPTION
**Pull request by marcovincit**

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/6900/commits/ca4ebd56f3a5a7ed7c47850b96ca9ac6ee8d85aa is at https://pr6900.build.csb.dev/s/new.

**Review by tristandubbeld — APPROVED** [review]
Looks like we're having issues with diffs showing previous changes that have already been merged into `dashboard/improvements`. @zehfernandes was also talking about this.

I checked the files changed by you and we're good to go :)

**Review by olarclara — APPROVED** [review]
Looks good to me. Probably should rebase before merging.

**Comment by alexnm** [comment]
@marcovincit I just worked on a PR with renaming the home page to recent. Mind if I apply the changes in your commit here to that branch so we close this and avoid the hustle of rebasing?

**Comment by marcovincit** [comment]
> @marcovincit I just worked on a PR with [renaming the home page to recent](https://github.com/codesandbox/codesandbox-client/pull/6905). Mind if I apply the changes in your commit here to that branch so we close this and avoid the hustle of rebasing?

yeah definitely! just do it @alexnm 🙌🙌🙌🖤

**Comment by alexnm** [comment]
banner removed here: https://github.com/codesandbox/codesandbox-client/pull/6905/commits/f2c57921479bd53d5a5a495b7a36aa16102372fd

**Pull request closed without merging**
