### PR TITLE
Feat/astro syntax highlight

### PR DESCRIPTION
**Pull request by danilowoz**
Related to https://github.com/codesandbox/codesandbox-client/issues/5958

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/6001/commits/88edbe160c76850d6fb5d17c7d68c876db35f5ec is at https://pr6001.build.csb.dev/s/new.

**Review by CompuIves — APPROVED** [review]
Yep, this looks good! Nice that you also updated `main.min.json`!

**Comment by FredKSchott** [comment]
Thanks yall for merging! Our community is loving this integration so far.

FYI we had a request to make sure that imported Astro repos start with the "node" template. cross-posting here in case that repo doesn't get as many eyes.  https://github.com/codesandbox/codesandbox-importers/pull/138

**Comment by sannek** [comment]
> Thanks yall for merging! Our community is loving this integration so far.
> 
> FYI we had a request to make sure that imported Astro repos start with the "node" template. cross-posting here in case that repo doesn't get as many eyes. [codesandbox/codesandbox-importers#138](https://github.com/codesandbox/codesandbox-importers/pull/138)

This one's also merged and deployed just now 🚀

**Comment by FredKSchott** [comment]
Awesome, thank you so much!

**Pull request merged**
