### PR TITLE
Added @storybook/react dependency to common with basic story examples

### PR DESCRIPTION
**Pull request by shiftyp**
## What kind of change does this PR introduce?

Adds a [React Storybook](https://storybook.js.org/) application to the @codesandbox/common package. This fills a need for documentation / testing I experienced in trying to create a contribution to the react component side of the app.

The goal of this change is to improve the ability of developers to learn and test components by using Storybook to provide a set of renderings from known props (stories) that can be easily reviewed as a form of documentation and used as a workbench during development.

## What is the current behavior?

This is a new feature, and doesn't modify existing behavior.

## What is the new behavior?

This change adds npm scripts as well as dependencies to the project to create a storybook application within the common package. It can be run against this PR with `yarn install && yarn start:storybook:common` from the project root. It also adds two stories within the storybook.

## What steps did you take to test this?

Current testing was simply to create a set of basic stories for the `Button` and `SandboxCard` components. These work as expected:

### Button
Screen Shot 2019-07-27 at 2 22 07 PM

### SandboxCard
Screen Shot 2019-07-27 at 2 05 58 PM

## Checklist

- [ ] Documentation
- [ ] Testing 
- [ ] Ready to be merged 
- [ ] Added myself to contributors table

### CODE REVIEW

**Comment by shiftyp** [comment]
I've added some additional stories [here](https://github.com/shiftyp/codesandbox-client/pull/1)

**Comment by shiftyp** [comment]
And added cypress for e2e testing stories [here](https://github.com/shiftyp/codesandbox-client/pull/2)

**Comment by SaraVieira** [comment]
Hey!

This is amazing @shiftyp 

Can I merge the pr's to this branch to then get this merged? ❤️

**Comment by SaraVieira** [comment]
Seems you have to merge them. They book look awesome! As soon as that is merged I think we can merge this 🎉

**Comment by shiftyp** [comment]
Hi @SaraVieira! I'm glad Storybook is a good addition. I've merged the additional stories into this PR, but I'm unsure about the addition of Cypress and would like your thoughts. Compare the [cypress PR](https://github.com/shiftyp/codesandbox-client/pull/2) with [this PR](https://github.com/shiftyp/codesandbox-client/pull/3/files) that achieves a similar testing result only with Jest. It doesn't run yet for me (perhaps you can test) but the code looks much nicer I think for what it does.

**Comment by shiftyp** [comment]
Also, I'm a little unsure how these changes caused the current test failures on CI, so any help there would be appreciated.

**Comment by SaraVieira** [comment]
I think the failures are a problem with master and yarn lock files that needs to be generated again :(

No worries about that

About the question yeah I would go with jest but the question would be why not add the plugin that automatically creates these things

https://github.com/storybookjs/storybook/tree/master/addons/storyshots

Does that make sense?

**Comment by SaraVieira** [comment]
I merged it but we can keep talking and again thank you so much!

**Pull request merged**
