### PR TITLE
replace reakit menu with design system component

### PR DESCRIPTION
**Pull request by alexnm**
The top-right corner menu was using the reakit Menu component and had some issues on the first render. It was replaced with the design system component and the UI is now closer to the rest of the application (spacing, colors, hover, etc.)

Follow-up:
- icons in the menu were not added in the design system yet, as they have a different viewBox and might be better to be rexported from figma
- MenuLink could be extracted into a separate file if it gets more complex
- Didn't have a different subscription user to test all the cases

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/5214/commits/f6a2c90eba2977b78db780337d7a1f1ea0f366ce is at https://pr5214.build.csb.dev/s/new.

**Comment by siddharthkp** [comment]
Love the hover effect on icons. Some of the default states seem inconsistent though

Tagging @DannyRuchtie for his eye 😋 

image

**Comment by alexnm** [comment]
I didn't change the icons themselves, we should talk about exporting all the missing svgs from figma

**Comment by DannyRuchtie** [comment]
Hi, Alex great work. Big improvement!
A couple of small things I would like to discuss with you and sid.

[ ] Default font-weight for menu
[ ]  Patrion icons default style 
[ ] Hover color of icons should be white
[ ] Explore animation options

**Review by DannyRuchtie — APPROVED** [review]
All looks good. 

- ~~Font weight~~
- ~~hover color~~
- ~~Icos~~

**Review by siddharthkp — APPROVED** [review]
LGTM, ship it!

**Pull request merged**
