### PR TITLE
Send env vars to vercel as secrets

### PR DESCRIPTION
**Pull request by SaraVieira**
**Problem**: 
When you tried to deploy a project to vercel, if you had env variables these were never actually sent to vercel so everything failed

**Now**:
If you have env vars in your now.json file and have the same in environment variables these will be sent to vercel so you can deploy and these secrets will be added to your account

Example sandbox id: https://pr4169.build.csb.dev/s/cool-northcutt-ud4wr

Add an env variable called: NEXT_HELLO_CSB with any value and then go to the deployed site at `api/people/test` and magic!

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/4169/commits/2ad77c2ed4ff47a8be8c7c081f5c909205e51d68 is at https://pr4169.build.csb.dev/s/new.

**Comment by SaraVieira** [comment]
My thinking was, this happens behind the scenes, should we really show an error?

Also because zeit shows one if the secret doesn't exist

**Comment by CompuIves** [comment]
Ohh, that makes sense! Good thinking. Could you add a comment to the code there to explain that? Then it's ready to go!

**Comment by SaraVieira** [comment]
Sure! Done :)

[https://github.com/codesandbox/codesandbox-client/pull/4169/commits/a01847eb96743cc7864f6f2dd368420eff7aaf8a ](https://github.com/codesandbox/codesandbox-client/pull/4169/commits/a01847eb96743cc7864f6f2dd368420eff7aaf8a)

**Pull request merged**
