### PR TITLE
Show error when rename a file with invalid name

### PR DESCRIPTION
**Pull request by yeion7**
## What kind of change does this PR introduce?

feature

## What is the current behavior?

When you rename a file, you can't see which is the error

## What is the new behavior?

You can see the error (also works with screen readers)

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

1. Rename a file
2. Input a not valid name
3. Show error

## Checklist

- [ ] Documentation
- [ ] Testing 
- [x] Ready to be merged
      
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/2908/commits/48485a8c0408a63562b346e2b60ebe72ecede2bd is at https://pr2908.build.csb.dev/s/new.

**Comment by SaraVieira** [comment]
Hey!

This is an amazing idea. Unfortunately, I do see some css issues. In this case, it gets cut :/

Screenshot 2019-10-22 at 14 58 06


Also when its the same name there is no bottom padding :(

**Comment by yeion7** [comment]
Nice catch @SaraVieira, could you confirm if it still happens?

I tested with 

Chrome 78.0.3904.70 (Official Build) (64-bit)
Safari 13.0.2 (15608.2.30.1.1)
Firefox 70.0 (64-bit)

**Comment by SaraVieira** [comment]
This is dope! Thank you so much for taking the time!!

**Pull request merged**
