### PR TITLE
Fix extra elements crash

### LINKED ISSUE #3928: crash on trying to access dashboard
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | safari | 13.1.0 | OS X 10.15.5           | d0620baaf          |

  **Route:**
  https://codesandbox.io/dashboard/recent

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: undefined is not an object (evaluating 't.props.ExtraElement')
  https://codesandbox.io/static/js/app.d9e3ef462.js:602:796745
https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2341152
value@https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2330290
value@https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2327548
Ya@https://codesandbox.io/static/js/common.09c57e702.chunk.js:1:1728725
ml@https://codesandbox.io/static/js/common.09c57e702.chunk.js:1:1748119
pl@https://codesandbox.io/static/js/common.09c57e702.chunk.js:1:1748044
il@https://codesandbox.io/static/js/common.09c57e702.chunk.js:1:1745372
il@[native code]
https://codesandbox.io/static/js/common.09c57e702.chunk.js:1:1703554
https://codesandbox.io/static/js/common.09c57e702.chunk.js:1:1778890
Yo@https://codesandbox.io/static/js/common.09c57e702.chunk.js:1:1703500
Jo@https://codesandbox.io/static/js/common.09c57e702.chunk.js:1:1703435
el@https://codesandbox.io/static/js/common.09c57e702.chunk.js:1:1742158
Sa@https://codesandbox.io/static/js/common.09c57e702.chunk.js:1:1720953
Sa@[native code]
next@https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:38785
y@https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2537102
g@https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2537605
value@https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2538158
forEach@[native code]
g@https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:900193
next@https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:899748
o@https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:913269
https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:914432
https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:919836
forEach@[native code]
https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:919818
forEach@[native code]
https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:919768
https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:921696
next@https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2539292
y@https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2537102
g@https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2537605
value@https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2538158
forEach@[native code]
next@https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:907493
y@https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2537102
g@https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2537605
value@https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2538158
value@[native code]
y@https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2537102
g@https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2537605
value@https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2538158
next@https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:937447
y@https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2537102
g@https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2537605
value@https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2538158
next@https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2539329
y@https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2537102
  
    in t
    in div
    in t
    in div
    in t
    in elements__Content
    in r
    in div
    in t
    in elements__Container
    in cm
    in dm
    in t
    in t
    in Unknown
    in withRouter()
    in div
    in t
    in elements__ContentContainer
    in div
    in div
    in t
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in t
    in div
    in t
    in elements__Content
    in r
    in withRouter(r)
    in div
    in t
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in t
    in l
    in t
  ```

  </details>

### LINKED ISSUE #3929: 💥 Crash Report
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > I just open codesandbox.io/dashboard/recent

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 81.0.4044 | Linux x86_64           | d0620baaf          |

  **Route:**
  https://codesandbox.io/dashboard/recent

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'ExtraElement' of undefined
  TypeError: Cannot read property 'ExtraElement' of undefined
    at https://codesandbox.io/static/js/app.d9e3ef462.js:602:602327
    at t.default (https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2341151)
    at t.value (https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2330289)
    at t.value (https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2327522)
    at Ya (https://codesandbox.io/static/js/common.09c57e702.chunk.js:1:1728719)
    at Ja (https://codesandbox.io/static/js/common.09c57e702.chunk.js:1:1728512)
    at xs (https://codesandbox.io/static/js/common.09c57e702.chunk.js:1:1763813)
    at ml (https://codesandbox.io/static/js/common.09c57e702.chunk.js:1:1748117)
    at pl (https://codesandbox.io/static/js/common.09c57e702.chunk.js:1:1748042)
    at il (https://codesandbox.io/static/js/common.09c57e702.chunk.js:1:1745370)
    at https://codesandbox.io/static/js/common.09c57e702.chunk.js:1:1703553
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.09c57e702.chunk.js:1:1778889)
    at qo (https://codesandbox.io/static/js/common.09c57e702.chunk.js:1:1703262)
    at Yo (https://codesandbox.io/static/js/common.09c57e702.chunk.js:1:1703498)
    at Jo (https://codesandbox.io/static/js/common.09c57e702.chunk.js:1:1703433)
    at el (https://codesandbox.io/static/js/common.09c57e702.chunk.js:1:1742156)
    at Sa (https://codesandbox.io/static/js/common.09c57e702.chunk.js:1:1720951)
    at Object.next (https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:38774)
    at y (https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2537098)
    at g (https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2537604)
    at e.value (https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2538157)
    at https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:900218
    at Array.forEach (<anonymous>)
    at g (https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:900186)
    at Object.next (https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:899747)
    at o (https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:913269)
    at https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:914431
    at https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:919835
    at Set.forEach (<anonymous>)
    at https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:919811
    at Map.forEach (<anonymous>)
    at e.broadcastQueries (https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:919761)
    at https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:921680
    at Object.next (https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2539291)
    at y (https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2537098)
    at g (https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2537604)
    at e.value (https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2538157)
    at https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:907524
    at Set.forEach (<anonymous>)
    at Object.next (https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:907486)
    at y (https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2537098)
    at g (https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2537604)
    at e.value (https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2538157)
    at y (https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2537098)
    at g (https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2537604)
    at e.value (https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2538157)
    at Object.next (https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:937443)
    at y (https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2537098)
    at g (https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2537604)
    at e.value (https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2538157)
  
    in t
    in div
    in t
    in div
    in t
    in elements__Content
    in r
    in div
    in t
    in elements__Container
    in cm
    in dm
    in t
    in t
    in Unknown
    in withRouter()
    in div
    in t
    in elements__ContentContainer
    in div
    in div
    in t
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in t
    in div
    in t
    in elements__Content
    in r
    in withRouter(r)
    in div
    in t
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in t
    in l
    in t
  ```

  </details>

### LINKED ISSUE #3930: Crash while logging out.
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 81.0.4044 | OS X 10.12.6           | d0620baaf          |

  **Route:**
  https://codesandbox.io/dashboard/recent

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'ExtraElement' of undefined
  TypeError: Cannot read property 'ExtraElement' of undefined
    at https://codesandbox.io/static/js/app.d9e3ef462.js:602:602327
    at t.default (https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2341151)
    at t.value (https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2330289)
    at t.value (https://codesandbox.io/static/js/vendors~app.93ba44dd1.chunk.js:1:2327522)
    at Ya (https://codesandbox.io/static/js/common.09c57e702.chunk.js:1:1728719)
    at Ja (https://codesandbox.io/static/js/common.09c57e702.chunk.js:1:1728512)
    at xs (https://codesandbox.io/static/js/common.09c57e702.chunk.js:1:1763813)
    at ml (https://codesandbox.io/static/js/common.09c57e702.chunk.js:1:1748117)
    at pl (https://codesandbox.io/static/js/common.09c57e702.chunk.js:1:1748042)
    at il (https://codesandbox.io/static/js/common.09c57e702.chunk.js:1:1745370)
  
    in t
    in div
    in t
    in div
    in t
    in elements__Content
    in r
    in div
    in t
    in elements__Container
    in cm
    in dm
    in t
    in t
    in Unknown
    in withRouter()
    in div
    in t
    in elements__ContentContainer
    in div
    in div
    in t
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in t
    in div
    in t
    in elements__Content
    in r
    in withRouter(r)
    in div
    in t
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in t
    in l
    in t
  ```

  </details>

### PR DESCRIPTION
**Pull request by CompuIves**
Might fix #3928
Might fix #3929
Might fix #3930

### CODE REVIEW

**Comment by jyash97** [comment]
Is this fix live? @CompuIves 

I can confirm that dashboard is working now. Also, I was trying to fix this but not happening on local.

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3931/commits/6bc6ff778063a04c09d5d1dcd56ec4583c127735 is at https://pr3931.build.csb.dev/s/new.

**Comment by CompuIves** [comment]
Yeah, it doesn't seem to happen on local for some reason. We rolled back, so this might be the fix, but am unsure. We will know once this has been deployed to staging 😄

**Comment by CompuIves** [comment]
Oh, speaking of the devil!

**Comment by CompuIves** [comment]
Dashboard seems to work on my side now, that's weird...

**Comment by jyash97** [comment]
I can give you some pointer here. This PR seems to break the dashboard: https://github.com/codesandbox/codesandbox-client/pull/3927

Try running `yarn` and test the app. Maybe it may break on local. My system is still starting the app 😕

**Comment by CompuIves** [comment]
Yeah, I wasn't able to repro it in dev at the time. I think maybe some babel dependencies changed in that PR that caused this issue 🤔

**Comment by CompuIves** [comment]
Okay, here we gooooo

**Comment by jyash97** [comment]
Curious to know what was the reason behind the issue. :)

**Pull request merged**
