### PR TITLE
fix(profile):prevent redirection on clicking close icon for upgrade banner

### PR DESCRIPTION
**Pull request by jyash97**
Hey 👋 

## What kind of change does this PR introduce?
Bug Fix

## What is the current behavior?
When we close the `Upgrade to Pro` message on the Profile page it takes us to the `pro` pricing page. I am not sure if this is the intended behavior. Screen rec for the issue: 

https://www.loom.com/share/b23fe204f9c64455adea2859ff417196

## What is the new behavior?
To not redirect to the pricing page on clicking the close button.

https://www.loom.com/share/86d2f04677e543ac968cec403afb5939

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

1. Checked redirection with close button
2. Confirmed that clicking on banner still takes to the Pricing page

## Checklist

- [x] Testing 
- [x] Ready to be merged

### CODE REVIEW

**Review by SaraVieira — APPROVED** [review]
Hero!

Thank you so much!

Definitely not supposed to happen

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/5392/commits/7c3967baa121c28d77f32493b653021512ddfca0 is at https://pr5392.build.csb.dev/s/new.

**Comment by SaraVieira** [comment]
I have no idea why the tests are not running :(

**Comment by jyash97** [comment]
Hey 👋 

Sorry for the late reply. Tests are working now. What was the issue ?

**Comment by SaraVieira** [comment]
I have no idea, seemed like just a hug from circle ci.

I made a fake commit with a space and it started working

**Comment by jyash97** [comment]
Okay thanks. I will push a empty commit for this PR as well: #5393

**Comment by SaraVieira** [comment]
Sounds good! Let me know if it doesn't work :/

**Pull request merged**
