### PR TITLE
fix(workspace): fix overflow on WorkspaceItem's children

### LINKED ISSUE #3100: Template Menu Collapse UI Glitch
# 🐛 bug report
Screen Shot 2019-11-29 at 9 33 05 PM

## Description of the problem
While I was using the template feature, I pressed on the collapse icon which caused the delete button to move up and the text elements for template features were still visible. I tried refreshing the page and attempting it again, the same result occurred. 
## How has this issue affected you? What are you trying to accomplish?
I was trying to collapse the template features section. The UI broke when attempting to do it, but it did not stop me from reopening the template section and the features were still usable. 
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1574702177-7e1e9d0d1 
| Browser          | Chrome/ Version 78.0.3904.108
| Operating System | Catalina 10.15.1/macOS

### PR DESCRIPTION
**Pull request by arthurdenner**
## What kind of change does this PR introduce?
Bug fix. Closes #3100.

## What is the current behavior?
Children element overlaps container sometimes. See linked issue.

## What is the new behavior?
Children element doesn't overlap.

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

1. Open [this sandbox](https://codesandbox.io/s/funny-mendeleev-j5in0);
2. Toggle the `Template` workspace item;
3. Verify that it doesn't overlaps.

## Notes

- I tested the other use cases of `WorkspaceItem` and they seem to keep the current behavior with the change of `overflow`;
- Also, I deleted some dead code that I found.

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3148/commits/4bbb779c841e4b90f57c4369320b626271f13549 is at https://pr3148.build.csb.dev/s/new.

**Comment by arthurdenner** [comment]
> If in template you try to open the color modal or the icon one they get cut :(

Nice, I'm glad you caught that - it wouldn't be so easy, right?

I'll try to find a proper fix.

**Comment by SaraVieira** [comment]
Yeah, no worries I am on it with portals. I did it the same way for the google fonts

Hacky but works

Mind if I close this one? :/

**Comment by arthurdenner** [comment]
> Mind if I close this one? :/

I managed to fix it by applying `overflow: initial` only when it's open. Can you test it?

I've checked the other scenarios and they seem to work good as well.

**Comment by SaraVieira** [comment]
Holy shit that does fix it!

Thank you so much, so much cleaner then mine!

THANK YOU 😭

**Comment by arthurdenner** [comment]
Thank you too, @SaraVieira <3

**Pull request merged**
