### PR TITLE
fix(embed): likes counter on dislike shows inconsistent value

### PR DESCRIPTION
**Pull request by jyash97**
## What kind of change does this PR introduce?
Bug Fix

## What is the current behavior?
When in `Embed` you dislike ( removing the current like ) the like counter does `-2` i.e if number of likes were `1` it goes to `-1`.

Reason: 

For instant feedback, the like is updated when we click heart button and on receiving the response we do `-1` which causes inconsistency. I have used the response from Backend to reflect on state.

## What is the new behavior?
Consistent behavior

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

1. Tested Locally by replicating the bug

## Checklist

- [ ] Documentation - N/A
- [x] Testing 
- [x] Ready to be merged
      
- [x] Added myself to contributors table
      

 Great work guys on the new embed design. Looks really awesome!!! 🔥 💯

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/2957/commits/e1b53c566d519361c69f86981f82daaded44a18c is at https://pr2957.build.csb.dev/s/new.

**Comment by siddharthkp** [comment]
@jyash97 Thanks for fixing this! I'll test this on top of my in-progress branch and merge this 👍

**Comment by jyash97** [comment]
Hey @siddharthkp  I think this can be tested from the deploy PR link as well. This may save you time as well.

**Comment by siddharthkp** [comment]
Yep, confirmed it works, but I have no idea how 😄 

Using this as a chance to learn more about how likes work

**Comment by jyash97** [comment]
You can read this once and check the code. You will get the cause: 
> For instant feedback, the like state is updated when we click the heart button and on receiving the response we do -1 which causes inconsistency. I have used the response from Backend to reflect on the state.

**Comment by jyash97** [comment]
@siddharthkp  Just checking if there's any update over this PR 🤔

**Comment by siddharthkp** [comment]
not yet but soon

**Comment by siddharthkp** [comment]
Thank you for fixing the bug @jyash97!

**Comment by jyash97** [comment]
Glad that the PR helped :) Thanks for the review 💯 

Also on another note, I have a couple of feedback on Embed in Mobile. Would you like to take a look at them and see if it makes sense?

**Comment by siddharthkp** [comment]
Sure, where can I look at them? Are they in a github issue (best way to report and attach snapshots)

**Comment by jyash97** [comment]
I can create a Github issue with proper description and mention you. Will be doing in some time :)

**Comment by jyash97** [comment]
Hey @siddharthkp 
I have created the issue over here: #3045 
Do take a look when you get the time and let me know if I can help you in making the mobile experience better :)

**Pull request merged**
