### PR TITLE
Remove dependency on react-icons in @csb/components

### PR DESCRIPTION
**Pull request by CompuIves**
It was the only place where we use `react-icons` in `@codesandbox/components`, and it's not marked as a dependency. We'll have to check the test snapshot to see if it changes styling significantly.

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/5044/commits/9cf89bdaac26578788bff6fa21e254b09dae870f is at https://pr5044.build.csb.dev/s/new.

**Comment by siddharthkp** [comment]
wow this day has already arrived?!

**Review by siddharthkp — APPROVED** [review]

**Comment by CompuIves** [comment]
I did a local test, and the icon is a bit too large. I reduced the size to 8, it was `1em` before. It feels like `1em` is better but I'm not sure, what do you think?

**Comment by siddharthkp** [comment]
Yep 7 would be perfect. react-icons has a different box size than our icons (it's not edge to edge)

**Comment by CompuIves** [comment]
Good one, looks much better now!

**Pull request merged**
