### PR TITLE
codesandbox-deps: use rollup instead of parcel

### PR DESCRIPTION
**Pull request by lbogdan**

### CODE REVIEW

**Comment by probablyup** [comment]
I think this broke things. After the latest SW update I'm getting this error:

browserfs.rollup.js:3932 Uncaught Error: WARNING: File system has desynchronized. Received following error: Error: ENOTSUP: Operation is not supported.
$
    at n (browserfs.rollup.js:3932)
    at browserfs.rollup.js:6631

https://codesandbox.io/embed/thirsty-river-nlgn5

**Comment by lbogdan** [comment]
@probablyup This PR is supposed to be related to only the `tern` dep of CodeMirror, so I don't think it's related to your issue.

**Comment by lbogdan** [comment]
Can reproduce it on an older PR build as well: https://pr2071.build.csb.dev/s/nlgn5 .

**Comment by probablyup** [comment]
Hmm.. what do you suggest? I cleared all site data including the SW and it's still broken.

**Pull request merged**
