### PR TITLE
fix(dependencies): preserve selected version after new search

### PR DESCRIPTION
**Pull request by jyash97**
## What kind of change does this PR introduce?
Bug Fix

## What is the current behavior?
Dependency modal shows the wrong selected version, as we don't have the defaultValue set in.

https://www.loom.com/share/219635b740a8468f922cda956ffb580f

## What is the new behavior?
https://www.loom.com/share/0e4014ff3e2f448dba075b0bb329f522

## Checklist

- [x] Testing 
- [x] Ready to be merged

Great work guys on the new improved UI 💯

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/4928/commits/e4c4fb4d212ce60457b0432ee0b1ecdfe8322ab9 is at https://pr4928.build.csb.dev/s/new.

**Comment by SaraVieira** [comment]
Nice! Really good fix! Thank you so much!

I don't wanna diminish your contribution but please try to regrain from calling us guys since there are women on the team :/

**Comment by jyash97** [comment]
>  I don't wanna diminish your contribution but please try to regrain from calling us guys since there are women on the team :/

Hey really sorry it came out this way, I never wanted to hurt anyone. But these was not intentional. 

Love your work 😁 and thanks for inspiring to do Open source stuff 👏

**Comment by SaraVieira** [comment]
Oh I know, do not worry, I know you didn't mean anything bad and as someone who's English is also not the first language I always saw guys as a global term for man and woman and I have only been trying to remove that now and for the last year or something

It's hard man

Again, thank you so much for your help!

**Comment by jyash97** [comment]
> always saw guys as a global term for man and woman

Same 

But thanks for clarifying. I will also try to spread the same message :)

**Pull request merged**
