### PR TITLE
fix crash

### LINKED ISSUE #4840: crashed
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 85.0.4183 | Linux x86_64           | 8505f3a11          |

  **Route:**
  https://codesandbox.io/s/broken-dream-tcyt8

  **Error Code:**
2df0498d50b84ac7bb7f3c93807f3de8

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'users' of null
  TypeError: Cannot read property 'users' of null
    at Ln (https://codesandbox.io/static/js/app.5df31c2dc.js?_sw-precache=0cfce2d2b853c851f166d452d61cbabe:306:866873)
    at ua (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1772874)
    at Es (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1818137)
    at ml (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1803713)
    at hl (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1803638)
    at il (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1800966)
    at https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1759149
    at https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1834485
    at qo (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1758858)
    at $o (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1759094)
    at Yo (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1759029)
    at el (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1797752)
    at Sa (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1776547)
    at https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1050313
    at https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1050996
    at https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1172448
    at m.flush (https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1175277)
    at p.flush (https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1171502)
    at Object.cb (https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1060110)
    at e.emit (https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1053753)
    at server.onCodeSandboxAPIMessage (https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1062743)
    at https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1061785
    at Object.<anonymous> (https://codesandbox.io/static/js/app.5df31c2dc.js?_sw-precache=0cfce2d2b853c851f166d452d61cbabe:306:517245)
    at https://codesandbox.io/static/js/default~app~embed~sandbox.ffd192e3d.chunk.js?_sw-precache=0c40285afb88be9257eb279104b374c9:1:6561
    at Array.forEach (<anonymous>)
    at P (https://codesandbox.io/static/js/default~app~embed~sandbox.ffd192e3d.chunk.js?_sw-precache=0c40285afb88be9257eb279104b374c9:1:6524)
    at k (https://codesandbox.io/static/js/default~app~embed~sandbox.ffd192e3d.chunk.js?_sw-precache=0c40285afb88be9257eb279104b374c9:1:6652)
  
    in Ln
    in div
    in Actions___StyledStack
    in Er
    in header
    in Header___StyledStack
    in Ia
    in je
    in Unknown
    in div
    in elements__Container
    in je
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

### PR DESCRIPTION
**Pull request by SaraVieira**
closes #4840

### CODE REVIEW

**Review by CompuIves — APPROVED** [review]
Nice!! Is there a reason this is in a memo? I always thought that useMemo is used for expensive computation, but maybe it also has other benefits?

**Comment by SaraVieira** [comment]
This was actually VSCode telling me

The thing is apparently if you don't set it it could cause the other useMemo to go on an infinite loop

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/4841/commits/ea16c27396586518c3475da09483395f6347655d is at https://pr4841.build.csb.dev/s/new.

**Comment by MichaelDeBoey** [comment]
@SaraVieira @CompuIves Using `useMemo` is mostly a bad practice
https://kentcdodds.com/blog/usememo-and-usecallback

**Comment by CompuIves** [comment]
I agree, useMemo is probably overused, but I'm happy that it exists. It wouldn't call it a bad practice but rather a tool that you can use whenever you want to optimize render performance.

**Pull request merged**
