### PR TITLE
🔨 Switch Appearance to use useOvermind

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Follow-up of #2806

Things I did extra:
- Extract `EditorTheme` into its own component
- Put all styles into the `elements.ts` file
- Use `FunctionComponent` instead of `React.FC`, since [it's the same](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f13238a5d2086cd87f3209704f8897f7f701d957/types/react/index.d.ts#L513), but `FunctionComponent` is a bit clearer I think

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3074/commits/40288535ec9eb5011589ba4ca808287d223dbb6e is at https://pr3074.build.csb.dev/s/new.

**Comment by christianalfoni** [comment]
Hm, there seems to be some missing code and styling?

Screenshot 2019-11-28 at 09 41 43

Screenshot 2019-11-28 at 09 41 47

Are you running the project while refactoring? 😄 Let me know if you have any issues running it

**Comment by MichaelDeBoey** [comment]
@christianalfoni This PR is waiting from before the #Hacktoberfest event.

I can't see the "Open VSCode Settings" button in production or my refactor, so I'm not sure how you can thb.

Will look into the width of the TextArea tho 🙂

**Comment by MichaelDeBoey** [comment]
> I can't see the "Open VSCode Settings" button in production or my refactor, so I'm not sure how you can thb.

Found out this is because of the [`VSCodePlaceholder` component](https://github.com/codesandbox/codesandbox-client/blob/master/packages/app/src/app/pages/common/Modals/PreferencesModal/VSCodePlaceholder.js), which needs `store.preferences.settings.experimentVSCode`.
https://github.com/codesandbox/codesandbox-client/blob/a4513fbe7d71b1c6922814bb2519c56e57c77d8b/packages/app/src/app/pages/common/Modals/PreferencesModal/VSCodePlaceholder.js#L10

Since there are no experiments atm, I can't test this out unfortunattely
https://github.com/codesandbox/codesandbox-client/blob/a4513fbe7d71b1c6922814bb2519c56e57c77d8b/packages/app/src/app/pages/common/Modals/PreferencesModal/Experiments/index.tsx#L17-L18

**Comment by MichaelDeBoey** [comment]
Found out the reason the "Open VSCode Settings" button isn't shown.

You need to be inside a sandbox to see it (so opening `Preferences` on dashboard won't show it):

https://github.com/codesandbox/codesandbox-client/blob/a4513fbe7d71b1c6922814bb2519c56e57c77d8b/packages/app/src/app/pages/common/Modals/PreferencesModal/VSCodePlaceholder.js#L31-L41
https://github.com/codesandbox/codesandbox-client/blob/a4513fbe7d71b1c6922814bb2519c56e57c77d8b/packages/common/src/utils/url-generator.ts#L58

**Comment by MichaelDeBoey** [comment]
@christianalfoni Resolved discussions + simplified components since `settings.experimentVSCode` is always `true` 🙂

**Comment by MichaelDeBoey** [comment]
Thanks! 🙂

**Pull request merged**
