### PR TITLE
[WIP] Sandbox Search

### PR DESCRIPTION
**Pull request by SaraVieira**
Adds a search to a sandbox using a worker

Figma file: https://www.figma.com/file/xjB6dL48lshfiIa5jIfWwe/Global-Search?node-id=1%3A2

Things to be done:

- [x]  Global Search
- [x]  Make typing faster
- [x]  Toggle ability to search case sensitive
- [x]  Allow Regex
- [x]  Add files to include
- [ ]  Profit

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/5458/commits/db1a24a61f95d7df2c25e1312652df5b710ff61c failed.

**Comment by CompuIves** [comment]
From Slack:

Sometimes the items they clip (eg. `clipboard.ts` goes through the result item and I can't click the result item):

image

The context is a bit small:

**Comment by CompuIves** [comment]
I think on the covering items between different items, it might be that `react-window` is getting a different height than the real element height 🤔

**Comment by SaraVieira** [comment]
@CompuIves All issues there are now fixed and most logic was moved to overmind

**Comment by siddharthkp** [comment]
Code looks good, nothing stands out as bad

Found a tiny bug in the implementation - seems like new lines are squashed in the results:

Other than this, if we have design signoff, ship it :shipit: 

image

**Comment by DannyRuchtie** [comment]
Looks good!

**Comment by SaraVieira** [comment]
Let's hope for the best

**Pull request merged**
