### PR TITLE
feat: add Inter to google font picker

### PR DESCRIPTION
**Pull request by ryanpwaldon**
## What kind of change does this PR introduce?

Feature (minor addition).

## What is the new behavior?

User can now add the Inter font as an external resource (via the Google Fonts picker).

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

1. Visit an existing sandbox;
2. Select _Inter_ via the Google Fonts picker;
3. Inter is successfully added as an external resource, and is functional as intended.

## Checklist

- [x] Documentation
- [x] Testing 
- [x] Ready to be merged
      
- [x] Added myself to contributors table
      

## Notes

Inter was only added to Google Fonts on the 6th of March, so I presume it was unintentionally left out. But if, for whatever reason, you prefer not to include it – that's totally fine 😄

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/5010/commits/5b0eef9192dea3928ddfcae7d46bf7694187024b is at https://pr5010.build.csb.dev/s/new.

**Comment by SaraVieira** [comment]
Nice!

Sorry, it took so long to test, having some issues with the PR environment :( 

Thank you so much!

**Comment by SaraVieira** [comment]
sorry, forgot how to git

**Comment by ryanpwaldon** [comment]
You're too fast, thanks Sara!

**Pull request merged**
