### PR TITLE
🔨 Switch PreferencesModal to use useOvermind

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Follow-up of #2746, #2758, #2841, #2918, #3475, #3573, #3600, #3715 & #4226

Things I did extra:
- Change `itemIdChanged`'s signature to accept a `string` instead of `{ itemId: string }`, because it only has 1 argument
- Use `FunctionComponent` instead of `React.FC`, since [it's the same](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f13238a5d2086cd87f3209704f8897f7f701d957/types/react/index.d.ts#L513), but `FunctionComponent` is a bit clearer I think
- Type `bindValue` functions
- Make `Integrations` & `SideNavigation` a `FunctionComponent`
- Move `overmind` subscriptions as close as possible to the components itself instead of passing it through
- Simplify `PreferencesModal`'s `getItems` function so it doesn't render the components already when running it
- Export `PreferencesModal` by a named export  instead of a `default export`
- Calculate the default value of `comments` within the `useState` function instead of using a `useEffect` in `Comments` expriment
- Extract `Card` component out of `PaymentInfo`

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3429/commits/9a38b73bbfb90af20eabd572615d826ee101a121 is at https://pr3429.build.csb.dev/s/new.

**Comment by SaraVieira** [comment]
@MichaelDeBoey Can you please solve the conflicts?

**Comment by MichaelDeBoey** [comment]
@SaraVieira Rebased on `upstream/master` 🙂

**Comment by SaraVieira** [comment]
Hey

If you click on something like experiments the whole thing collapses :(

Screenshot 2020-02-17 at 15 48 06

**Comment by MichaelDeBoey** [comment]
@SaraVieira Will take a look at it later today when I have some time 🙂

**Comment by MichaelDeBoey** [comment]
@SaraVieira I've fixed the collapsing 🙂

**Comment by MichaelDeBoey** [comment]
@SaraVieira I've rebased onto `upstream/master`, so this could be merged now 🙂

**Comment by MichaelDeBoey** [comment]
@SaraVieira I've rebased onto `upstream/master`, so this could be merged now 🙂

**Comment by SaraVieira** [comment]
Danke!!

**Comment by MichaelDeBoey** [comment]
Always a pleasure! 🙂

**Pull request merged**
