### PR TITLE
🔨 Cleanup components package

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Follow-up of #4506

When merging `master` into #4506, some things went missing/wrong (especially in `package.json`).
So I reverted that PR and cherry-picked all the commits afterwards.

This PR is the result of how #4506 should have been.

### CODE REVIEW

**Comment by SaraVieira** [comment]
Hey

I was the one that reverted those things because we need a lot of testing before updating dependencies

**Comment by MichaelDeBoey** [comment]
@SaraVieira That's why we have the visual tests, no? 🤔

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/4861/commits/3e15e8796f62a37decb4ba935ef1f1852a476fcb is at https://pr4861.build.csb.dev/s/new.

**Comment by MichaelDeBoey** [comment]
@SaraVieira I only updated minor versions, so no breaking changes too.
I also deleted some packages that weren't used anywhere in the `@codesandbox/components` packages and added some packages that weren't in the (dev)dependency list.

Updated to latest minor without breaking changes:
- `@reach/auto-id`
- `@reach/menu-button`
- `@reach/skip-nav`
- `@reach/tooltip`
- `@reach/visually-hidden`
- `chromatic`
- `@storybook/*`
- `@types/styled-components`
- `rimraf`
- `simple-git`

Deleted since they're not used:
- `codesandbox-api`
- `date-fns`
- `typeface-inter`
- `@storybook/csf`
- `@types/lodash`
- `cpx`
- `np`
- `postinstall-postinstall`

Added because they weren't in the (dev)dependency list:
- `react-is`
- `@types/dot-object`
- `@types/react-tagsinput`
- `execa`
- `react`
- `react-dom`

**Comment by christianalfoni** [comment]
Thanks for helping us clean up!

Due to the time we spend reviewing and testing PRs we are forced to evaluate cost/benefit of all well intended contributions. This PR seems to be stylistic in nature, meaning it does not seem to improve user or developer experience in a noticeable way. We are very sorry that you spent time on this, only to see us closing the PR. But we hope you understand our reasoning and do not feel discouraged to make other contributions 😄

**Pull request closed without merging**
