### PR TITLE
Minor Website Updates

### PR DESCRIPTION
**Pull request by codebryo**
This branch adds a few updates to the main page.

1. I try to replace the main references to play.js
2. Add references to CodeSandbox for iOS on the product dropdown
3. Also fix the job number

image
^ Updated the copy and links

image
^ Mobile menu update

image
^ Desktop View Menu with Job hint

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/6710/commits/dfe4f165a7ad4e7c34da3010aad4d4b30ad1d596 is at https://pr6710.build.csb.dev/s/new.

**Comment by danilowoz** [comment]
It looks good to me

Don't we have a proper icon for iOS? It looks weird two links with the same icon
Screenshot 2022-05-25 at 14 03 43

**Comment by codebryo** [comment]
If there is a second Icon would be good. For now afailk it's the same Icon.

**Comment by codebryo** [comment]
Updated the images - although format is a little off so I need to update the screenshots to verify

**Pull request merged**
