### PR TITLE
Open folder on drag over it / Ignore thumbnail cache files

### PR DESCRIPTION
**Pull request by yeion7**
## What kind of change does this PR introduce?

improve

## What is the new behavior?
When someone what drag a file inside a folder, the folder don't open when drag a file over it 

when you upload a folder, system cache files are upload also

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

Open folder when drag file over it

Ignore `DS_Store` and `Thumbs.db`

Also I migrated this component to TS and overmind

1. Open sandbox
2. Drag folder over sandbox files, and don't should upload `DS_Store` file
3. Drag file inside folder, folder should open when drag over it

## Checklist

- [ ] Documentation
- [ ] Testing 
- [x] Ready to be merged
      
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/2951/commits/149a5c467c53beffd4928468f284378493432c00 is at https://pr2951.build.csb.dev/s/new.

**Comment by yeion7** [comment]
nice catch!

I don't close the folder because if the you regret and don't move the folder is better experience keep it folder open, but if you think is better close the folder when you drag, let me know

**Comment by yeion7** [comment]
@CompuIves @christianalfoni I rebased this PR and everything seems works 🤞🏼

**Comment by CompuIves** [comment]
Great @yeion7!! I can take a look today. I think keeping the folder open sounds good, your reasoning is good.

**Comment by yeion7** [comment]
wow! 🎉 thanks for all your help with this @SaraVieira

**Comment by yeion7** [comment]
> Tested:
> 
> * Create folder
> * Create file
> * Delete file
> * Delete folder
> * Move file to closed folder (it opens)
> * Uploading files
> * Rename files
> * Rename folder

@christianalfoni I've seen you test a lot of times this scenarios manually, is it ok if I work to add test to this scenarios?

**Comment by CompuIves** [comment]
That would be reaaaally awesome @yeion7!

**Pull request merged**
