### PR TITLE
feat(tracking): editor more menu event

### PR DESCRIPTION
**Pull request by danilowoz**
| Tested | Where | Event name |
| :-: | :- | :- |
| ⛔️  | Vertical more option (3 dots) | Editor - Click More Menu |  
| ⛔️  | Pricing page link under share sandbox | Editor - Share sandbox Pricing link | 
| ⛔️  | Upgrade Pro under the workspace | Dashboard - Workspace Settings Pro link |
| ⛔️  | Every like icon | Sandbox - Like & Sandbox - Undo Like | 
| ⛔️  | Deployment Modal | Editor - Open Netlify Site |
| ⛔️  | Pro page - switching plan | Pro - Set billing interval |
| ⛔️  | Pro page - change workspace switcher | Pro - Change Workspace |

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/5860/commits/130e72bf30bc924e439b226817f218bc19f26aed is at https://pr5860.build.csb.dev/s/new.

**Comment by tromika** [comment]
@danilowoz the event names looks good to me!

**Review by DannyRuchtie — APPROVED** [review]
Looking good!

**Comment by danilowoz** [comment]
## TODO
- [ ] Sandbox - Like & Sandbox - Undo Like doesn't work in the grid view

**Pull request merged**
