### PR TITLE
fix(profile): show no sandboxes found message in Liked Sandboxes Page

### PR DESCRIPTION
**Pull request by jyash97**
## What kind of change does this PR introduce?
Enhancement

## What is the current behavior?
Shows no messages but have active buttons as seen in below screenshot.

image

## What is the new behavior?
Shows no sandboxes message.
image

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

1. Tested with no liked sandboxes
2. Tested with Liked Sandboxes

## Checklist

- [x] Testing 
- [x] Ready to be merged
      
      

____
Can we add a `.nvmrc` file?  Whenever opening a new session to run scripts, I need to manually use the node version for eg: `nvm use 10.22.1`

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/5393/commits/f87cc77dabb3686d03a8edd610e773f523ca27c2 is at https://pr5393.build.csb.dev/s/new.

**Comment by SaraVieira** [comment]
I had no idea nvmrc was a thing, I use https://github.com/tj/n because it just looked simpler at the time but it does sound like a good idea to add that since nvm is the most used one

**Review by SaraVieira — APPROVED** [review]
Thank you! Looks great!!!

**Comment by jyash97** [comment]
Thanks for the fix and the quick review :)

**Pull request merged**
