### PR TITLE
🔨 Refactor Chat to use Hooks, TypeScript

### PR DESCRIPTION
**Pull request by Saeris**
Applied coding conventions to Workspace Chat component.

Can't test locally. @CompuIves is it possible to test live coding sessions on staging?

### CODE REVIEW

**Comment by CompuIves** [comment]
Deployed to staging!

**Comment by SaraVieira** [comment]
How is this working?

**Comment by CompuIves** [comment]
When you open a live session you can enable chat in the Live session tab. This enables chat for everyone and they can chat with eachother.

**Comment by Saeris** [comment]
Also super out of date, so closing. If this still needs to be refactored it can be done in a new PR.

**Pull request closed without merging**
