### PR TITLE
feat(editor): add experiment to onboarding the live session feature GRO-9

### PR DESCRIPTION
**Pull request by danilowoz**
New experiment to onboarding the Share/Live session feature in the editor, but this will only appear when it covers some conditionals:
- The key on localstorage has never been filled (`csb.onboarding-share`);
- The experiment value is `B` (`share-onboarding` experiement);

Also, once the user clicks on the Share button, the onboarding will be considered as done.

Todo:
- [x] Create an experiment in production, @tromika can you address this, please? The key must be `share-onboarding`

| A | B | 
| - | - |
| Nothing | Screenshot 2021-07-02 at 11 26 45 |

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/5941/commits/bbc2ccd39f06843e441eaf19ec558d9134e67564 is at https://pr5941.build.csb.dev/s/new.

**Comment by tromika** [comment]
@danilowoz would it be possible to add a tracking event(Editor - Close - Share onboarding) if users close the onboarding with the x? It helps understand users clicks. Thanks in advance!

**Comment by danilowoz** [comment]
Just added @tromika!

**Review by DannyRuchtie — CHANGES_REQUESTED** [review]
Could you add an overflow hidden on the element so the image is not overlapping the border in the corners? 

Screenshot 2021-07-09 at 11 48 49
Screenshot 2021-07-09 at 11 48 41

https://user-images.githubusercontent.com/46239581/125059322-7ad8f380-e0ab-11eb-8ae4-e4198c83eb61.mov

**Review by DannyRuchtie — APPROVED** [review]

**Pull request merged**
