### PR TITLE
Add horizon dark theme

### LINKED ISSUE #5139: Theme request: Horizon Dark
# 🌈 Feature
It is absolutely beautiful, here are some screenshots: 
<details>
<summary>Screenshots:</summary>

image
image
image

</details>
 And here is the export from VSCode: 
<details>
<summary>Show</summary>

```jsonc
{
    "$schema": "vscode://schemas/color-theme",
    "type": "dark",
    "colors": {
        "activityBar.background": "#1c1e26",
        "activityBar.foreground": "#d5d8dab3",
        "activityBarBadge.background": "#e95378",
        "activityBarBadge.foreground": "#06060c",
        "badge.background": "#2e303e",
        "badge.foreground": "#d5d8da",
        "breadcrumbPicker.background": "#232530",
        "button.background": "#2e303e",
        "debugToolBar.background": "#1c1e26",
        "diffEditor.insertedTextBackground": "#09f7a01a",
        "diffEditor.removedTextBackground": "#f43e5c1a",
        "dropdown.background": "#232530",
        "dropdown.listBackground": "#2e303e",
        "editor.background": "#1c1e26",
        "editor.findMatchBackground": "#6c6f9380",
        "editor.findMatchHighlightBackground": "#6c6f934d",
        "editor.findRangeHighlightBackground": "#6c6f931a",
        "editor.hoverHighlightBackground": "#6c6f934d",
        "editor.lineHighlightBackground": "#2e303e4d",
        "editor.rangeHighlightBackground": "#2e303e80",
        "editor.selectionBackground": "#2e303eb3",
        "editor.selectionHighlightBackground": "#6c6f934d",
        "editor.wordHighlightBackground": "#6c6f9380",
        "editor.wordHighlightStrongBackground": "#6c6f9380",
        "editorBracketMatch.background": "#6c6f9380",
        "editorBracketMatch.border": "#6c6f9300",
        "editorCodeLens.foreground": "#6c6f9380",
        "editorCursor.background": "#1c1e26",
        "editorCursor.foreground": "#e95378",
        "editorError.foreground": "#f43e5c",
        "editorGroup.border": "#1a1c23",
        "editorGroup.dropBackground": "#6c6f934d",
        "editorGroupHeader.tabsBackground": "#1c1e26",
        "editorGutter.addedBackground": "#09f7a0b3",
        "editorGutter.deletedBackground": "#f43e5cb3",
        "editorGutter.modifiedBackground": "#21bfc2b3",
        "editorIndentGuide.activeBackground": "#2e303e",
        "editorIndentGuide.background": "#2e303e80",
        "editorLineNumber.activeForeground": "#d5d8da80",
        "editorLineNumber.foreground": "#d5d8da1a",
        "editorOverviewRuler.addedForeground": "#09f7a080",
        "editorOverviewRuler.border": "#2e303eb3",
        "editorOverviewRuler.bracketMatchForeground": "#d5d8da80",
        "editorOverviewRuler.deletedForeground": "#f43e5c80",
        "editorOverviewRuler.errorForeground": "#f43e5ce6",
        "editorOverviewRuler.findMatchForeground": "#6c6f93",
        "editorOverviewRuler.modifiedForeground": "#21bfc280",
        "editorOverviewRuler.warningForeground": "#27d79780",
        "editorRuler.foreground": "#6c6f934d",
        "editorSuggestWidget.highlightForeground": "#e95378",
        "editorWarning.foreground": "#27d797b3",
        "editorWidget.background": "#232530",
        "editorWidget.border": "#232530",
        "errorForeground": "#f43e5c",
        "extensionButton.prominentBackground": "#e95378",
        "extensionButton.prominentHoverBackground": "#e9436d",
        "focusBorder": "#1a1c23",
        "foreground": "#d5d8da",
        "gitDecoration.addedResourceForeground": "#27d797b3",
        "gitDecoration.deletedResourceForeground": "#f43e5c",
        "gitDecoration.ignoredResourceForeground": "#d5d8da4d",
        "gitDecoration.modifiedResourceForeground": "#fab38e",
        "gitDecoration.untrackedResourceForeground": "#27d797",
        "input.background": "#2e303e",
        "inputOption.activeBorder": "#e9436d80",
        "inputValidation.errorBackground": "#f43e5c80",
        "inputValidation.errorBorder": "#f43e5c00",
        "list.activeSelectionBackground": "#2e303e80",
        "list.activeSelectionForeground": "#d5d8da",
        "list.dropBackground": "#6c6f9380",
        "list.errorForeground": "#f43e5ce6",
        "list.focusBackground": "#2e303e80",
        "list.focusForeground": "#d5d8da",
        "list.highlightForeground": "#e95378",
        "list.hoverBackground": "#2e303e80",
        "list.hoverForeground": "#d5d8da",
        "list.inactiveFocusBackground": "#2e303e80",
        "list.inactiveSelectionBackground": "#2e303e4d",
        "list.inactiveSelectionForeground": "#d5d8da",
        "list.warningForeground": "#27d797b3",
        "panelTitle.activeBorder": "#e95378",
        "peekView.border": "#1a1c23",
        "peekViewEditor.background": "#232530",
        "peekViewEditor.matchHighlightBackground": "#6c6f9380",
        "peekViewResult.background": "#232530",
        "peekViewResult.matchHighlightBackground": "#6c6f9380",
        "peekViewResult.selectionBackground": "#2e303e80",
        "peekViewTitle.background": "#232530",
        "pickerGroup.foreground": "#e95378e6",
        "progressBar.background": "#e95378",
        "scrollbar.shadow": "#16161c",
        "scrollbarSlider.activeBackground": "#6c6f9380",
        "scrollbarSlider.background": "#6c6f931a",
        "scrollbarSlider.hoverBackground": "#6c6f934d",
        "selection.background": "#6c6f9380",
        "sideBar.background": "#1c1e26",
        "sideBar.dropBackground": "#6c6f934d",
        "sideBar.foreground": "#d5d8da80",
        "sideBarSectionHeader.background": "#1c1e26",
        "sideBarSectionHeader.foreground": "#d5d8dab3",
        "statusBar.background": "#1c1e26",
        "statusBar.debuggingBackground": "#fab38e",
        "statusBar.debuggingForeground": "#06060c",
        "statusBar.foreground": "#d5d8da80",
        "statusBar.noFolderBackground": "#1c1e26",
        "statusBarItem.hoverBackground": "#2e303e",
        "statusBarItem.prominentBackground": "#2e303e",
        "statusBarItem.prominentHoverBackground": "#6c6f93",
        "tab.activeBorder": "#e95378",
        "tab.border": "#1c1e2600",
        "tab.inactiveBackground": "#1c1e26",
        "terminal.ansiBlue": "#26bbd9",
        "terminal.ansiBrightBlue": "#3fc4de",
        "terminal.ansiBrightCyan": "#6be4e6",
        "terminal.ansiBrightGreen": "#3fdaa4",
        "terminal.ansiBrightMagenta": "#f075b5",
        "terminal.ansiBrightRed": "#ec6a88",
        "terminal.ansiBrightYellow": "#fbc3a7",
        "terminal.ansiCyan": "#59e1e3",
        "terminal.ansiGreen": "#29d398",
        "terminal.ansiMagenta": "#ee64ac",
        "terminal.ansiRed": "#e95678",
        "terminal.ansiYellow": "#fab795",
        "terminal.foreground": "#d5d8da",
        "terminal.selectionBackground": "#6c6f934d",
        "terminalCursor.background": "#d5d8da",
        "terminalCursor.foreground": "#6c6f9380",
        "textLink.activeForeground": "#e9436d",
        "textLink.foreground": "#e95378",
        "titleBar.activeBackground": "#1c1e26",
        "titleBar.inactiveBackground": "#1c1e26",
        "walkThrough.embeddedEditorBackground": "#232530",
        "widget.shadow": "#16161c",
        //"activityBar.activeBorder": "#d5d8dab3",
        //"activityBar.dropBorder": "#d5d8dab3",
        //"activityBar.inactiveForeground": "#d5d8da48",
        //"breadcrumb.activeSelectionForeground": "#ecedee",
        //"breadcrumb.background": "#1c1e26",
        //"breadcrumb.focusForeground": "#ecedee",
        //"breadcrumb.foreground": "#d5d8dacc",
        //"button.foreground": "#ffffff",
        //"button.hoverBackground": "#37394a",
        //"button.secondaryBackground": "#3a3d41",
        //"button.secondaryForeground": "#ffffff",
        //"button.secondaryHoverBackground": "#45494e",
        //"charts.blue": "#75beff",
        //"charts.foreground": "#d5d8da",
        //"charts.green": "#89d185",
        //"charts.lines": "#d5d8da80",
        //"charts.orange": "#d18616",
        //"charts.purple": "#b180d7",
        //"charts.red": "#f43e5c",
        //"charts.yellow": "#27d797b3",
        //"checkbox.background": "#232530",
        //"checkbox.border": "#232530",
        //"checkbox.foreground": "#f0f0f0",
        //"debugConsole.errorForeground": "#f43e5c",
        //"debugConsole.infoForeground": "#75beff",
        //"debugConsole.sourceForeground": "#d5d8da",
        //"debugConsole.warningForeground": "#27d797b3",
        //"debugConsoleInputIcon.foreground": "#d5d8da",
        //"debugExceptionWidget.background": "#420b0d",
        //"debugExceptionWidget.border": "#a31515",
        //"debugIcon.breakpointCurrentStackframeForeground": "#ffcc00",
        //"debugIcon.breakpointDisabledForeground": "#848484",
        //"debugIcon.breakpointForeground": "#e51400",
        //"debugIcon.breakpointStackframeForeground": "#89d185",
        //"debugIcon.breakpointUnverifiedForeground": "#848484",
        //"debugIcon.continueForeground": "#75beff",
        //"debugIcon.disconnectForeground": "#f48771",
        //"debugIcon.pauseForeground": "#75beff",
        //"debugIcon.restartForeground": "#89d185",
        //"debugIcon.startForeground": "#89d185",
        //"debugIcon.stepBackForeground": "#75beff",
        //"debugIcon.stepIntoForeground": "#75beff",
        //"debugIcon.stepOutForeground": "#75beff",
        //"debugIcon.stepOverForeground": "#75beff",
        //"debugIcon.stopForeground": "#f48771",
        //"debugTokenExpression.boolean": "#4e94ce",
        //"debugTokenExpression.error": "#f48771",
        //"debugTokenExpression.name": "#c586c0",
        //"debugTokenExpression.number": "#b5cea8",
        //"debugTokenExpression.string": "#ce9178",
        //"debugTokenExpression.value": "#cccccc99",
        //"debugView.exceptionLabelBackground": "#6c2022",
        //"debugView.exceptionLabelForeground": "#d5d8da",
        //"debugView.stateLabelBackground": "#88888844",
        //"debugView.stateLabelForeground": "#d5d8da",
        //"debugView.valueChangedHighlight": "#569cd6",
        //"descriptionForeground": "#d5d8dab3",
        //"diffEditor.diagonalFill": "#cccccc33",
        //"dropdown.border": "#232530",
        //"dropdown.foreground": "#f0f0f0",
        //"editor.focusedStackFrameHighlightBackground": "#7abd7a4d",
        //"editor.foldBackground": "#2e303e36",
        //"editor.foreground": "#bbbbbb",
        //"editor.inactiveSelectionBackground": "#2e303e5a",
        //"editor.lineHighlightBorder": "#282828",
        //"editor.onTypeRenameBackground": "#ff00004d",
        //"editor.snippetFinalTabstopHighlightBorder": "#525252",
        //"editor.snippetTabstopHighlightBackground": "#7c7c7c4d",
        //"editor.stackFrameHighlightBackground": "#ffff0033",
        //"editor.symbolHighlightBackground": "#6c6f934d",
        //"editorActiveLineNumber.foreground": "#c6c6c6",
        //"editorGroupHeader.noTabsBackground": "#1c1e26",
        //"editorGutter.background": "#1c1e26",
        //"editorGutter.commentRangeForeground": "#c5c5c5",
        //"editorGutter.foldingControlForeground": "#c5c5c5",
        //"editorHint.foreground": "#eeeeeeb3",
        //"editorHoverWidget.background": "#232530",
        //"editorHoverWidget.border": "#232530",
        //"editorHoverWidget.foreground": "#d5d8da",
        //"editorHoverWidget.statusBarBackground": "#2a2c3a",
        //"editorInfo.foreground": "#75beff",
        //"editorLightBulb.foreground": "#ffcc00",
        //"editorLightBulbAutoFix.foreground": "#75beff",
        //"editorLink.activeForeground": "#4e94ce",
        //"editorMarkerNavigation.background": "#2d2d30",
        //"editorMarkerNavigationError.background": "#f43e5c",
        //"editorMarkerNavigationInfo.background": "#75beff",
        //"editorMarkerNavigationWarning.background": "#27d797b3",
        //"editorOverviewRuler.commonContentForeground": "#60606066",
        //"editorOverviewRuler.currentContentForeground": "#40c8ae80",
        //"editorOverviewRuler.incomingContentForeground": "#40a6ff80",
        //"editorOverviewRuler.infoForeground": "#75beff",
        //"editorOverviewRuler.rangeHighlightForeground": "#007acc99",
        //"editorOverviewRuler.selectionHighlightForeground": "#a0a0a0cc",
        //"editorOverviewRuler.wordHighlightForeground": "#a0a0a0cc",
        //"editorOverviewRuler.wordHighlightStrongForeground": "#c0a0c0cc",
        //"editorPane.background": "#1c1e26",
        //"editorSuggestWidget.background": "#232530",
        //"editorSuggestWidget.border": "#232530",
        //"editorSuggestWidget.foreground": "#bbbbbb",
        //"editorSuggestWidget.selectedBackground": "#2e303e80",
        //"editorUnnecessaryCode.opacity": "#000000aa",
        //"editorWhitespace.foreground": "#e3e4e229",
        //"editorWidget.foreground": "#d5d8da",
        //"extensionBadge.remoteBackground": "#e95378",
        //"extensionBadge.remoteForeground": "#06060c",
        //"extensionButton.prominentForeground": "#ffffff",
        //"gitDecoration.conflictingResourceForeground": "#6c6cc4",
        //"gitDecoration.stageDeletedResourceForeground": "#c74e39",
        //"gitDecoration.stageModifiedResourceForeground": "#e2c08d",
        //"gitDecoration.submoduleResourceForeground": "#8db9e2",
        //"icon.foreground": "#c5c5c5",
        //"imagePreview.border": "#80808059",
        //"input.foreground": "#d5d8da",
        //"input.placeholderForeground": "#d5d8da80",
        //"inputOption.activeBackground": "#1a1c2366",
        //"inputOption.activeForeground": "#ffffff",
        //"inputValidation.infoBackground": "#063b49",
        //"inputValidation.infoBorder": "#007acc",
        //"inputValidation.warningBackground": "#352a05",
        //"inputValidation.warningBorder": "#b89500",
        //"list.deemphasizedForeground": "#8c8c8c",
        //"list.filterMatchBackground": "#6c6f934d",
        //"list.invalidItemForeground": "#b89500",
        //"listFilterWidget.background": "#653723",
        //"listFilterWidget.noMatchesOutline": "#be1100",
        //"listFilterWidget.outline": "#00000000",
        //"menu.background": "#232530",
        //"menu.foreground": "#f0f0f0",
        //"menu.selectionBackground": "#2e303e80",
        //"menu.selectionForeground": "#d5d8da",
        //"menu.separatorBackground": "#bbbbbb",
        //"menubar.selectionBackground": "#ffffff1a",
        //"menubar.selectionForeground": "#cccccc",
        //"merge.commonContentBackground": "#60606029",
        //"merge.commonHeaderBackground": "#60606066",
        //"merge.currentContentBackground": "#40c8ae33",
        //"merge.currentHeaderBackground": "#40c8ae80",
        //"merge.incomingContentBackground": "#40a6ff33",
        //"merge.incomingHeaderBackground": "#40a6ff80",
        //"minimap.errorHighlight": "#ff1212b3",
        //"minimap.findMatchHighlight": "#d18616",
        //"minimap.selectionHighlight": "#264f78",
        //"minimap.warningHighlight": "#27d797b3",
        //"minimapGutter.addedBackground": "#587c0c",
        //"minimapGutter.deletedBackground": "#94151b",
        //"minimapGutter.modifiedBackground": "#0c7d9d",
        //"minimapSlider.activeBackground": "#6c6f9340",
        //"minimapSlider.background": "#6c6f930d",
        //"minimapSlider.hoverBackground": "#6c6f9327",
        //"notebook.cellBorderColor": "#80808024",
        //"notebook.cellHoverBackground": "#80808012",
        //"notebook.cellInsertionIndicator": "#1a1c23",
        //"notebook.cellStatusBarItemHoverBackground": "#ffffff26",
        //"notebook.cellToolbarSeparator": "#80808059",
        //"notebook.focusedCellBackground": "#80808024",
        //"notebook.focusedCellBorder": "#ffffff1f",
        //"notebook.focusedEditorBorder": "#1a1c23",
        //"notebook.focusedRowBorder": "#ffffff1f",
        //"notebook.outputContainerBackgroundColor": "#80808024",
        //"notebook.rowHoverBackground": "#80808012",
        //"notebook.symbolHighlightBackground": "#ffffff0b",
        //"notebookScrollbarSlider.activeBackground": "#6c6f9380",
        //"notebookScrollbarSlider.background": "#6c6f931a",
        //"notebookScrollbarSlider.hoverBackground": "#6c6f934d",
        //"notebookStatusErrorIcon.foreground": "#f43e5c",
        //"notebookStatusRunningIcon.foreground": "#d5d8da",
        //"notebookStatusSuccessIcon.foreground": "#89d185",
        //"notificationCenterHeader.background": "#2e303f",
        //"notificationLink.foreground": "#e95378",
        //"notifications.background": "#232530",
        //"notifications.border": "#2e303f",
        //"notifications.foreground": "#d5d8da",
        //"notificationsErrorIcon.foreground": "#f43e5c",
        //"notificationsInfoIcon.foreground": "#75beff",
        //"notificationsWarningIcon.foreground": "#27d797b3",
        //"panel.background": "#1c1e26",
        //"panel.border": "#80808059",
        //"panel.dropBorder": "#e7e7e7",
        //"panelSection.border": "#80808059",
        //"panelSection.dropBackground": "#6c6f934d",
        //"panelSectionHeader.background": "#80808033",
        //"panelTitle.activeForeground": "#e7e7e7",
        //"panelTitle.inactiveForeground": "#e7e7e799",
        //"peekViewEditorGutter.background": "#232530",
        //"peekViewResult.fileForeground": "#ffffff",
        //"peekViewResult.lineForeground": "#bbbbbb",
        //"peekViewResult.selectionForeground": "#ffffff",
        //"peekViewTitleDescription.foreground": "#ccccccb3",
        //"peekViewTitleLabel.foreground": "#ffffff",
        //"pickerGroup.border": "#3f3f46",
        //"problemsErrorIcon.foreground": "#f43e5c",
        //"problemsInfoIcon.foreground": "#75beff",
        //"problemsWarningIcon.foreground": "#27d797b3",
        //"quickInput.background": "#232530",
        //"quickInput.foreground": "#d5d8da",
        //"quickInputTitle.background": "#ffffff1b",
        //"scm.providerBorder": "#454545",
        //"searchEditor.findMatchBackground": "#6c6f9333",
        //"settings.checkboxBackground": "#232530",
        //"settings.checkboxBorder": "#232530",
        //"settings.checkboxForeground": "#f0f0f0",
        //"settings.dropdownBackground": "#232530",
        //"settings.dropdownBorder": "#232530",
        //"settings.dropdownForeground": "#f0f0f0",
        //"settings.dropdownListBorder": "#232530",
        //"settings.focusedRowBackground": "#80808024",
        //"settings.headerForeground": "#e7e7e7",
        //"settings.modifiedItemIndicator": "#0c7d9d",
        //"settings.numberInputBackground": "#2e303e",
        //"settings.numberInputForeground": "#d5d8da",
        //"settings.textInputBackground": "#2e303e",
        //"settings.textInputForeground": "#d5d8da",
        //"sideBarTitle.foreground": "#d5d8da80",
        //"statusBar.noFolderForeground": "#d5d8da80",
        //"statusBarItem.activeBackground": "#ffffff2e",
        //"statusBarItem.prominentForeground": "#d5d8da80",
        //"statusBarItem.remoteBackground": "#e95378",
        //"statusBarItem.remoteForeground": "#06060c",
        //"symbolIcon.arrayForeground": "#d5d8da",
        //"symbolIcon.booleanForeground": "#d5d8da",
        //"symbolIcon.classForeground": "#ee9d28",
        //"symbolIcon.colorForeground": "#d5d8da",
        //"symbolIcon.constantForeground": "#d5d8da",
        //"symbolIcon.constructorForeground": "#b180d7",
        //"symbolIcon.enumeratorForeground": "#ee9d28",
        //"symbolIcon.enumeratorMemberForeground": "#75beff",
        //"symbolIcon.eventForeground": "#ee9d28",
        //"symbolIcon.fieldForeground": "#75beff",
        //"symbolIcon.fileForeground": "#d5d8da",
        //"symbolIcon.folderForeground": "#d5d8da",
        //"symbolIcon.functionForeground": "#b180d7",
        //"symbolIcon.interfaceForeground": "#75beff",
        //"symbolIcon.keyForeground": "#d5d8da",
        //"symbolIcon.keywordForeground": "#d5d8da",
        //"symbolIcon.methodForeground": "#b180d7",
        //"symbolIcon.moduleForeground": "#d5d8da",
        //"symbolIcon.namespaceForeground": "#d5d8da",
        //"symbolIcon.nullForeground": "#d5d8da",
        //"symbolIcon.numberForeground": "#d5d8da",
        //"symbolIcon.objectForeground": "#d5d8da",
        //"symbolIcon.operatorForeground": "#d5d8da",
        //"symbolIcon.packageForeground": "#d5d8da",
        //"symbolIcon.propertyForeground": "#d5d8da",
        //"symbolIcon.referenceForeground": "#d5d8da",
        //"symbolIcon.snippetForeground": "#d5d8da",
        //"symbolIcon.stringForeground": "#d5d8da",
        //"symbolIcon.structForeground": "#d5d8da",
        //"symbolIcon.textForeground": "#d5d8da",
        //"symbolIcon.typeParameterForeground": "#d5d8da",
        //"symbolIcon.unitForeground": "#d5d8da",
        //"symbolIcon.variableForeground": "#75beff",
        //"tab.activeBackground": "#1c1e26",
        //"tab.activeForeground": "#ffffff",
        //"tab.activeModifiedBorder": "#3399cc",
        //"tab.inactiveForeground": "#ffffff80",
        //"tab.inactiveModifiedBorder": "#3399cc80",
        //"tab.lastPinnedBorder": "#585858",
        //"tab.unfocusedActiveBackground": "#1c1e26",
        //"tab.unfocusedActiveBorder": "#e9537880",
        //"tab.unfocusedActiveForeground": "#ffffff80",
        //"tab.unfocusedActiveModifiedBorder": "#3399cc80",
        //"tab.unfocusedInactiveBackground": "#1c1e26",
        //"tab.unfocusedInactiveForeground": "#ffffff40",
        //"tab.unfocusedInactiveModifiedBorder": "#3399cc40",
        //"terminal.ansiBlack": "#000000",
        //"terminal.ansiBrightBlack": "#666666",
        //"terminal.ansiBrightWhite": "#e5e5e5",
        //"terminal.ansiWhite": "#e5e5e5",
        //"terminal.border": "#80808059",
        //"textBlockQuote.background": "#7f7f7f1a",
        //"textBlockQuote.border": "#007acc80",
        //"textCodeBlock.background": "#0a0a0a66",
        //"textPreformat.foreground": "#d7ba7d",
        //"textSeparator.foreground": "#ffffff2e",
        //"titleBar.activeForeground": "#cccccc",
        //"titleBar.inactiveForeground": "#cccccc99",
        //"tree.indentGuidesStroke": "#585858"
    },
    "tokenColors": [
        {
            "scope": "comment",
            "settings": {
                "foreground": "#BBBBBB4D",
                "fontStyle": "italic"
            }
        },
        {
            "scope": "constant",
            "settings": {
                "foreground": "#F09483E6"
            }
        },
        {
            "scope": "constant.character.escape",
            "settings": {
                "foreground": "#25B0BCE6"
            }
        },
        {
            "scope": "entity.name",
            "settings": {
                "foreground": "#FAC29AE6"
            }
        },
        {
            "scope": "entity.name.function",
            "settings": {
                "foreground": "#25B0BCE6"
            }
        },
        {
            "scope": "entity.name.tag",
            "settings": {
                "foreground": "#E95678E6",
                "fontStyle": "normal"
            }
        },
        {
            "scope": [
                "entity.name.type",
                "storage.type.cs"
            ],
            "settings": {
                "foreground": "#FAC29AE6"
            }
        },
        {
            "scope": "entity.other.attribute-name",
            "settings": {
                "foreground": "#F09483E6",
                "fontStyle": "italic"
            }
        },
        {
            "scope": "entity.other.inherited-class",
            "settings": {
                "foreground": "#FAB795E6"
            }
        },
        {
            "scope": "entity.other.attribute-name.id",
            "settings": {
                "foreground": "#25B0BCE6"
            }
        },
        {
            "scope": [
                "entity.other.attribute-name.pseudo-element",
                "entity.other.attribute-name.pseudo-class"
            ],
            "settings": {
                "foreground": "#FAB795E6"
            }
        },
        {
            "scope": [
                "entity.name.variable",
                "variable"
            ],
            "settings": {
                "foreground": "#E95678E6"
            }
        },
        {
            "scope": "keyword",
            "settings": {
                "foreground": "#B877DBE6",
                "fontStyle": "italic"
            }
        },
        {
            "scope": "keyword.operator",
            "settings": {
                "foreground": "#BBBBBB"
            }
        },
        {
            "scope": [
                "keyword.operator.new",
                "keyword.operator.expression",
                "keyword.operator.logical",
                "keyword.operator.delete"
            ],
            "settings": {
                "foreground": "#B877DBE6"
            }
        },
        {
            "scope": "keyword.other.unit",
            "settings": {
                "foreground": "#F09483E6"
            }
        },
        {
            "scope": "markup.quote",
            "settings": {
                "foreground": "#FAB795B3",
                "fontStyle": "italic"
            }
        },
        {
            "scope": [
                "markup.heading",
                "entity.name.section"
            ],
            "settings": {
                "foreground": "#E95678E6"
            }
        },
        {
            "scope": "markup.bold",
            "settings": {
                "foreground": "#B877DBE6",
                "fontStyle": "bold"
            }
        },
        {
            "scope": "markup.italic",
            "settings": {
                "foreground": "#25B0BCE6",
                "fontStyle": "italic"
            }
        },
        {
            "scope": [
                "markup.inline.raw",
                "markup.fenced_code.block"
            ],
            "settings": {
                "foreground": "#F09483E6"
            }
        },
        {
            "scope": "markup.underline.link",
            "settings": {
                "foreground": "#FAB795E6"
            }
        },
        {
            "scope": "storage",
            "settings": {
                "foreground": "#B877DBE6",
                "fontStyle": "italic"
            }
        },
        {
            "scope": [
                "string.quoted",
                "string.template"
            ],
            "settings": {
                "foreground": "#FAB795E6"
            }
        },
        {
            "scope": "string.regexp",
            "settings": {
                "foreground": "#F09483E6"
            }
        },
        {
            "scope": "string.other.link",
            "settings": {
                "foreground": "#F09483E6"
            }
        },
        {
            "scope": "support",
            "settings": {
                "foreground": "#FAC29AE6"
            }
        },
        {
            "scope": "support.function",
            "settings": {
                "foreground": "#25B0BCE6"
            }
        },
        {
            "scope": "support.variable",
            "settings": {
                "foreground": "#E95678E6"
            }
        },
        {
            "scope": [
                "support.type.property-name",
                "meta.object-literal.key"
            ],
            "settings": {
                "foreground": "#E95678E6"
            }
        },
        {
            "scope": "support.type.property-name.css",
            "settings": {
                "foreground": "#BBBBBB"
            }
        },
        {
            "scope": [
                "variable.language"
            ],
            "settings": {
                "foreground": "#FAC29AE6",
                "fontStyle": "italic"
            }
        },
        {
            "scope": "variable.parameter",
            "settings": {
                "fontStyle": "italic"
            }
        },
        {
            "scope": "string.template meta.embedded",
            "settings": {
                "foreground": "#BBBBBB"
            }
        },
        {
            "scope": "punctuation.definition.tag",
            "settings": {
                "foreground": "#E95678B3",
                "fontStyle": "normal"
            }
        },
        {
            "scope": "punctuation.separator",
            "settings": {
                "foreground": "#BBBBBB"
            }
        },
        {
            "scope": "punctuation.definition.template-expression",
            "settings": {
                "foreground": "#B877DBE6"
            }
        },
        {
            "scope": "punctuation.section.embedded",
            "settings": {
                "foreground": "#B877DBE6"
            }
        },
        {
            "scope": "punctuation.definition.list",
            "settings": {
                "foreground": "#F09483E6"
            }
        },
        {
            "scope": "token.info-token",
            "settings": {
                "foreground": "#6796E6"
            }
        },
        {
            "scope": "token.warn-token",
            "settings": {
                "foreground": "#CD9731"
            }
        },
        {
            "scope": "token.error-token",
            "settings": {
                "foreground": "#F44747"
            }
        },
        {
            "scope": "token.debug-token",
            "settings": {
                "foreground": "#B267E6"
            }
        }
    ]
}
```
</details>

### PR DESCRIPTION
**Pull request by SaraVieira**
Adds https://marketplace.visualstudio.com/items?itemName=jolaleye.horizon-theme-vscode

Only the dark version since all the light ones weirdly broke codesandbox

image

Closes #5139

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/5143/commits/b8c27857c7e3d2d2616352bfbc542c147cf558d0 is at https://pr5143.build.csb.dev/s/new.

**Comment by Explosion-Scratch** [comment]
Yeah, the light one looks amazing for VSCode but looks really weird in CSB. Thanks for making this PR btw!

**Comment by SaraVieira** [comment]
It also completly broke codesandbox, saying Maximum stack exceeded, so weird 🤷🏻‍♀️

**Comment by Explosion-Scratch** [comment]
The light one, right? (You didn't just merge something that broke it, right....)

**Comment by Explosion-Scratch** [comment]
Thanks though!

**Comment by SaraVieira** [comment]
Naaa, I just added the dark one :)

**Comment by Explosion-Scratch** [comment]
Okay! Just checking! :)

**Pull request merged**
