### PR TITLE
Update CI + embed blogpost

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
## What kind of change does this PR introduce?
Added some links to referenced projects, like we do in all other blogposts.
Also let the [`gatsby-remark-embedder`](https://github.com/MichaelDeBoey/gatsby-remark-embedder) Gatsby plugin embed the tweet instead of using an image.

## What is the current behavior?
- No links to referenced projects
- Image of tweet

## What is the new behavior?
- Links to referenced projects
- Embedded tweet

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

1. Go to blog page
2. Click on CI + embed post
3. Check that Tweet is embedded and referenced projects are linked too

## Checklist
- [N/A] Documentation
- [x] Testing
- [x] Ready to be merged
- [N/A] Added myself to contributors table

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3025/commits/6b87b8bb6481fd1d9623ad23262195a06629b752 is at https://pr3025.build.csb.dev/s/new.

**Comment by MichaelDeBoey** [comment]
@garethx If you look at [the preview,](https://pr3025.build.csb.dev/post/codesandbox-ci-embeds) the tweet is looking like it should look, no? 🤔

Schermafbeelding 2019-11-14 om 15 07 12

**Comment by MichaelDeBoey** [comment]
@garethx I've reverted linking to referenced projects 🙂

**Comment by MichaelDeBoey** [comment]
Ping @garethx

**Pull request merged**
