### PR TITLE
Bump react-devtools-inline from v4.4.0 to v4.13.2 

### PR DESCRIPTION
**Pull request by iChenLei**
## What kind of change does this PR introduce?
Bump `react-devtools-inline` from v4.4.0 to v4.13.2

## What is the current behavior?
It work, but lack many new feature and encount some bugs, to see [react-devtools-inline CHANGELOG](https://github.com/facebook/react/blob/master/packages/react-devtools/CHANGELOG.md)

## What is the new behavior?
More useful feature and more bugfix. ( I contributed a bugfix https://github.com/facebook/react/pull/20534

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

1. Step A
2. Step B
3. Step C

## Checklist

- [ ] Documentation
- [x] Testing 
- [x] Ready to be merged
      
- [ ] Added myself to contributors table

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/5779/commits/6c62144bc698cc809859a92d947ac139c87a33df is at https://pr5779.build.csb.dev/s/new.

**Comment by iChenLei** [comment]
Yep, we get a error.



Dose it is the reasom why react-devtools-inline crash ?



https://pr5779-d346v.build.csb.dev it's a crashed react app. @danilowoz

**Comment by danilowoz** [comment]
I was investigating the issue that might be causing this error in the dev tools, and it seems that the last version depends on [react@experimental version](https://github.com/facebook/react/issues/21023). Looking at the code, we can see that it uses a method called [`useCacheRefresh`](https://github.com/facebook/react/blob/2bf4805e4bd63dab45cd7f5e1ad32ef8fed3f6ab/packages/react-devtools-shared/src/devtools/views/Components/InspectedElementContext.js#L14) which are only available in > 17.

Does it make sense?

**Comment by iChenLei** [comment]
Thanks for your investigation, danilowoz. Maybe i need call @bvaughn (official react devtools maintainer). Hope he can solve this problem.

**Comment by bvaughn** [comment]
> I was investigating the issue that might be causing this error in the dev tools, and it seems that the last version depends on react@experimental version. Looking at the code, we can see that it uses a method called useCacheRefresh which are only available in > 17.

Yeah, unfortunately the `react-devtools-inline` package currently depends on experimental APIs that are only available in the "experimental" npm tagged release

**Comment by iChenLei** [comment]
@bvaughn wooo, thanks for your fast reply. sir. Can you give me some advices for upgrade react-devtools-inline ? just keep current version and wait the stable release version? or what ?

**Comment by bvaughn** [comment]
I think you might be okay updating to the latest 4.10 patch version, but 4.11+ integrates with new (experimental) Suspense APIs.

Alternately you could update to use the experimental channel temporarily, but that's a bigger decision.

**Pull request closed without merging**
