### PR TITLE
Add support for fetching tars for dependencies

### LINKED ISSUE #1570: Add dependency via tar.gz upload or URL
# 🌈 Feature

Sometimes it is nice to provide a demo of a package before it has been published. Or sometimes the package is published in a private npm repository. 

Providing the option to reference a dependency in `package.json` either by uploading the result of `npm pack` or alternatively specifying an accessible url to that file would make this possible.

### PR DESCRIPTION
**Pull request by CompuIves**
Fixes #1570 

Adds support for adding .tgz or .tar.gz files as dependency. Keep in mind that these external URLs need to have CORS enabled to download tars from them. If you need it to work without CORS, please let us know here!

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/4660/commits/4ab10752ae1811a81c5c3038e29a2c8b7821519b is at https://pr4660.build.csb.dev/s/new.

**Comment by CompuIves** [comment]
TODO: Add support for `file` protocol.

**Comment by eps1lon** [comment]
Really looking forward to this feature. Unfortunately it doesn't seem to work for our particular use case (probably due to CORS).

Using https://artprodsu6weu.artifacts.visualstudio.com/Aa6600ed7-e5f1-448b-ab05-5c895bc584d8/69af1cae-afce-45c2-9b8b-b56370b6d923/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL211aS1vcmcvcHJvamVjdElkLzY5YWYxY2FlLWFmY2UtNDVjMi05YjhiLWI1NjM3MGI2ZDkyMy9idWlsZElkLzExODgxL2FydGlmYWN0TmFtZS9jYW5hcmllcw2/content?format=file&subPath=%2Fmaterial-ui-core.tgz from https://dev.azure.com/mui-org/Material-UI/_build/results?buildId=11881&view=artifacts&type=publishedArtifacts produces a blank page: https://pr4660.build.csb.dev/s/peaceful-poitras-lgs1l?file=/package.json

**Comment by CompuIves** [comment]
Oh! I think that was a fluke with staging, it seems to work now for me @eps1lon 🎉 !

image

I'm curious: what is your use case for this?

**Comment by eps1lon** [comment]
> I'm curious: what is your use case for this?

Test the latest build from `master` (or any branch for that matter). codesandbox CI only builds PRs as far as I can tell.

**Comment by CompuIves** [comment]
Ah, that's a good use case. I'll also make sure to add building branches to the CodeSandbox CI roadmap!

**Comment by CompuIves** [comment]
Next thing to do is allow for a mix of dynamic resolving (using dynamic fetching) and using the packager. That will speed up CSB CI downloads as well.

**Pull request merged**
