### PR TITLE
feat: Add Astro and Vite icons to templates

### PR DESCRIPTION
**Pull request by acekyd**
## What kind of change does this PR introduce?
New icon for Astro and Vite templates.

## What is the new behavior?
Now adds icon to lists for templates

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

1. Step A
2. Step B
3. Step C

## Checklist

- [ ] Documentation
- [x] Testing 
- [x] Ready to be merged
      
- [ ] Added myself to contributors table

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/7018/commits/9ef45f98635a4c61a5616e777190b75e91e0aeeb is at https://pr7018.build.csb.dev/s/new.

**Review by ioana-chiorean — COMMENTED** [review]
@acekyd can you just ensure the alphabetical order for the bottom last 3 ones too?Solid, Sanity and Vite?

**Comment by acekyd** [comment]
Updated @ioana-chiorean

**Review by ioana-chiorean — APPROVED** [review]
thanks for including sorting - looks good!

**Pull request merged**
