### PR TITLE
docs: Update default Node version in container sandbox

### PR DESCRIPTION
**Pull request by B2D1**
## What kind of change does this PR introduce?

Fix FAQ Docs: Update default Node version in container sandbox

## What is the current behavior?

Container sandboxes run Node v10.20.1 (LTS) by default.

## What is the new behavior?

Container sandboxes run Node v14.18.1 (LTS) by default.

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

1. yarn test
2. yarn lint

## Checklist

- [x] Documentation
- [x] Testing 
- [x] Ready to be merged
      
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/6750/commits/97d595ba45f3c4c2acfa3fb101b08582ecbc15af is at https://pr6750.build.csb.dev/s/new.

**Comment by B2D1** [comment]
@CompuIves Please review my PR.

**Comment by B2D1** [comment]
> @CompuIves Please review my PR.

hello, Is there a problem with my PR, please give me some suggestions.

**Comment by B2D1** [comment]
> Hey! Sorry for the late reply, this PR is indeed right, but there's a small caveat. Sandboxes that are created _after_ May 10 2021 will have node v14. For backwards compatibility the older sandboxes are on node v10. Could you update that in the documentation? Then it's ready for merging!

Sir, I have updated the documentation about different NodeJS versions in conatainer sandbox, wait for you code review!

**Comment by CompuIves** [comment]
Thank you!

**Pull request merged**
