### PR TITLE
Fix add template typoes

### PR DESCRIPTION
**Pull request by dangdennis**
## What kind of change does this PR introduce?

Doc update for some typoes.

## What is the current behavior?

No open issue.

## What is the new behavior?

Words, words, words.

## What steps did you take to test this?

I ran tests and lint.

## Checklist

- [N/A] Documentation
- [ N/A] Testing 
- [X ] Ready to be merged 
- [ X] Added myself to contributors table

### CODE REVIEW

**Comment by SaraVieira** [comment]
Hey!

Thank you but can you please revert everything except `contributor-docs/adding-template.md` because idk why but the yarn.lock changed and the formatting for contributors too

We can use the all contributors bot for that

**Comment by dangdennis** [comment]
Thanks Sara! No wonder it failed integration. Will revert.

I only did `yarn`, made my markdown changes, and then run the add-contributor script.

**Comment by MichaelDeBoey** [comment]
The contributors-table formatting will be fixed in #2686 🙂

**Comment by SaraVieira** [comment]
Yeah, this is a problem on our side :/

**Comment by dangdennis** [comment]
I’ll pull and revert the right commits.

Would it have been better if I had made the change + PR directly on GitHub? They’re typoes, so unsure if you care about them going through the same process.

**Comment by SaraVieira** [comment]
Naa, thats fine :)

**Pull request closed without merging**
