### PR TITLE
GitHub flow ui improvements

### PR DESCRIPTION
**Pull request by christianalfoni**
So we could do a lot of stuff here, but it would not come from user requests, so I have scoped it to the following changes:

- We have changed the wording of "Export to Github", you can also get to the import modal from the sidebar now.

Screenshot 2020-08-06 at 13 20 45

- The import modal is now updated:

Screenshot 2020-08-06 at 13 21 26

- And now you have to explicitly make changes to commit and you get help with any missing info:

Screenshot 2020-08-06 at 13 22 01

Screenshot 2020-08-06 at 13 22 15

Screenshot 2020-08-06 at 13 22 23

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/4652/commits/50173fc4146dff8cc19439a6cb84c6affb9cdecd failed.

**Comment by CompuIves** [comment]
Really great improvements! One question:

> The import modal is now updated

Shouldn't the top input be gray like the other inputs? 🤔

**Comment by christianalfoni** [comment]
> Really great improvements! One question:
> 
> > The import modal is now updated
> 
> Shouldn't the top input be gray like the other inputs? 🤔

Oh my god @CompuIves , micro managing, the DESIGNER said 👍  SHIP IT! 😂

**Comment by CompuIves** [comment]
Hahahahha, I even updated the comment now 😂 😂

**Pull request merged**
