### PR TITLE
🔨 Cleanup components package

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
- Cleanup dependencies
- Update dependencies to latest version
- Remove double exported components
- Cleanup Storybook config
- Cleanup package.json
- Cleanup ignore files

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/4068/commits/421a69bafe817527185d5b4d645de494f700c3c9 failed.

**Comment by MichaelDeBoey** [comment]
@SaraVieira I only removed the unused packages and updated all other packages to their latest minor version, so this shouldn't be a problem

**Comment by SaraVieira** [comment]
Michael we shouldn't update stuff just like that, pls revert the package.json, updates to used things should be super well tested before

**Comment by MichaelDeBoey** [comment]
@SaraVieira I've reverted the deletion and update of dependencies

**Comment by SaraVieira** [comment]
Hey!

I am so sorry but at this point I can't really understand what is happening and why it's failing, I am gonna close, feel free to start it over cause this one just became super old :/

**Pull request closed without merging**
