### PR TITLE
Refactor Curator to functional components with hooks

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
**What kind of change does this PR introduce?**
Update Curator to functional components with Hooks

**What is the current behavior?**
Class components

**What is the new behavior?**
Functional components with Hooks

**Checklist**:
- [ ] Documentation N/A
- [x] Tests
- [x] Ready to be merged 
- [ ] Added myself to contributors table  N/A

### CODE REVIEW

**Comment by SaraVieira** [comment]
Hey

I know you can't see this page but if something has an observer it can't have hooks because Observer is a class :(

We have a PR to refactor to use `mobx-react-lite` and that one supports hooks

**Comment by MichaelDeBoey** [comment]
Will take care of it when the PR is merged then 🙂

**Comment by MichaelDeBoey** [comment]
@SaraVieira I extracted @Saeris' changes to make this possible in  #1956 so this one can be rebased and possibly merged 🙂

**Comment by SaraVieira** [comment]
test

**Comment by SaraVieira** [comment]
nop, can't reopen :(

**Pull request closed without merging**
