### PR TITLE
Cleanup Server screen

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Things I did:
- Change `deleteEnvironmentVariable`'s signature to accept a `string` instead of `{ name: string }`, because it only has 1 argument
- Change `onBrowserFromPortOpened`'s signature to accept a `ServerPort` instead of `{ port: ServerPort }`, because it only has 1 argument
- Make `Control`, `EnvVars`, `Ports`, `Server`, `Status`, `Tasks` & `VarForm` a `FunctionComponent`
- Type `VarForm`'s props
- Type `VarForm`'s `onCancel` & `onSubmit` functions
- Type the icons
- Simplify `getContainerStatusInfo` & `getManagerStatusInfo` a bit in `Status`
- Simplify `getIcon` a bit in `Tasks`

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/4025/commits/6f2cd9a398ad6983d2f7d22cd0b109733bdc17ce is at https://pr4025.build.csb.dev/s/new.

**Comment by MichaelDeBoey** [comment]
@SaraVieira I've rebased onto `upstream/master`, so this could be merged now 🙂

**Comment by SaraVieira** [comment]
Restert buttons are not working, gonna pull and see whats up

**Comment by MichaelDeBoey** [comment]
@SaraVieira If needed, I can look at it tomorrow 🙂

**Comment by MichaelDeBoey** [comment]
@SaraVieira I've rebased onto `upstream/master`, so this could be merged now 🙂

**Comment by SaraVieira** [comment]
Thank you!

**Pull request merged**
