### PR TITLE
Simplify prettier usage

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
**What kind of change does this PR introduce?**
Formatting change

**What is the current behavior?**
- Use `lint-staged` to run `prettier`
- Each package has it's own config

**What is the new behavior?**
- Use `pretty-quick` to run `prettier`
- Update `eslint-config-prettier`  & `husky` to latest version
- Update `prettier` to latest version and make it an exact dependency, as [recommended](https://prettier.io/docs/en/install.html) by @prettier itself
  > We recommend pinning an exact version of prettier in your `package.json` as we introduce stylistic changes in patch releases.
- Run `prettier` on all files. It will figure out which parser needs to be used
  > Prettier automatically infers the parser from the input file path
- Run `prettier` over the whole codebase (run `npx prettier '**/*'` in project root)

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Ready to be merged 
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by SaraVieira** [comment]
Hey!

Can you let me know why the change from lint staged to pretty quick?

**Comment by MichaelDeBoey** [comment]
@SaraVieira `pretty-quick` is build by @azz (one of the maintainers of @prettier) and has less boilerplate

It's also the recommended way according to https://prettier.io:
Schermafbeelding 2019-05-13 om 18 06 10

My main objective was to update `prettier` to the latest version and make it easier to change config, ...

**Comment by CompuIves** [comment]
Great PR! Thanks for cleaning this up and making it prettier (;)).

**Comment by MichaelDeBoey** [comment]
With pleasure! 🙂
Makes it easier to work with too 😉

**Pull request merged**
