### PR TITLE
Send in-app feedback to Front also

### PR DESCRIPTION
**Pull request by garethx**
## What kind of change does this PR introduce?
In-app feedback currently gets sent to Airtable. This sends it along to Front too.

## Checklist
- [ ] Testing - waiting on PR URL
- [ ] Ready to be merged

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/4157/commits/0c588e5997da039865de578c42395918d617bf96 failed.

**Comment by garethx** [comment]
@SaraVieira Looks like this is a bit beyond me, but hopefully you can see what I was going for? :)

**Comment by CompuIves** [comment]
I love that you used CodeSandbox for this again! Implementation looks good, I would only remove the requirement of `request` and use `fetch`.

**Comment by SaraVieira** [comment]
@CompuIves I talked to Gareth and I will do that and merge before I leave today :)

**Pull request merged**
