### PR TITLE
WIP: global search

### PR DESCRIPTION
**Pull request by loweisz**
Figma file: https://www.figma.com/file/xjB6dL48lshfiIa5jIfWwe/Global-Search?node-id=1%3A2

Things to be done:

- [x]  Global Search
- [x]  Make typing faster
- [x]  Toggle ability to search case sensitive
- [ ]  Allow Regex
- [ ]  Add files to include
- [ ]  Profit

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/4787/commits/881a18e96736dbaae94ee3383b8959035597d4ac is at https://pr4787.build.csb.dev/s/new.

**Comment by philip-sultanescu** [comment]
When this feature is online, I will migrate from StackBlitz to CodeSandbox. Everything else is already better.

**Comment by SaraVieira** [comment]
👋 

Will merge this into a branch in codesandbox so I can merge with master and keep working on it and finally have it!

Thank you so much @loweisz

**Comment by loweisz** [comment]
@SaraVieira Go for it 👍 
Was really awesome to at least contribute a little to it 🎉

**Pull request merged**
