### PR TITLE
🔨 Cleanup Avatar component

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
This PR adds `@codesandbox/common` as a dependency of `@codesandbox/components`, just because I need the `User` type. (see c11f8596)
I can imagine we will have some other components that will need other types too.

So what I'm suggesting is to extract all types from `@codesandbox/common/lib/types` into a separate `@codesandbox/types` package (see #4862).
Thoughts @SaraVieira @siddharthkp @CompuIves? 🤔

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/4070/commits/e2ee220f1487cbc5292832e002229b5e1617ed3a is at https://pr4070.build.csb.dev/s/new.

**Comment by siddharthkp** [comment]
> This PR adds @codesandbox/common as a dependency of @codesandbox/components, just because I need the User type. 

need to confirm with @SaraVieira on this one, from what I remember, this led to a circular dependency

**Comment by MichaelDeBoey** [comment]
@siddharthkp It does, so that’s why I’m suggesting the extraction of types into a new `@codesandbox/types` package.

**Comment by SaraVieira** [comment]
Has a bunch of conclicts if you pull from master

We also can't do the circular dependency :(

**Comment by MichaelDeBoey** [comment]
I'll rebase 🙂

**Pull request closed without merging**
