### PR TITLE
Adds Quasar Framework template

### PR DESCRIPTION
**Pull request by smolinari**
This PR adds a Quasar Framework SPA template to Codesandbox.

I hope I got it all right, as testing containers doesn't seem possible locally. 

I didn't add myself as a contributor, as I don't feel this is really contributing. It's more like Codesandbox contributing to Quasar, once the template is up and running. 😄 

[The importer PR is also done.](https://github.com/codesandbox/codesandbox-importers/pull/40)

Scott

### CODE REVIEW

**Comment by SaraVieira** [comment]
Hey!


So far I can see two small issues here

- I can't acess the template at first because it's not in master. Do you mind setting the main code in master?

- Also is there a way to turn off errors for eslint? Because we use our own eslint config :(

**Comment by SaraVieira** [comment]
Example sandbox: https://codesandbox.io/s/0o794klrwn

**Comment by smolinari** [comment]
Hey Sara!

>     * I can't acess the template at first because it's not in master. Do you mind setting the main code in master?

I'm not sure what you mean. It's in master. 

image

>     * Also is there a way to turn off errors for eslint? Because we use our own eslint config :(

So, the templates have to follow Codesandbox linting rules? I'm not sure what you mean here either. 

Sorry... :disappointed: 

Scott

**Comment by smolinari** [comment]
@SaraVieira - Can we continue to work on this? Pretty please? 😁 

Scott

**Comment by smolinari** [comment]
@SaraVieira @compulves 

I've added a `.prettierrc` to fix the prettier settings. I seems to be the solution for the prettier conflict in the VS Code standard settings. 

Scott

**Comment by smolinari** [comment]
And Sara - Sorry. I got my repos mixed up. We'll be merging the template to master here shortly. I'll ping you again.

**Comment by smolinari** [comment]
Ok. Done. Template is in the master branch. I hope the two issues to move forward are resolved.

Scott

**Comment by SaraVieira** [comment]
Im so sorry I commented and then left you alone :(

I just took another look and it all looks to be working great!

Please ignore the PR I made for your repo, I didn't see the importer PR

Im just waiting for everything on CI to pass :)


Thank you so much

**Comment by SaraVieira** [comment]
@all-contributors bot please add @smolinari for code

**Comment by SaraVieira** [comment]
You should, of course, be in the contributor's list :)

**Comment by smolinari** [comment]
@SaraVieira - Thanks for adding me as a contributor. I'm honored. 

How long approximately will it take, until the template is available on the live site? It's like sitting on hot stones waiting. 😁 

Scott

**Comment by SaraVieira** [comment]
Hey!

Bad news on that side as there was a lot of merges and me and ives have conferences the rest of the week so only next week :(

**Comment by smolinari** [comment]
Not bad news. Good news! 😃 Now I know when to expect the change. Thanks Sara! Have fun at the conferences!

Scott

**Comment by smolinari** [comment]
@SaraVieira - Hi Sara. A friendly reminder. 😄 

Scott

**Comment by smolinari** [comment]
Nevermind! I see the template is now available! 

Thanks Codesandbox team and Sara! 😁 

Scott

**Pull request merged**
