### PR TITLE
🔨 Refactor, 🧠 Overmind Hacktober | DeleteProfileSandboxModal to use useOvermind

### PR DESCRIPTION
**Pull request by stevetangue**
<h2>What kind of change does this PR introduce?</h2>

Refactor `/src/app/pages/common/Modals/DeleteProfileSandboxModal/index.js`

@Saeris @christianalfoni

<h2>What is the current behavior?</h2>

| [#2621](https://github.com/codesandbox/codesandbox-client/issues/2621) |

<h2>What steps did you take to test this? This is required before we can merge.</h2>
Tested via http://pr2744.build.csb.dev/s/new
<br /><br />
1. Sign in via token > My Profile > Sandboxes > Delete Sandbox

### CODE REVIEW

**Comment by CompuIves** [comment]
Heyo! Did you verify that this works? You can do that by going to your profile and trying to delete a profile. You can test it with this url: http://pr2744.build.csb.dev/s/new

**Comment by stevetangue** [comment]
Hey @Compulves, i am unable to sign-in, do you know what i am missing? 🙇 

image

**Comment by stevetangue** [comment]
Hey @CompuIves @christianalfoni 
reading from this PR 
https://github.com/codesandbox/codesandbox-client/pull/2781#issuecomment-542169328

- is that what it is ? am my missing some kind of token to be able to sign in and test out the delete sandbox from my profile ?

**Comment by stevetangue** [comment]
Yes that work - apology - i missed fully reading the contribute info

**Pull request merged**
