### PR TITLE
fix: add theme provider to get all the custom vakues

### PR DESCRIPTION
**Pull request by jyash97**
## What kind of change does this PR introduce?
Maybe a fix for #3934 

## What is the current behavior?
Seeing a different error than the one reported in Crash. I suspect this is because the component are accessing values from the theme which isn't present and we are having those values in Custom ThemeProvider present in components.

Error: 
https://www.loom.com/share/ac0a8f907a3d469d9209127aaf1b3995

## What is the new behavior?
Fix:
https://www.loom.com/share/04b8adf59daf4d1196d07353c5ad790e

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

1. Tested the same URL reported in crash and seems to work properly.

## Checklist

- [x] Testing 
- [x] Ready to be merged

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3935/commits/0bcde06eedf0b77d67244efcf9b92bb2951efafe is at https://pr3935.build.csb.dev/s/new.

**Comment by SaraVieira** [comment]
Hey!

This is great but you would need to pass the theme to the provider :/

I wanna apologize for closing and creating a new one but this is kind of urgent

Thank you so much for detecting the error!

**Comment by jyash97** [comment]
Hey @SaraVieira  

Thanks for the quick review, I thought it may take a default theme as Codesandbox Black. 

> I wanna apologize for closing and creating a new one but this is kind of urgent

No worries I can understand. 😄 

Glad that the PR helped in finding the root cause.

**Comment by SaraVieira** [comment]
Honestly, it should take the default theme, I might add that so we can clean the code a tad since in these pages we just pass the default one

If you wanna take that one this is created here: https://github.com/codesandbox/codesandbox-client/blob/master/packages/components/src/components/ThemeProvider/index.tsx

Otherwise, I can do it next week :)

Thank you again

**Comment by jyash97** [comment]
@SaraVieira  This was a quick change, have set up a PR here: #3939

**Comment by SaraVieira** [comment]
Wow! That was super fast! Thank you!

I accepted and now let's wait for Sid to take a look :)

**Comment by jyash97** [comment]
> Wow! That was super fast! Thank you!

Haha, thanks. Getting more time to contribute because of Quarantine 🔒

**Pull request closed without merging**
