### PR TITLE
feat(dashboard/recent): update recent page

### PR DESCRIPTION
**Pull request by olarclara**
Implements the empty state on the dashboard recent:

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/7240/commits/2ac295452fa6a497a94c6623406f17e50c70baf6 is at https://pr7240.build.csb.dev/s/new.

**Review by tristandubbeld — COMMENTED** [review]
The grid or list view button is present on the page, but does nothing in the empty state. Should we still show it?

**Comment by olarclara** [comment]
@tristandubbeld there's a task to remove the view toggle button from the pages.

**Review by tristandubbeld — APPROVED** [review]
Nice @olarclara!

**Pull request merged**
