### PR TITLE
Add Razzle template

### PR DESCRIPTION
**Pull request by jaredpalmer**
**What kind of change does this PR introduce?**

New template

**What is the current behavior?**

**What is the new behavior?**

Add Razzle basic SSR template

**Checklist**:

- [ ] Documentation N/A
- [ ] Tests N/A
- [x] Ready to be merged 
- [ ] Added myself to contributors table

### CODE REVIEW

**Comment by SaraVieira** [comment]
Don't want that fancy badge of open source contributor of CodeSandbox?

**Comment by jaredpalmer** [comment]
bitmoji

**Comment by jaredpalmer** [comment]
Still installing node_modules as I write this. Is the entire matrix a dependency? lol. 

Also, @SaraVieira I didn't know what ya'll wanted for main, popular, etc. I will leave that to you.

**Comment by jaredpalmer** [comment]
@SaraVieira this one does not seem related to this PR

**Comment by SaraVieira** [comment]
Hey @jaredpalmer 

Sorry, I was in a conference.

About the error it is not related, no worries 🎉

I do get an error when running because the port is not defined and it's not falling back to 3000

I made a PR here: https://github.com/jaredpalmer/razzle/pull/1018

Is this okay for you to merge? With that works 💯

https://codesandbox.io/s/github/SaraVieira/razzle/tree/csb-1558253759116/examples/basic

**Comment by SaraVieira** [comment]
> Still installing node_modules as I write this. Is the entire matrix a dependency? lol.

It's moment man, we need to install moment, that takes 3 days


Also thank you for setting netlifly to false, last time I forgot ahah

**Comment by lbogdan** [comment]
It kinda works, still there's this in `index.html`:

image

image

**Comment by SaraVieira** [comment]
@jaredpalmer is now at react europe so I left a note to come back to this nexct week 👍

**Comment by jaredpalmer** [comment]
Coming back for air. Razzle needs 2 ports.

**Comment by CompuIves** [comment]
Heyo! Is there anything else needed here? I'd gladly merge this in so we can announce it Monday 😄

**Comment by jaredpalmer** [comment]
@CompuIves Razzle needs 2 ports to run in development mode. Is that being accounted for?

**Comment by Saeris** [comment]
Hey @jaredpalmer! Containers should accept connections on multiple ports. The only thing about them right now is that we use auto-detection for what port to serve HTTP requests to `/` over, which requires you to explicitly set the default port in `sandbox.config.json` like so:

```json
{
  "container": {
    "port": 3000
  }
}
```

The asset loading error is strange though. I'm assuming Razzle generates a `static` directory at build time?

One other thing to note is that we're overhauling templates right now. I've got all the default Razzle starter files + the extra sandbox configuration added to our `codesandbox-templates` repository. So that steps on some of the work in this PR and I apologize for that. Here's that repo and a link to the sandbox:

https://github.com/codesandbox/codesandbox-templates/tree/master/packages/container/razzle-template

https://codesandbox.io/s/github/codesandbox/codesandbox-templates/tree/master/packages/container/razzle-template

One nice thing is that you can make changes to this template and submit a PR directly from the CodeSandbox GitHub integration and it will be committed back to the template repository this way. So if you'd like to play around with it to try and debug it, go ahead and give that workflow a shot!

**Comment by CompuIves** [comment]
We just got support for two ports. Will this make it possible to run everything well? :D

**Comment by jaredpalmer** [comment]
Yep

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/1915/commits/256f532eede628b1da49d76122554bcde9e95e41 failed.

**Comment by SaraVieira** [comment]
Hey!

So the way we add templates as completly changed and also the logos are gotten from diffrent places, we do already have the razzle logo if needed

So it doesn't really make sense anymore this PR as the templates are now created in the UI so you can just send one of us the link to the sandbox and we mark them as official

The issue is that right now the view is not updating because of getting assets from localhost, it should be gotten from whatever url the person is in :/

image

If you fix this and find a way for things to re render after a change please send me the sandbox in a DM and we will add it to the official list :)

**Pull request closed without merging**
