### PR TITLE
Cleanup package.json files with the help of sort-package-json

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
## What kind of change does this PR introduce?
Cleanup `package.json` files with the help of [`sort-package-json`](https://www.npmjs.com/package/sort-package-json).

## What is the current behavior?
Unsorted `package.json` files.

## What is the new behavior?
Sorted `package.json` files.

## What steps did you take to test this?
N/A

## Checklist
- [ ] Documentation N/A
- [ ] Testing  N/A
- [x] Ready to be merged 
- [ ] Added myself to contributors table N/A

### CODE REVIEW

**Comment by lbogdan** [comment]
Is this needed in any way? I'm usually against polluting the history with cosmetic changes, which seems to be the case with this PR?

**Comment by MichaelDeBoey** [comment]
It's not a needed change.
I just wanted to make all the `package.json`s consistent and sort all scripts.

**Comment by SaraVieira** [comment]
Thanks man!

Nice cleanup!

**Comment by lbogdan** [comment]
But why?... 🙁

**Comment by MichaelDeBoey** [comment]
@SaraVieira Always a pleasure to help out. Even with small things 🙂

@lbogdan Like I said: I just did it for consistency

**Pull request merged**
