### PR TITLE
Feat supprot Rax

### PR DESCRIPTION
**Pull request by fyangstudio**
Support Rax: https://rax.js.org/
## What kind of change does this PR introduce?
Rax starter template feature #3345 

## What is the current behavior?
No Rax bei'shang 😞

## What is the new behavior?
Get started with Rax in CodeSandbox

## Checklist

- [x] Documentation
- [x] Testing 
- [x] [Icon](https://github.com/codesandbox/codesandbox-templates/pull/30)
- [x] [Template](https://github.com/raxjs/rax-codesandbox-template)
- [x] [Importer](https://github.com/codesandbox/codesandbox-importers/pull/60)
- [x] Ready to be merged
      
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3346/commits/c063d7a42869a3bd448076e8159a96c97ab18862 failed.

**Comment by fyangstudio** [comment]
Can i use this url for test?
https://pr3346.build.csb.dev/s/github/raxjs/rax-codesandbox-template/tree/master/

Why this `github/raxjs/rax-codesandbox-template` shortid can't be matched?

**Comment by yacheng** [comment]
We can build a rax project at this address, but the default setting in sandbox.config.json, rax, will fail. The default setting, node, can only be changed to rax manually
https://pr3346.build.csb.dev/s/github/raxjs/rax-codesandbox-template/tree/master/

How can I set the rax template type by default?

**Comment by fyangstudio** [comment]
> We can build a rax project at this address, but the default setting in sandbox.config.json, rax, will fail. The default setting, node, can only be changed to rax manually
> https://pr3346.build.csb.dev/s/github/raxjs/rax-codesandbox-template/tree/master/
> 
> How can I set the rax template type by default?
> 
> 

@lbogdan @coderberry @robbyoconnor  
Sorry to bother you, please see the template problem.

**Comment by fyangstudio** [comment]
We are ready to merge

**Pull request closed without merging**
