### PR TITLE
✨ New Profiles

### PR DESCRIPTION
**Pull request by Saeris**
To be updated with TODO list!

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3115/commits/b0906b3d567409663577b6fd5b08e772d6bc63f3 failed.

**Comment by DannyRuchtie** [comment]
I added my remarks in a notion document 
https://www.notion.so/Profile-Review-6092bb8fe58e418fafd2891f16655177

**Comment by DannyRuchtie** [comment]
@CompuIves What are we going to do with this once? 
Close for now?  I no longer want to see the PR messages in slack :P

**Comment by SaraVieira** [comment]
I am so sorry for closing this :((((((

**Pull request closed without merging**
