### PR TITLE
🔨 Switch StorageManagementModal to use useOvermind

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Follow-up of #2808, #2828 & #3081

Things I did extra:
- Change `addedFileToSandbox`'s signature to get its argument types directly from `UploadFile` instead of hardcoding them
- Change `deletedUploadedFile`'s signature to accept a `string` instead of `{ id: string }`, because it only has 1 argument
- Refactor `Button` out of `AddFileToSandboxButton` & `DeleteFileButton`
- Move `overmind` subscriptions as close as possible to the components itself instead of passing it through
- Put all styles into the `elements.ts` file

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3438/commits/c7c1ca8e8bad6850b19d02c2567c0ea96ded6c7a is at https://pr3438.build.csb.dev/s/new.

**Comment by SaraVieira** [comment]
@MichaelDeBoey Can you please fix the conflicts?

**Comment by MichaelDeBoey** [comment]
@SaraVieira Rebased on `upstream/master` 🙂

**Comment by SaraVieira** [comment]
There is an issue with the modal :(

Screenshot 2020-02-13 at 15 30 44

**Comment by MichaelDeBoey** [comment]
With pleasure! 🙂

**Pull request merged**
