### PR TITLE
re-enable experimental esmodule resolution

### PR DESCRIPTION
**Pull request by DeMoorJasper**
## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

1. Step A
2. Step B
3. Step C

## Checklist

- [ ] Documentation
- [ ] Testing 
- [ ] Ready to be merged
      
- [ ] Added myself to contributors table

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/6330/commits/1e96de35c859b32e5feb227c856a73236dc98e6b is at https://pr6330.build.csb.dev/s/new.

**Comment by darrinm** [comment]
This is great to see @DeMoorJasper, thanks! How can I create a new project using the esm-react preset? Can I configure sandpack to use it as well?

**Comment by DeMoorJasper** [comment]
@darrinm yes, you can use the customSetup for this and set `environment` to `esm-react`, here's a sandbox with an example: https://codesandbox.io/s/sandpack-project-forked-o7tvk?file=/App.js

It's apparently missing in the typings though

**Comment by darrinm** [comment]
> @darrinm yes, you can use the customSetup for this and set `environment` to `esm-react`, here's a sandbox with an example: https://codesandbox.io/s/sandpack-project-forked-o7tvk?file=/App.js

That did the trick. Thanks!

**Comment by darrinm** [comment]
There's probably a better place to ask this but, why is ESM support coupled with React? Seems like it should be independent.

**Comment by DeMoorJasper** [comment]
> There's probably a better place to ask this but, why is ESM support coupled with React? Seems like it should be independent.

This is because we launched this preview together with Framer's esmodule components which are React and we wanted to test it on a small number of sandboxes first. It's totally possible to make it work for every sandbox just have to remove the flag

**Comment by darrinm** [comment]
> > There's probably a better place to ask this but, why is ESM support coupled with React? Seems like it should be independent.
> 
> This is because we launched this preview together with Framer's esmodule components which are React and we wanted to test it on a small number of sandboxes first. It's totally possible to make it work for every sandbox just have to remove the flag

Got it, thanks.

**Pull request merged**
