### PR TITLE
Add lit html support

### LINKED ISSUE #3562: Support lit-html highlight
# 🌈 Feature

[lit-html](https://github.com/Polymer/lit-html) template example:
```js
html`
  <div></div>
`
```

More and more applications use es string templates to write HTML, hope to support html highlighting

### PR DESCRIPTION
**Pull request by SaraVieira**
Adds https://github.com/runem/lit-analyzer/tree/master/packages/vscode-lit-plugin and closes #3562

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3564/commits/4652f598774658d866fdd6c70d50adbbabfaacd6 is at https://pr3564.build.csb.dev/s/new.

**Comment by CompuIves** [comment]
Nice! Did it work after testing?

**Comment by SaraVieira** [comment]
Yes 🎉

**Comment by jonsherrard** [comment]
Is this plugin better perhaps? Slightly smaller?https://github.com/mjbvz/vscode-lit-html

3.4mb on my disk

**Pull request merged**
