### PR TITLE
fix time information

### PR DESCRIPTION
**Pull request by yeion7**
## What kind of change does this PR introduce?

Fix

## What is the current behavior?

The sandbox dates (`insertedAt`, `updatedAt`, `deletedAt`) is received with format `2019-09-19 11:29:27.280934` this format now allow parsed with the right timezone

#2465 

## What is the new behavior?

There are two changes

1. Add `date-fns` to `app` scope
2. use [date-fns-tz](https://date-fns.org/v2.2.1/docs/Time-Zones) to parse the dates as utc dates and then `formatDistanceToNow` can parsed with the user time zone

*Before:*
Screen Shot 2019-09-19 at 20 33 56

*After*
Screen Shot 2019-09-19 at 20 33 26

## Checklist

- [ ] Documentation
- [ ] Testing 
- [x] Ready to be merged 
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by yeion7** [comment]
@CompuIves done 😅

**Comment by janmyler** [comment]
@yeion7 thanks for the fix!

**Comment by christianalfoni** [comment]
@CompuIves Seems to be a configuration error on the `typecheck` error. Should not do type checking on node_modules?

**Comment by christianalfoni** [comment]
@yeion7 If you have time maybe you could try bringing in latest master? This might have been fixed :)

**Comment by yeion7** [comment]
@christianalfoni I rebased the branch, but I think the error persists:/

**Comment by SaraVieira** [comment]
Hey!

I think the issue is that date-fns is already installed in the workspace, can you try to remove it from app and run `yarn typecheck` again?

**Comment by SaraVieira** [comment]
@yeion7 ping 🙃

**Comment by yeion7** [comment]
@SaraVieira i'll resolve this issue in https://github.com/codesandbox/codesandbox-client/pull/2590

I rebased this branch and brought many changes jaja 😅

**Comment by SaraVieira** [comment]
Omg we are really not making it easy for you, I'm sorry 😂

**Pull request closed without merging**
