### PR TITLE
Fix honoured gitignore

### PR DESCRIPTION
**Pull request by yeion7**
## What kind of change does this PR introduce?

fix

## What is the current behavior?

#323 

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

1. Create a sandbox or fork https://pr3003.build.csb.dev/s/falling-sun-uth2m
2. Add `.gitignore`
3. Create a repositorio from sandbox

## Checklist

- [ ] Documentation
- [ ] Testing 
- [x] Ready to be merged
      
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3003/commits/6c944bfceb428b9d0612c2c41f16f4a8624c2d55 is at https://pr3003.build.csb.dev/s/new.

**Comment by CompuIves** [comment]
Man you're really good, thanks a lot for building this!

**Comment by wannikid** [comment]
This fix only works for me when I export files for the first time to Github. Any following commit to the same repository however still uploads the excluded files. As an example, my .env file does not get exported to Github at first, but when I add a .env file to my sandbox later on, it is commited to Github despite being mentioned the .gitignore file. Is that the intended behaviour?

**Comment by tjxnor** [comment]
Ditto @wannikid. I had a project already connected to github. Added the .gitignore and .env files later on. On making a new commit, the entries in .gitignore are not honoured.

**Comment by srguiwiz2** [comment]
As git works, once committed, merely making a `.gitignore` entry won't automatically remove it.  To achieve that, one has to do a `git rm --cached path/filename.ext` and a commit, and if necessary a push.

See the answer at

https://stackoverflow.com/questions/6030530/git-ignore-not-working-in-a-directory/6030686#6030686

and a mention at

https://git-scm.com/docs/gitignore

Therefore I will now make sure to write into `.gitignore` early, and commit it, before adding files that should not be committed.

**Comment by srguiwiz2** [comment]
While I got it to work once, `.gitignore` in codesandbox is overall not functioning for me.

As hints for reproducing the problems:  Overall we are using private setting, in case that matters for reproducibility.  We have made a very simple static template on a private repository we are starting from.

There is proof It is a valid `.gitignore` we use, because on a command line on a computer that has a clone of that same repository, `.gitignore` works as expected.

**Pull request merged**
