### PR TITLE
Add freezing/unfreezing in the dashboard

### PR DESCRIPTION
**Pull request by CompuIves**
An addition is the refactoring of our logic when it comes to updating/removing dashboard sandboxes in state. We had duplicated it quite a bit, so I simplified the logic and deduplicated it in a separate `internalActions` file.

Additional changes:

* Deduplicated changing/removing sandbox from state
* Removed need to provide `page` to sandbox change (we now always check REPOS and change it if need be)
* Removed need to provide `oldTitle` to `renameSandbox` (is now inferred in action)
* Reuse our `sandboxFragmentDashboard` in `repoFragmentDashboard` and `templateFragmentDashboard`. This simplifies typing and both had 100% overlap with `sandboxFragmentDashboard`, also when something needs to be added to `sandboxFragmentDashboard` we probably need it in `repoFragmentDashboard` and `templateFragmentDashboard`.
* Slightly changed order of SandboxMenu and MultiMenu items (shown in screenshots below)
* Added margin to eye (request from @DannyRuchtie)
* Added frozen status to sandboxes that are frozen, with a tooltip
* Added possibility using context menu to freeze/unfreeze sandboxes
* Allow everyone with write permission and pro to change privacy of the sandbox in a workspace (not only the author)

Tested:

* Verify changing state works by renaming and changing privacy of a sandbox
* Verify rollback of changing state works by renaming sandbox while it fails
* Verify deletion from state works by deleting the sandbox
* Verify it changes state everywhere, by renaming sandbox in "Recents" and see if the change propagated in the folder
* Verify whether changing frozen works by (un)freezing sandboxes both in multi and single context menu
* Verify whether rollback of changing frozen works by manually throwing error

Screenshot 2020-09-02 at 16 56 55
Screenshot 2020-09-02 at 16 56 51

image

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/4803/commits/939f4c407d1ac4ff9bf50e9d71b733f59b848abd failed.

**Comment by CompuIves** [comment]
I don't know why this happens...
image

image

**Review by SaraVieira — APPROVED** [review]

**Comment by DannyRuchtie** [comment]
@CompuIves the icon indeed is not centred vertically (its placed to high)
I wanted to debug but I can't seem to load my sandboxes in this PR. Any ideas why?
  
screen_shot_2020-08-28_at_17 02 18

**Comment by CompuIves** [comment]
Server deploy has been done, it should now be testable1

**Review by DannyRuchtie — APPROVED** [review]
Looking Sharp!

**Pull request merged**
