### PR TITLE
update favicon

### PR DESCRIPTION
**Pull request by SaraVieira**
This updates the favicon to the new white logo
Screenshot 2019-12-13 at 15 01 59

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3200/commits/2b56a97df45e8fa5b95eefc00b427b0467a2b45b is at https://pr3200.build.csb.dev/s/new.

**Comment by CompuIves** [comment]
I think we should use the one from codesandbox ci, that one also has the shadow.

**Comment by CompuIves** [comment]
https://ci.codesandbox.io/static/favicon.ico

**Comment by SaraVieira** [comment]
Can you ask Danny? He told me to use this one

**Comment by DannyRuchtie** [comment]
> https://ci.codesandbox.io/static/favicon.ico

@CompuIves  this is not the rounded version.
As far as I know the rounded version bas created is the new one.

I removed the "shadow" side because of the legibility of the icon

**Comment by CompuIves** [comment]
Hmm, in my opinion I think this looks actually better:
image. Maybe it's because of retina? I can clearly see the shadow when visiting ci.codesandbox.io

**Comment by SaraVieira** [comment]
All updated

**Pull request merged**
