### PR TITLE
Allow for editing the team name

### PR DESCRIPTION
**Pull request by CompuIves**
I went for a simple version since we're updating the dashboard anyway soon.

How it works: https://www.loom.com/share/e756118b536c47cc80931278e8eb3b6a

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/4082/commits/1efa2c6385d08b5fb7abdb68a2b9fb2f42fad594 is at https://pr4082.build.csb.dev/s/new.

**Comment by DannyRuchtie** [comment]
@CompuIves hmm have some bugs.
- Also no validation feedback
- Edit mode will be open if you switch to other team 
- Can't Save 

Video: https://drive.google.com/open?id=1PVXJvIeO-GpwBbIp4_gZELL9_NqFO_Wp

Screenshot 2020-05-08 at 12 43 46

**Comment by CompuIves** [comment]
Oh, yes, I needed to deploy the server still 😂 . Whoops, doing that now

**Comment by CompuIves** [comment]
Could you try again @DannyRuchtie? Sorry for the time wasted in the first session...

**Comment by DannyRuchtie** [comment]
Switching teams and not save overrides the input field of the other team overviewpage.
https://drive.google.com/open?id=1PVXJvIeO-GpwBbIp4_gZELL9_NqFO_Wp

**Comment by DannyRuchtie** [comment]
Would it be an Idea to have max length ?

Screenshot 2020-05-08 at 13 12 39

**Comment by CompuIves** [comment]
Good one! We have a validation on it when creating a team (max 64 chars), but it wasn't triggered on edit. Nice find!

**Comment by CompuIves** [comment]
The validation is back in! Max 64 characters IIRC.

**Pull request merged**
