### PR TITLE
Use ot types from DefinitelyTyped

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Copied the types over to DefinitelyTyped in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43211, https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43430, https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43638 & https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44970

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3732/commits/29652a1b7c14488ad88266cb607b024dad216d60 is at https://pr3732.build.csb.dev/s/new.

**Comment by MichaelDeBoey** [comment]
@SaraVieira Will resolve them later today 🙂

**Comment by SaraVieira** [comment]
@MichaelDeBoey let me know if you don't have time to fix the conflicts

**Comment by MichaelDeBoey** [comment]
@SaraVieira I'll look into this one later tonight 🙂

**Comment by MichaelDeBoey** [comment]
@SaraVieira I've rebased onto `upstream/master`, so this could be merged now 🙂

**Comment by MichaelDeBoey** [comment]
Always a pleasure! 🙂

**Pull request merged**
