### PR TITLE
Make mobile sign in work

### PR DESCRIPTION
**Pull request by CompuIves**
Video with the fix: https://www.loom.com/share/2568e7add36f4bffa2071d49b8787754

### CODE REVIEW

**Comment by SaraVieira** [comment]
Any idea why the generator stopped working?

**Comment by CompuIves** [comment]
Hmm, it isn't working? Oh! In my test it works, but it's relative, so it goes to localhost:8000/signin while the signin page is actually on localhost:3000/signin. In prod it should work fine though!

**Comment by SaraVieira** [comment]
I was just asking because you also changed that code

**Comment by CompuIves** [comment]
Oh, I changed it to the generator, just for the consistency and a bit of reusability.

**Comment by SaraVieira** [comment]
Oh nevermind, sorry I'm half asleep, you placed it back!!

Good work! Sorry for the leftover from the modal

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/4154/commits/ad0268e4a97c23214ed617fc0b0d22358bd1fbde is at https://pr4154.build.csb.dev/s/new.

**Pull request merged**
