### PR TITLE
Update prettier + prettify codebase

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Just like #2968

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/2989/commits/22bf86bad723ab0969be5f98164c6e23a0b4116e is at https://pr2989.build.csb.dev/s/new.

**Comment by MichaelDeBoey** [comment]
Ping @CompuIves @SaraVieira @christianalfoni

**Comment by MichaelDeBoey** [comment]
Fixed conflicts 🙂

**Comment by MichaelDeBoey** [comment]
@Saeris Fixed all conflicts + all green 🙂

**Comment by SaraVieira** [comment]
Nice! Thank you!

**Comment by MichaelDeBoey** [comment]
With pleasure! 🙂

**Pull request merged**
