### PR TITLE
Update console-feed

### LINKED ISSUE #4980: built-in console wrongly prints null for vue component ref
# 🐛 bug report

## Preflight Checklist

- [X] I have read the
      [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md)
      for this project.
- [X] I agree to follow the
      [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [X] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I have created a very small `vuejs` demo which illustrate the issue. I never in those wasted hours have thought to double-check the console using the browser's one.

## How has this issue affected you? What are you trying to accomplish?

I have been wasting my whole day trusting the built-in console of codesandbox.
apparently it's untrustworthy as it prints `null` where an Object should be printed.

All I wanted was to print the `ref` for a vue child-component in another parent vue-component.

### To Reproduce

Open the built-in console vs browser console and see:

image

 
https://codesandbox.io/s/vue-example-to-print-ref-1spu6?file=/src/App.vue

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 
| Browser          | Chrome Version 81.0.4044.122 (Official Build) (64-bit)
| Operating System | MacOS 10.15.7

### PR DESCRIPTION
**Pull request by SaraVieira**
Fixes nested proxies in our browser console

test sandbox: https://codesandbox.io/s/vue-example-to-print-ref-1spu6?file=/src/App.vue

closes #4980

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/4988/commits/22cb0f182afdaa7b59cb2491b85a5c4215ae8ba7 is at https://pr4988.build.csb.dev/s/new.

**Comment by RealPeha** [comment]
@SaraVieira I did another PR (https://github.com/samdenty/console-feed/pull/56) in console-feed which should have a very good effect on console performance. So when (and if) it is merged it would be great to update the version again.

**Comment by SaraVieira** [comment]
@RealPeha that is an awesome PR! I will definitely update it when merged, subscribed to it! :D

**Comment by lbogdan** [comment]
Tested on https://pr4988.build.csb.dev/s/1spu6 , LGTM.

**Pull request merged**
