### PR TITLE
Fix showing personal workspace in the share sheet

### PR DESCRIPTION
**Pull request by CompuIves**
Personal Workspace:
Screenshot 2020-09-10 at 21 28 21

Team:
Screenshot 2020-09-10 at 21 06 00

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/4881/commits/7b47d3e4593c15d4873174e693cec2eb731cbc61 is at https://pr4881.build.csb.dev/s/new.

**Review by SaraVieira — APPROVED** [review]

**Review by DannyRuchtie — CHANGES_REQUESTED** [review]
Not sure it's related to these changes. 
1. creating sandbox in personal 
2. move to drafts in team
3. move back to personal  (not possible)

**Comment by CompuIves** [comment]
It isn't related to this change, I only change some styling of the collaborator modal here. But could you maybe create a Loom video or something reproducing this problem and send it to me? I'd need to know how you move the sandboxes.

**Review by DannyRuchtie — APPROVED** [review]
Styling all looks good! 
FF, Chrome, Safari & iPad

**Pull request merged**
