### PR TITLE
fix: remove sidebar experiment

### PR DESCRIPTION
**Pull request by jyash97**
## What kind of change does this PR introduce?
Bug fix

## What is the current behavior?
Currently, if we toggle the sidebar experiment from preferences modal it doesn't show any update in UI. Because the feature-flag has been set to `true` for all. 

## What is the new behavior?
Remove the sidebar experiment option from the preferences modal.

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

Confirmed locally

## Checklist

- [x] Testing 
- [x] Ready to be merged
      
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by jyash97** [comment]
If we want to keep the toggle we may update the `feature-flag` variable to read from `localStorage` and keep the fallback as `true`

@siddharthkp  Thoughts ?

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3797/commits/2c1e2248a74a035f7559f94d2989a959b8d765fc failed.

**Comment by siddharthkp** [comment]
> If we want to keep the toggle we may update the feature-flag variable to read from localStorage and keep the fallback as true

Haha yeah, that was the intention initially, but then I didn't wire the flag properly to go back. At this point, I'd say the experiment was a success, we'll watch it for a few more days

Merging your PR because removing the toggle is better than a broken toggle for sure

**Comment by jyash97** [comment]
> At this point, I'd say the experiment was a success, we'll watch it for a few more days

Yeah the sidebar is looking great 🔥 

Before merging just wanted to confirm, should I remove the `NewSidebar` component as well from experiments folder ?

**Comment by siddharthkp** [comment]
I'd say just remove from the experiments for now

**Comment by jyash97** [comment]
@siddharthkp  ready to be merged 🚀  PR only contains delete changes 😄

**Comment by jyash97** [comment]
Ping @siddharthkp

**Pull request merged**
