### PR TITLE
Fix typecheck error

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Fixes CI

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3155/commits/0d236e915f878d22d7f8c8375a2d880aee7ed1df is at https://pr3155.build.csb.dev/s/new.

**Comment by SaraVieira** [comment]
New error :(

**Comment by MichaelDeBoey** [comment]
Hmmm new errors keep coming... 😓

**Comment by SaraVieira** [comment]
Hey!

It took me a while but done!

Thank you so much for trying :D

**Comment by SaraVieira** [comment]
You can pull in the other one

**Pull request closed without merging**
