### PR TITLE
🔨 Switch Navigation to use useOvermind

### PR DESCRIPTION
**Pull request by MichaelDeBoey**

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/2847/commits/d7842d018866f52785e64aa01e85cb4c4df63533 is at https://pr2847.build.csb.dev/s/new.

**Comment by MichaelDeBoey** [comment]
Ping @CompuIves @SaraVieira @christianalfoni

**Comment by christianalfoni** [comment]
Awesome work @MichaelDeBoey! 👍

**Comment by MichaelDeBoey** [comment]
With pleasure! 🙂

**Pull request merged**
