### PR TITLE
feat: add support for npm alias in subdependencies

### LINKED ISSUE #3727: subdependency NPM alias fails for CSB links
# 🐛 bug report

## Description of the problem

I have a npm alias in one of my dependencies, dependencies.

https://github.com/jamime/carbon/blob/4c471f334aca2f168dd3a0be0b6b193263d5d42a/package.json#L163

If I create a sandbox and pull in the latest version (`carbon-react`). This works fine, however, the templates created by CodeSandboxCI fail to resolve the npm alias.

**Update**

It fails when using `https://pkg.csb.dev/jamime/carbon/commit/60c9c3e8/carbon-react` as a dependency. 

This looks like a good starting point: https://github.com/codesandbox/codesandbox-client/blob/c435a7ba414ec3c676e6c7f6e2226fbb3c8c0079/packages/app/src/sandbox/eval/npm/fetch-npm-module.ts

## How has this issue affected you? What are you trying to accomplish?

Unable to use CodeSandboxCI to test our library.

### Link to sandbox: [link](https://codesandbox.io/s/laughing-lovelace-sgv2y)
https://ci.codesandbox.io/status/jamime/carbon/pr/5

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 🤷‍♂ 
| Browser          | Chrome 80.0.3987.132 (Official Build) (64-bit)
| Operating System | MacOS 10.14.6

### PR DESCRIPTION
**Pull request by jamime**
## What kind of change does this PR introduce?

Fixes #3727

## What is the current behavior?
When a dependency uses a npm alias, the package is not resolved.

## What is the new behavior?
When a dependency uses a npm alias, the package is resolved.

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

1. Create a new React sandbox
1. Edit the `package.json`
1. Add a package with an npm alias to the dependencies.
```diff
"dependencies": {
    "react": "16.12.0",
    "react-dom": "16.12.0",
    "react-scripts": "3.0.1",
+   "carbon-react": "https://pkg.csb.dev/jamime/carbon/commit/60c9c3e8/carbon-react"
  },
```

## Checklist

- [ ] Documentation N/A
- [x] Testing 
- [x] Ready to be merged
      
- [ ] Added myself to contributors table N/A

### CODE REVIEW

**Comment by jamime** [comment]
I'm not sure why this is failing, the failing sandboxes appear to load on the staging environment.

**Comment by CompuIves** [comment]
Wow, this is really impressive @jamime! I'm impressed that you found how the code works without that much documentation. This fix looks good to me, great to see that we now get `npm:` support!

**Comment by jamime** [comment]
@CompuIves thank you for the kind words.

To be clear, it does not allow users to use `npm:` alias within their codesandbox directly, but they can consume packages that do.

It's great that this was merged did you find out why some of the CI was failing? 

- ci/circleci: test-integrations 
- ci/circleci: test-visual-regressions
- ci/circleci: build-and-test/deploy-staging-approval Pending — Your job is on hold on CircleCI!

#3627 has a request for `npm` links within a codesandbox. I had some success but ultimately. I decided to submit this pull request without that support.

**Comment by CompuIves** [comment]
That makes sense. I think it'd be good to have this one in already, then I can take another look at the `npm:` alias. We do support aliases already, but we have to move it to the package install level I presume.

The tests failing were for multiple reasons. The integration tests failed due to a network issue, the regressions failed because we hit a limit. The staging one is just used for us to deploy to our staging server, but serves no purpose in this case.

**Comment by jamime** [comment]
This is the area that I was looking at to resolve #3627 
https://github.com/codesandbox/codesandbox-client/blob/2f6ba184d3c332552fd827516f0674bdecab51f1/packages/common/src/utils/dependencies.ts#L51

I was going to move the `resolveNPMAlias` function that I added to the `@codesandbox/common/lib/utils/dependencies` package.

Thanks again for your quick response. Is this deployed to production on merge?

**Pull request merged**
