### PR TITLE
chore: Remove some unused code and references to autoFork

### PR DESCRIPTION
**Pull request by tristandubbeld**
This PR used to contain changes to default forked sandboxes to be private. However, we're moving that logic to the backend instead. In this PR I've cleaned up a few things that I wanted to keep so that's what this PR is about now.

Notable changes:
- [x] Removed unused code and add comments to clarify code and todos for potential future improvements.
- [x] Removed references to `autoFork`. This property was `undefined` for all sandboxes in our dashboard. I couldn't find any other references to this property.

### CODE REVIEW

**Comment by necoline** [comment]
I ran through the following tests. 
- [ ] Sandboxes forked from the create new modal on `/dashboard/*`
@tristandubbeld do you have a suggestion for how to test this?
- [x] Sandboxes forked from the context menu
  - [x] on the Recent page (`/dashboard/recent`)
  - [ ] on the Discover page (`/dashboard/discover`)
     Also, not sure how to target this
  - [x] on the My drafts page (`/dashboard/drafts`)
  - [x] on the Templates page (`/dashboard/templates`)
  - [x on the All sandboxes and nested folder pages (`dashboard/sandboxes`)
  - [ ] on a users page (e.g. `/u/tristandubbeld`)
- [x] The branches forked on the Synced page (`/dashboard/synced-sandboxes`). Try `test_repo` from `sannek` because that one still exists, some others result in errors.


When the sandbox is public, the fork is also public
When the sandbox is private, the fork is private

The intended behavior is that 
if the workspace is Pro, all forks are private

**Comment by tristandubbeld** [comment]
> "Sandboxes forked from the create new modal on `/dashboard/*`" @tristandubbeld do you have a suggestion for how to test this?

At the core the templates in the create new modal are sandboxes too, so they behave the same-ish! This can be tested by clicking the (non-cloud) templates in the create new modal.

> "Sandboxes forked from the context menu on the Discover page"
> Also, not sure how to target this

On the `/dashboard/discover` page some sandboxes should be visible. Right clicking these shows the option to fork - these should also be private when pro.

**Comment by tristandubbeld** [comment]
Deployed the branch to stream to confirm this also works when forking cloud sandboxes:


https://user-images.githubusercontent.com/7533849/216913811-94dbc9bc-1bef-4c92-a16b-7b768574d1a8.mov

**Review by olarclara — APPROVED** [review]
🚫🍴

**Pull request merged**
