### PR TITLE
Update move modal styling

### PR DESCRIPTION
**Pull request by CompuIves**
Update active styling of folder to be consistent with our new design:
image

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/4624/commits/4ecc579b7d502f60014519135cf3764bf8475165 is at https://pr4624.build.csb.dev/s/new.

**Comment by DannyRuchtie** [comment]
Found two bugs:
1. The context menu animates up (making it hard to click it) 
2. Making folder in Personal account is not possible

**Comment by CompuIves** [comment]
Did the fixes!

> The context menu animates up (making it hard to click it)

It animates up when it can't animate down because there is no space. Do you want to change it?

**Comment by DannyRuchtie** [comment]
He noticed one inconsistency related to selected and hover states.
The move modal is now missing a hover state. It would be nice to align this with the dashboard

**Pull request merged**
