### PR TITLE
🔨 Switch Project to use useOvermind

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Resubmission of #2843

Follow-up of #2782

Things I did extra:
- Change `sandboxPrivacyChanged `'s signature to accept `0 | 1 | 2` instead of `{ privacy: 0 | 1 | 2 }`, because it only has 1 argument
- Put all styles into the `elements.ts` file
- Move `overmind` subscriptions as close as possible to the components itself instead of passing it through
- Extract `Environment`, `ForkedFrom`, `Git`, `Privacy`, `PrivacyNotice` & `Team` out of `Project`
- Use `FunctionComponent` instead of `React.FC`, since [it's the same](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f13238a5d2086cd87f3209704f8897f7f701d957/types/react/index.d.ts#L513), but `FunctionComponent` is a bit clearer I think

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3119/commits/a20dab159e71d895e14cd1df6d571df2751994a8 failed.

**Comment by MichaelDeBoey** [comment]
Typecheck will pass once DefinitelyTyped/DefinitelyTyped#40894 is merged and `@types/react-color` is updated

**Comment by CompuIves** [comment]
Interesting, why do we include `@types/react-color`?

**Comment by SaraVieira** [comment]
@MichaelDeBoey Do you mind closing this and splitting it up? 42 files is a lot :(

**Comment by MichaelDeBoey** [comment]
@CompuIves I included `@types/react-color`, to have a typed `SketchPicker` (used in `TemplateConfig/index.tsx`)

@SaraVieira I can make a new PR where I only have the first commit and a separate PR for the extraction of all the components?
Having each extraction a different PR will cause merge conflicts so

**Comment by christianalfoni** [comment]
@MichaelDeBoey I think we can get this through as the refactor is scoped to a specific part of the page. We just have to test the Project feature as a whole 😄 

Could you just add the type here as well? Just so that we can merge it in without having to wait for the other one?

**Comment by christianalfoni** [comment]
Oh sorry, it is a different repo... can we get around this? Write a comment ignore the typing or something. Do not want to have this pending, as we do not know when the other one will be merged

**Comment by SaraVieira** [comment]
@MichaelDeBoey Can you get the react color types off and then when thats merged we can add it?

Wanna get a bunch of these things in this month :)

**Comment by SaraVieira** [comment]
I deleted the @types/react-color and merged it :)

Good luck with thier pr 🎉

**Pull request merged**
