### PR TITLE
Fix local development build

### PR DESCRIPTION
**Pull request by baremetalfreak**
## What kind of change does this PR introduce?

Fixes a problem of running local development build. After opening http://localhost:3000/s/new fails with a 404 because https://codesandbox.stream/api/v1/sandboxes/new returns a 404.

> `curl -i 'https://codesandbox.stream/api/v1/sandboxes/new'`
```
HTTP/2 404
date: Thu, 11 Jul 2019 14:44:20 GMT
content-length: 17
set-cookie: __cfduid=d18d203693b38a69bbdda5b58d427e9661562856260; expires=Fri, 10-Jul-20 14:44:20 GMT; path=/; domain=.codesandbox.stream; HttpOnly; Secure
cache-control: max-age=0, private, must-revalidate
x-request-id: 2mo62v80q6r814dai8007nbh
via: 1.1 google
alt-svc: clear
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 4f4b8e0a2c92dbeb-LHR
```

## What is the current behavior?

/api requests are forwarded to to http://codesandbox.stream/api

## What is the new behavior?

/api requests are forwarded to to http://codesandbox.io/api

Run local build according to CONTRIBUTING.md, after opening http://localhost:3000/s/new, codesandbox loads fine with a react template.

## Checklist

- [ ] Documentation
- [x] Testing 
- [ ] Ready to be merged 
- [ ] Added myself to contributors table 

**This PR is just to make you aware of the problem and a potential workaround.**
I do not understand the purpose of codesandbox.stream or and how it differs from codesandbox.io. I assume the problem is in the infrastructure rather than the code.

### CODE REVIEW

**Comment by lbogdan** [comment]
Hey @baremetalfreak ,

Yeah, this was an oversight on our side, we needed `codesandbox.stream` to work on #2060 , but we forgot to change it back. Can you also change it here
https://github.com/codesandbox/codesandbox-client/blob/b6e7ee2192077629adfa0e71341cbb73d77fb994/packages/executors/src/serverExecutor.ts#L75
please?

**Comment by baremetalfreak** [comment]
Sure thing @lbogdan . How about https://github.com/codesandbox/codesandbox-client/blob/d02b9bb894fa5471cab4db4e8832c019c47ea182/packages/common/src/components/Preview/index.tsx#L64 ?

**Comment by lbogdan** [comment]
Yes, good catch, that one too! (wasn't showing up here, in GitHub, because the diff for that file was too large) Thanks!

**Comment by baremetalfreak** [comment]
Cool!. Technically there is one more spot here https://github.com/codesandbox/codesandbox-client/blob/d02b9bb894fa5471cab4db4e8832c019c47ea182/packages/common/src/utils/url-generator.ts#L9 and another one in comment https://github.com/codesandbox/codesandbox-client/blob/d02b9bb894fa5471cab4db4e8832c019c47ea182/packages/app/src/app/components/CodeEditor/VSCode/MonacoReactComponent.js#L48

**Comment by lbogdan** [comment]
Those two are fine - first is legitimate and second is just dead code that was probably committed by mistake.

**Pull request merged**
