### PR TITLE
Add ability to delete workspace

### PR DESCRIPTION
**Pull request by SaraVieira**
This PR adds the Frontend Part for an admin to be able to delete a workspace:

image

And the modal:

image

with users:

image

Only available in stream

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/5119/commits/92fd96b368d3087c3b3bfb57dc7d788643eb59f4 is at https://pr5119.build.csb.dev/s/new.

**Comment by siddharthkp** [comment]
hallelujah!

**Comment by DannyRuchtie** [comment]
Hi Sara, small consistency thing.
Could you style and align the cancel button like the other modals (on the right side next to the main button)? 
Screenshot 2020-11-16 at 14 24 07

**Review by DannyRuchtie — CHANGES_REQUESTED** [review]
Hi Sara, small consistency thing.
Could you style and align the cancel button like the other modals (on the right side next to the main button)? 
Screenshot 2020-11-16 at 14 24 07

**Comment by SaraVieira** [comment]
@DannyRuchtie Fixed

**Pull request merged**
