### PR TITLE
Notifications, showing, short selector a11y

### PR DESCRIPTION
**Pull request by yeion7**
## What kind of change does this PR introduce?

Refactor, reopen #2652 

## What is the current behavior?

The notifications has a few a11 issues

## Checklist

- [ ] Documentation
- [] Testing 
- [x] Ready to be merged 
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by yeion7** [comment]
@CompuIves what do you think about this? use the same styles as user menu for hover items

**Comment by diegohaz** [comment]
Read on the other PR that there was some performance issue! Is this still an issue? If so, please let me know if there's anything I can help on the Reakit side. :)

**Comment by yeion7** [comment]
@CompuIves any chance of moving this PR forward?

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/2711/commits/435bc57d7a91efeb8979f7bac6c17307a0472ee6 is at https://pr2711.build.csb.dev/s/new.

**Pull request closed without merging**
