### PR TITLE
more things

### PR DESCRIPTION
**Pull request by SaraVieira**
- [x]  Linking to file and removing general header
- [x]  When placing a comment and pressing enter, the input field also gets a newline - In replies when adding a comment after adding it state is not reverted back to empty @Sara Vieira
- [x]  Code is currently rendered in a different theme, I think we could use the existing VSCode theme, I can help with this too: @Sara Vieira @Ives van Hoorne
> Took the vscode theme we use and made it into prisma theme using the tool here: https://github.com/FormidableLabs/prism-react-renderer/tree/master/tools/themeFromVsCode and making it work in the browser

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3859/commits/ba3e3b7a4aca4fd4ac86a193b0097e490d45b4af failed.

**Comment by CompuIves** [comment]
Great way of making the theme work with Prisma!!

**Comment by christianalfoni** [comment]
Wow, super impressed @SaraVieira ❤️ 👏

**Comment by christianalfoni** [comment]
Tested, merging!

**Pull request merged**
