### PR TITLE
Remove old sidebar

### PR DESCRIPTION
**Pull request by siddharthkp**
Removed old sidebar
Removed flag

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3922/commits/9c2caacf4145ee0641c123c382f43ba27db12b91 failed.

**Comment by siddharthkp** [comment]
@SaraVieira @CompuIves Should we take the leap on this one?

**Comment by SaraVieira** [comment]
SHIP IT!!

**Comment by CompuIves** [comment]
YES! Merge it once we resolved the conflicts 😄 😄

**Pull request merged**
