### PR TITLE
change now.json to vercel.json

### PR DESCRIPTION
**Pull request by SaraVieira**
keep this file up to date

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/5101/commits/2d8eb77d822405b6183a912e7d8485ac41a7d042 is at https://pr5101.build.csb.dev/s/new.

**Review by CompuIves — COMMENTED** [review]
Do sandboxes with a `now.json` still work after this update?

**Comment by SaraVieira** [comment]
@CompuIves It does now lol

**Review by CompuIves — APPROVED** [review]
Great!

**Pull request merged**
