### PR TITLE
fix: add undefined check for mostUsedTemplates

### PR DESCRIPTION
**Pull request by jyash97**
## What kind of change does this PR introduce?
Bug Fix

## What is the current behavior?
When we visit a nested route for sandboxes like `/dashboard/sandboxes/${NAME}` it breaks the UI. This check is missing: https://github.com/codesandbox/codesandbox-client/commit/c000f60f77d96b15eb52af7d25bf3862334559c4#diff-49445e53b61b882865073a56f962aee4L114

## What is the new behavior?
Added the check

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

1. Tested Locally

## Checklist

- [ ] Documentation - N/A
- [x] Testing 
- [x] Ready to be merged
      
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3099/commits/a7f48ad195f5ebcf41221541dc6e4706abdc1782 is at https://pr3099.build.csb.dev/s/new.

**Comment by CompuIves** [comment]
Hey! Thanks for the PR. In what way does the UI currently break? I can't seem to repro the problem, but maybe I'm doing something wrong here.

**Comment by jyash97** [comment]
Hey @CompuIves thanks for the quick review 

I am not able to repro on the production now. I think these changes are deployed. 

This was the page that was breaking as `mostUsedSandboxTemplate ` was undefined:

image

**Comment by CompuIves** [comment]
Hmmmmm, but what is broken here? I think the "Create Sandbox" button supposed to fill up the remaining space. Well, nevertheless, it's good to fix this.  A clear typing issue!

**Comment by jyash97** [comment]
Before this fix, it was giving an error for accessing `niceName` from `undefined`

**Comment by MichaelDeBoey** [comment]
Very strange this was `undefined`.
Went through the code and it indeed can be `null`, but `undefined` shouldn't happen tho 😕

**Pull request merged**
