### PR TITLE
🔨 Switch SortOptions to use useOvermind

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Follow-up of #3183

Things I did extra:
- Change `orderByChanged`'s signature to accept a `OrderBy` instead of `{ orderBy: OrderBy }`, because it only has 1 argument
- Put all styles into the `elements.ts` file
- Use `FunctionComponent` instead of `React.FC`, since [it's the same](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f13238a5d2086cd87f3209704f8897f7f701d957/types/react/index.d.ts#L513), but `FunctionComponent` is a bit clearer I think
- Move `overmind` subscriptions as close as possible to the components itself instead of passing it through
- Extract `Overlay` into it's own component (separate file)
- Derive `SortOptions`' Props type
- Type `SortOptions`' `toggleSort` function

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3281/commits/1d6a3d2b732d0d781f7987fb5526707eb8a7a1bb is at https://pr3281.build.csb.dev/s/new.

**Comment by MichaelDeBoey** [comment]
Ping @christianalfoni @SaraVieira

**Comment by MichaelDeBoey** [comment]
Ping @christianalfoni @SaraVieira

**Comment by MichaelDeBoey** [comment]
Gerne 🙂

**Pull request merged**
