### PR TITLE
feat(ab experiment): change trigger to show sign-in ads in the editor

### PR DESCRIPTION
**Pull request by danilowoz**
Let's run our first experiement! 🚀 

---

This changes the trigger to show the sign-in ads on top of editor for anonymous users:
- A version: keep the same, runs after 3 minutos;
- B version: run after 3 changes in the editor;

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/5915/commits/f5f3a1ed6f8c497c8f04d9fb0c1b99b14fc9250d is at https://pr5915.build.csb.dev/s/new.

**Review by tromika — COMMENTED** [review]
@danilowoz would it be possible to add a tracking event to the banner clicks? So track clicks on the `to save your work` link? It would be really interesting to see how many users click there.

**Review by DannyRuchtie — APPROVED** [review]

**Comment by danilowoz** [comment]
@tromika we already have an event to the entire button (`Header Sign In Ad Clicked`), does it work? 
https://github.com/codesandbox/codesandbox-client/pull/5915/files#diff-635ee4b8486b9cb06949c3083817f2e126b0a01f039f6021ef8731cdc89478f4L76

**Comment by tromika** [comment]
I've created an experiment as `editor-signin-banner-trigger-real` on https://ab-testing-framework.vercel.app/ for this

**Review by tromika — APPROVED** [review]
Good to go now! Thanks so much!

**Pull request merged**
