### PR TITLE
Icon button

### PR DESCRIPTION
**Pull request by siddharthkp**
Built on top of https://github.com/codesandbox/codesandbox-client/pull/3595, review after that

It's a new component: IconButton, tried to build as a variant="icon" on Button, but it has different behavior on interaction, so made a new one 🤔 

gif:
icon button

### CODE REVIEW

**Comment by SaraVieira** [comment]
fancy

**Comment by SaraVieira** [comment]
Nice that you added the not disabled

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3596/commits/9c7cdac439f81615906b2ebe731da5a84a9f7a96 is at https://pr3596.build.csb.dev/s/new.

**Comment by SaraVieira** [comment]
Nice that you added the not disabled

**Pull request merged**
