### PR TITLE
fix: version copied from editor status bar

### PR DESCRIPTION
**Pull request by jyash97**
## What kind of change does this PR introduce?
Enhancement

## What is the current behavior?
When we copy the text from the status bar present in Editor we also get a comma in between version and commitSha. Like this 
`Version: ,ac5b1e45c`

## What is the new behavior?
Avoid Comma

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

1. Locally copied version
2. Tested the react behavior here: https://codesandbox.io/s/goofy-solomon-nq9bm?file=/src/App.js

## Checklist

- [x] Testing 
- [x] Ready to be merged
      
      

`Question` Can anyone explain to me how this is happening. Is React tracking explicitly if a string is passed it keeps as a string ( this is expected ) but when we declare a variable it tracks as an array ( Not able to understand this :/ )

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3949/commits/0667ac7724d56a37e1f467a9e07f23ee618de70d is at https://pr3949.build.csb.dev/s/new.

**Comment by lbogdan** [comment]
TBH, I would remove `Version: ` entirely, and just copy the short SHA. @CompuIves what do you say?

**Comment by CompuIves** [comment]
Agree!

**Comment by lbogdan** [comment]
(thanks for fixing this, btw, it also annoyed me a bit! 🙂)

**Comment by jyash97** [comment]
@lbogdan  Fixed :)

**Pull request merged**
