### PR TITLE
Remove all 'create-react-app-typescript' references

### LINKED ISSUE #1014: React + TS build not working
# 🐛 bug report

It's not possible to download and build React Typescript, just because of the wmonk/create-react-app-typescript recent changes.

Steps to reproduce:
1 - Create a React+TS sandbox
2 - Download it
3 - npm install & npm run build

Whats wrong?
1 - Failed to load tsconfig.json: Missing baseUrl in compilerOptions
2 - Cannot find "$PATH/tsconfig.prod.json" file.

Is there a related issue?
https://github.com/wmonk/create-react-app-typescript/issues/322

Actually, to solve this I made 2 simple steps:
1 - compilerOptions.baseUrl = '.'  >  tsconfig.json
2 - { 'extends': './tsconfig.json' } > tsconfig.prod.json

Although the sandbox is already using the fixed version ("^2.13.0" which resolves to "2.16.0") there are still missing files.

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
**What kind of change does this PR introduce?**
Code cleanup

**What is the current behavior?**
The code has references to `create-react-app-typescript` although we're using `create-react-app --typescript`

**What is the new behavior?**
All references to `create-react-app-typescript` are gone

**Checklist**:
- [ ] Documentation N/A
- [x] Tests
- [x] Ready to be merged 
- [ ] Added myself to contributors table  N/A

Closes #1014
Closes #1015

### CODE REVIEW

**Comment by SaraVieira** [comment]
I am actually not entirely sure about this so I asked ives to make sure

**Comment by MichaelDeBoey** [comment]
Yeah I think @CompuIves knows the most about everything related 🙂

**Comment by CompuIves** [comment]
I'm not sure if we can remove all the references yet, as there are still sandboxes that use create-react-app-typescript (https://codesandbox.io/search?refinementList%5Btemplate%5D%5B0%5D=create-react-app-typescript&page=1&configure%5BhitsPerPage%5D=12). A solution would be to convert all those to CRA, but we first need to make sure that the mapping of CRA-TS -> CRA is fluent.

**Comment by MichaelDeBoey** [comment]
Hmmmmm haven't thought about the ones that already exist... 😕

We could choose to convert all of those ourselves (automatically) to CRA or we could show some kind of notice that these ones aren't supported anymore and just convert them to a plain JS template? 🤔

@CompuIves Could you maybe give some more info what the meaning of the template is after I created a sandbox?  
All the dependencies are in place after creation, so don't  see any problems to just change the template to plain JS?

**Comment by MichaelDeBoey** [comment]
When @wmonk deprecated the `create-react-app-typescript` repo, he also [added a link](https://github.com/wmonk/create-react-app-typescript/blame/master/README.md#L4) to @Vinnl's [migration guide](https://vincenttunru.com/migrate-create-react-app-typescript-to-create-react-app) (which is also the [recommended guide by the CRA-team](https://github.com/facebook/create-react-app/blame/master/docusaurus/docs/adding-typescript.md#L44)) btw, so depending on the purpose of the template _after_ creating a sandbox, this one could  come in handy

**Comment by MichaelDeBoey** [comment]
@CompuIves Did you already have some time to look into my questions?

> @CompuIves Could you maybe give some more info what the meaning of the template is after I created a sandbox?
> All the dependencies are in place after creation, so don't see any problems to just change the template to plain JS?

**Comment by CompuIves** [comment]
Saw your questions now! 

> We could choose to convert all of those ourselves (automatically) to CRA or we could show some kind of notice that these ones aren't supported anymore and just convert them to a plain JS template? 🤔

I think there are some manual changes (like in the migration guide) that needs to be made. People can convert by themselves, but I don't like forcing them to use something new.

> Could you maybe give some more info what the meaning of the template is after I created a sandbox?

Templates are primarily used to say to the browser bundler of CodeSandbox what to bundle. We're changing that now though, and it will soon just be used as boilerplate and custom colors. By that time we can start removing the references to create-react-app-typescript.

Templates used to have more logic, they used to define what files to add when you press "Export" and what linting rules to enable. We started to make that configurable though, and nowadays their functionality is primarily giving a starting point for new people tos tart.

**Comment by CompuIves** [comment]
I think we should wait a bit with removing the template until we've fully extracted all template specific logic. Then we'll know for sure that we won't break anything.

**Comment by MichaelDeBoey** [comment]
Seems a logical decision to wait a bit longer indeed.

If you can lead me towards the changes that need to happen first, I'm happy to contribute 🙂

**Comment by SaraVieira** [comment]
There is nothing we can do for now in terms of code I think :(

Or at least we didn't yet see a pathway to it

**Comment by CompuIves** [comment]
I think we can re-evaluate this once we start moving everything to custom templates!

**Comment by MichaelDeBoey** [comment]
Yeah sure no prob 🙂

**Pull request closed without merging**
