### PR TITLE
Fix: Added fallback for avatar.io failing image

### PR DESCRIPTION
**Pull request by anuraghazra**
## What kind of change does this PR introduce?
Added fallback for broken avatar.io image

## What is the current behavior?
Broken image

## What is the new behavior?
Fallback to a default image

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

1. Step A
2. Step B
3. Step C

## Checklist

- [ ] Documentation
- [ ] Testing 
- [ ] Ready to be merged
      
- [ ] Added myself to contributors table
      

IDE - CodeSandbox

Seems like @EmmaWedekind's account is suspended for some reason thats why avatars.io is failing to fetch the image
Fallback img url: https://avatars.io/static/default_128.jpg

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3525/commits/571d672b2685c6766f97d1ddc26dd43fbc464e2e is at https://pr3525.build.csb.dev/s/new.

**Comment by SaraVieira** [comment]
Hey!

Thank you so much! The error was also because emma changed her hanlde and I updated that 

Next time this happens it will look way better, thank you!

**Comment by anuraghazra** [comment]
Welcome! :heart:  I'm really happy to contribute! 
btw can i do this "Added myself to contributors table"? :thinking:

**Comment by MichaelDeBoey** [comment]
@all-contributors Please add @anuraghazra for code

**Pull request merged**
