### PR TITLE
Delete ZenModeIntroductionModal, since it's not used anymore

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Resubmission of #3056, but now deleting the file since [it's not used anymore](https://github.com/codesandbox/codesandbox-client/pull/3056#issuecomment-563281081)

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3153/commits/74cc1c1dd00c49c91f136820e874f7756bb3dd71 is at https://pr3153.build.csb.dev/s/new.

**Comment by SaraVieira** [comment]
Heey

Do you mind fixing this ts file? I am not home

I think I did it with a merge :(

**Comment by SaraVieira** [comment]
Updated with master and working great!

Thank yoU!

**Comment by MichaelDeBoey** [comment]
With pleasure! 🙂

**Pull request merged**
