### PR TITLE
Update sign in banner design

### PR DESCRIPTION
**Pull request by SaraVieira**
Updates with a differnt design 
CleanShot 2021-01-28 at 14 20 42

When approved will add the 3 minute timeout back

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/5418/commits/6751bfe91468463741fd241f90402ebac72569d3 is at https://pr5418.build.csb.dev/s/new.

**Comment by DannyRuchtie** [comment]
image

Hi Sara a thing I did not realized was the height of the navbar. Seeing the screenshot it's probably better to match the height? Was that the height it was before I ask you to change it? 😓😅￼

**Comment by SaraVieira** [comment]
Yeah, I did see that but wanted to get your eyes on it. It looks weird af

it was 49px, and I just changed it :)

**Review by DannyRuchtie — COMMENTED** [review]
Strange color jump when the skeleton is shown.
not sure this could happen when shown after 3 min 
https://user-images.githubusercontent.com/46239581/106265149-e8dcdd00-6226-11eb-9c15-13e394f40a67.mov

**Review by DannyRuchtie — APPROVED** [review]

**Pull request merged**
