### PR TITLE
Update setup instructions

### PR DESCRIPTION
**Pull request by jyash97**
## What kind of change does this PR introduce?
Docs

## What is the current behavior?
`yarn start:home` gave this error `Cannot find module '@codesandbox/common/lib/config/env'`

## What is the new behavior?
Have updated the setup instructions to include this command

## What steps did you take to test this?
After running `yarn build:deps` I was able to run the homepage locally.

## Checklist

- [x] Documentation
- [ ] Testing 
- [x] Ready to be merged 
- [ ] Added myself to contributors table

### CODE REVIEW

**Comment by CompuIves** [comment]
Hmm, in this case `yarn start` automatically runs `yarn build:deps`. Maybe it would be better to add `yarn build:deps` as an extra script to `yarn start:home` instead.

**Comment by jyash97** [comment]
Right this happens only when we do `start:home` I can revert this change and add the following scripts.

**Comment by jyash97** [comment]
If we add this script in `start:home` than it would build this dependencies everytime we run `yarn start:home` and thus slowing down the process. Thoughts @CompuIves  ?

**Comment by lbogdan** [comment]
Maybe we can do the same as with `start` and `start:fast` - have `start:home` and `start:home:fast`?

**Comment by lbogdan** [comment]
Hey @jyash97 ,

Can you please revert all those formatting changes in `CONTRIBUTING.md`? Thanks!

**Comment by jyash97** [comment]
Hey @lbogdan  You can check the #2215 . I messed up with the formatting here. Thanks

**Pull request closed without merging**
