### PR TITLE
Feat/dashboard invite members

### PR DESCRIPTION
**Pull request by danilowoz**

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/5919/commits/884b7db3b8bd98e0337abe25d7f1e03c8689ea06 is at https://pr5919.build.csb.dev/s/new.

**Comment by tromika** [comment]
I've created this experiment as `dashboard-invite-members` on the AB framework

**Comment by tromika** [comment]
@danilowoz Danny's got me thinking about this a bit https://codesandboxapp.slack.com/archives/C023FHZ0ZN1/p1624352998015200 so please can you check if we can add an extra event where we can send the invitation URL to Amplitude?
image

**Review by tromika — APPROVED** [review]
LGTM! Thanks for adding the extra tracking events!

**Pull request merged**
