### PR TITLE
fix(CI): Only use resource-class:xlarge on master

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
After upgrading containers in 4d3ef6e, a73c2b3 & 5af1e63, CI keeps failing

https://app.circleci.com/pipelines/github/MichaelDeBoey/codesandbox-client/1321/workflows/1069edcc-f24d-463b-9a71-520112f3f5c5/jobs/9259

Schermafbeelding 2020-04-15 om 17 12 46

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3908/commits/8385d866e3ce82e6ecf6ffb7a77ab025a1812972 is at https://pr3908.build.csb.dev/s/new.

**Comment by MichaelDeBoey** [comment]
@CompuIves I'm not really familiar with CircleCI config and it seems my [WIP change](https://github.com/codesandbox/codesandbox-client/pull/3908/commits/37e7e8e3f47a713bb9cbdbdbf1faae8f4744a449) is still failing 😕

https://app.circleci.com/pipelines/github/MichaelDeBoey/codesandbox-client/1341/workflows/6464a8b6-342a-44ea-8783-be3d84da7649/jobs/9280

I'm open for suggestions 🙂

**Comment by MichaelDeBoey** [comment]
I managed to get it run 🎉

In a more perfect world, the things on `master` would only run on the original repo, not on a fork.

This way, branches on the original repo can benefit all the time from more CPUs.
CircleCi doesn't have a way to check whether or not the workflow is run on a fork or not tho (like [Travis has](https://docs.travis-ci.com/user/conditions-v1#integration))

`master` on forked repos will still fail too.

**Comment by MichaelDeBoey** [comment]
I found out I had CircleCI configured to follow/build `MichaelDeBoey/codesandbox-client` (my fork of the repo), which was why all my PRs were build on my personal CircleCI account instead of via the CodeSandbox account.

Removed the following/building and now my PR is build via the CodeSandbox account and can benefit from the extra CPUs 🥳
https://app.circleci.com/pipelines/github/codesandbox/codesandbox-client/6370/workflows/b7ea9612-4cd0-44ee-8b89-1da74a96addb

**Comment by MichaelDeBoey** [comment]
I found out I had CircleCI configured to follow/build `MichaelDeBoey/codesandbox-client` (my fork of the repo), which was why all my PRs were build on my personal CircleCI account instead of via the CodeSandbox account.

Removed the following/building and now my PR is build via the CodeSandbox account and can benefit from the extra CPUs 🥳
https://app.circleci.com/pipelines/github/codesandbox/codesandbox-client/6370/workflows/b7ea9612-4cd0-44ee-8b89-1da74a96addb

**Pull request closed without merging**
