### PR TITLE
🔨 Switch Live to use useOvermind

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Follow-up of #3177 & #3208

Things I did extra:
- Change `signInToRoom` & `roomJoined`'s signatures to accept a `string` instead of `{ roomId: string }`, because they only have 1 argument
- Use `FunctionComponent` instead of `React.FC`, since [it's the same](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f13238a5d2086cd87f3209704f8897f7f701d957/types/react/index.d.ts#L513), but `FunctionComponent` is a bit clearer I think
- Put all styles into the `elements.ts` file
- Extract `Error`, `Loading` & `NotAuthenticated` from `Live`
- Remove `BlinkingDot`

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3558/commits/2e017e337613434788180aad81b179df85a9ffc3 failed.

**Comment by MichaelDeBoey** [comment]
@SaraVieira @christianalfoni I've rebased onto `upstream/master`, so this could be merged now 🙂

**Comment by MichaelDeBoey** [comment]
@SaraVieira @christianalfoni I've rebased onto `upstream/master`, so this could be merged now 🙂

**Comment by MichaelDeBoey** [comment]
@SaraVieira @christianalfoni I've rebased onto `upstream/master`, so this could be merged now 🙂

**Comment by MichaelDeBoey** [comment]
@SaraVieira @christianalfoni I've rebased onto `upstream/master`, so this could be merged now 🙂

**Comment by SaraVieira** [comment]
Thank you!

**Pull request merged**
