### PR TITLE
Refactored | Overmind Hacktober | /app/pages/common/Modals/NetlifyLogs/index.js

### PR DESCRIPTION
**Pull request by NileshPatel17**
## What kind of change does this PR introduce?
Refactor code for hacktoberfest #2621

## What is the current behavior?
```/app/pages/common/Modals/NetlifyLogs/index.js``` was using inject and observer from app/componentConnectors

## What is the new behavior?
1. converted class component to functional component
2. uses ```useOvermind``` from ```app/overmind``` and ```js``` file converted to ```tsx``` file

## What steps did you take to test this? This is required before we can merge.

1. ```yarn:lint```: There were several linting errors, but none relevant to the scope of this PR
2.  ```yarn:test```: Ran successfully

## Checklist

- [ ] Documentation
- [x] Testing 
- [x] Ready to be merged
      
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by CompuIves** [comment]
This is great, thanks a lot! Did you also verify seeing the Netlify Logs?

**Comment by NileshPatel17** [comment]
I have no idea how to do that

**Comment by CompuIves** [comment]
You can do this by forking a sandbox, then looking in the sidebar at deployments, there deploy the sandbox with Netlify and then check the logs (View Logs button). Let me know if you could use help with this!

**Comment by NileshPatel17** [comment]
I tried to test with below link. is it correct url?
https://pr2727.build.csb.dev/s/new
I  am unable to login with github
image

**Comment by SaraVieira** [comment]
Can you please pull from master and that is solved?

After that you can login

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/2727/commits/6d338568fedd9d3c2e63f9e7eb753ab487be0312 is at https://pr2727.build.csb.dev/s/new.

**Comment by NileshPatel17** [comment]
I wonder why i do not see "Deploy" button with latest commit build( https://pr2727.build.csb.dev/s/new)
image

**Comment by NileshPatel17** [comment]
Although i can see logs of another project which i deployed yesterday from production app.
image

**Comment by SaraVieira** [comment]
Hey!

Angular does not work with netlify. You can see it in vue or react projects for example

**Comment by NileshPatel17** [comment]
Tested with react project, and it looks good. i can see the logs.
image

**Pull request merged**
