### PR TITLE
Skeleton

### PR DESCRIPTION
**Pull request by christianalfoni**

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3583/commits/adb0a88e013adc69ef7cd344477854e94c4750ca failed.

**Comment by CompuIves** [comment]
Very nice! One thing I notice is that after loading we sometimes get the vscode dark+ selected. I don't know why. Checking.

**Comment by CompuIves** [comment]
image
This one

**Comment by christianalfoni** [comment]
I am not able to reproduce this, but I am updating this branch with https://github.com/codesandbox/codesandbox-client/pull/3607, which was just merged. It probably solves it or I have to get more info on how to reproduce.

**Pull request merged**
