### PR TITLE
fix: check for package alias when resolving dependencies

### PR DESCRIPTION
**Pull request by sjohnson-sage**
## What kind of change does this PR introduce?

Fixes: #5863

## What is the current behavior?

See #5863 - Dependency resolution for aliased packages was recently broken.

## What is the new behavior?

When a dependency uses a npm alias, the package is resolved.

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

1. Set up the project locally.
2. Copied and pasted the package.json and index.js files from a broken example (https://codesandbox.io/s/carbon-quickstart-xzkbp?file=/public/index.html:1607-1627) and reproduced the issue.
3. Made my changes to the code
4. Rebuilt the project and confirmed that it now works as expected, i.e. the sandbox works correctly and has no errors regarding trying to fetch the aliased package from any registry.

## Checklist

- [ ] Documentation N/A
- [x] Testing 
- [x] Ready to be merged
- [ ] Added myself to contributors table N/A

Hopefully this is ok, feel free to contact me on Github with any questions!

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/5864/commits/8f0036fdef7c6b07645e37ffc04db73ae5b80788 is at https://pr5864.build.csb.dev/s/new.

**Review by DeMoorJasper — APPROVED** [review]
Looks good, thanks for this contribution

**Comment by sjohnson-sage** [comment]
Thanks for looking at this so quickly @DeMoorJasper! When can we expect Codesandbox CI to pick up this change?

**Comment by DeMoorJasper** [comment]
Getting deployed right now so think it should be live in about 10 minutes

**Pull request merged**
