### PR TITLE
Support dynamic import in vanilla template for Babel v7

### PR DESCRIPTION
**Pull request by pshrmn**
**What kind of change does this PR introduce?**

This PR enables use of dynamic `import()` in the vanilla template.

Fixes https://github.com/codesandbox/codesandbox-client/issues/1930

**What is the current behavior?**

A syntax error occurs.

**What is the new behavior?**

`import()` works as expected.

**Checklist**:

- [ ] Documentation
- [x] Tests
- [x] Ready to be merged 
- [ ] Added myself to contributors table 

I split the way that the change is added based on how Parcel does it internally.

v7 should be ready, it simply uses `parserOpts`.

v6 could use some work. My "fix" uses a plugin, which is what Parcel does for Babel v6. Parcel creates a custom plugin that is essentially the same as `babel-plugin-syntax-dynamic-import`. That wasn't playing nicely when I tried to do the same, so I updated the `babel.6.26.js` module to support `babel-plugin-syntax-dynamic-import`. I don't like this solution, particularly because the `babel.6.26.min.js` module wasn't updated, but it wasn't immediately obvious where these static files get generated.

**Edit:** I realized why the custom plugin wasn't working. `getDefaultCode` serializes the return object, so the function is transformed into `null`. I think the best solution will be to use `babel-plugin-syntax-dynamic-import` provided I figure out how to generate the minified Babel 6 module.

### CODE REVIEW

**Comment by lbogdan** [comment]
@pshrmn Very nice!

Doesn't seem to be working with v6, though? http://pr1931.cs.lbogdan.tk/s/muddy-field-v05k2

**Comment by pshrmn** [comment]
@lbogdan I think that is because it is using the minified version, which I didn't fix.

**Comment by pshrmn** [comment]
Ideally I would prefer to get Babel 6 working without touching those static files, but if that is the best approach, I would rather not try manually editing the minified version. Are those modules generated by some external script?

**Comment by pshrmn** [comment]
I removed the Babel 6 support for now. Both static Babel files were added in https://github.com/codesandbox/codesandbox-client/pull/446, so I think that the builds must have happened externally.

**Comment by CompuIves** [comment]
Ahh, good point! I think we can merge this one in the meantime. I think I got the other ones by building `babel-standalone` with webpack.

**Comment by pshrmn** [comment]
Does the PR build through `cs.lbogdan.tk` no longer work? I wanted to do a sanity check that this still works before pinging about getting it merged but I'm getting a 503 error.

**Comment by lbogdan** [comment]
Hey @pshrmn ,

We recently made some improvements to the PR building workflow, please push a new (empty) commit so that it will pick up and build this PR.

**Comment by lbogdan** [comment]
Or you can merge `master`, as there were a few changes in the meanwhile. 🙂

**Comment by pshrmn** [comment]
I think that this is fine to merge. I'm not sure why the integration test is failing; the failing sandbox (https://codesandbox.io/s/6w66jzw3mn) is a Preact starter while this PR only affects Parcel templates.

**Pull request merged**
