### PR TITLE
🔨 Switch TemplateConfig to use useOvermind

### PR DESCRIPTION
**Pull request by MichaelDeBoey**

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
Same problems as in #2562

**Comment by SaraVieira** [comment]
`published ` is also true or false but can be undefined

**Comment by christianalfoni** [comment]
HElping out with the typefix now

**Comment by christianalfoni** [comment]
ehm... how could this even work?

```ts
    editTemplate({
      template: {
        color: selectedColor,
      },
    });
```

It needs the ID to save it... though it did save it, wuut?

**Comment by christianalfoni** [comment]
Okay, fixed a bug related to editing colors and fixed the type: https://github.com/MichaelDeBoey/codesandbox-client/pull/305

**Pull request merged**
