### PR TITLE
Consistency tweak on autofill user /ui

### PR DESCRIPTION
**Pull request by DannyRuchtie**
@compuives I wanted to add the border-radius but turns out the paddingY was hiding the round courners. I removed the paddingY.

Also Added border radius on the container

It seems like it was there for a reason. Not sure I can delete it

Old
Screenshot 2020-05-27 at 10 10 47

New 
Screenshot 2020-05-27 at 10 14 34

------
**Container**

Old
Screenshot 2020-05-27 at 10 35 37

New 
Screenshot 2020-05-27 at 10 35 51

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/4217/commits/761fff586c7c6962ac1a36603485bcd434490bed is at https://pr4217.build.csb.dev/s/new.

**Comment by CompuIves** [comment]
Ah, yes, the `paddingY` was there to give the items a bit more spacing. This looks a bit cramped:

image

I don't understand how a padding can remove a border-radius though. Is there another way to fix it?

**Comment by CompuIves** [comment]
Oh this fixes it actually. Looks good to me! Nice work @DannyRuchtie !

**Comment by DannyRuchtie** [comment]
> Ah, yes, the `paddingY` was there to give the items a bit more spacing. This looks a bit cramped:
> 

> I don't understand how a padding can remove a border-radius though. Is there another way to fix it?

We could make the avatars smaller 20x20. Run into the same issue when designing the new notification center. (I think the border-radius is the thing that makes the list feel cramped)

**Pull request merged**
