### PR TITLE
Add .nvmrc

### PR DESCRIPTION
**Pull request by baremetalfreak**
## What kind of change does this PR introduce?

Adds `.nvmrc` config file for nvm / fnm to indicate what node version is required and help avoid frustration from a failing build

## What is the current behavior?

one has to read the docs and remember to set node to v10

## What is the new behavior?

The presence of `.nvmrc` indicates that a particular node version is required. Running `nvm use` or `fnm use` sets it properly 

- [x] Documentation
- [ ] Testing 
- [x] Ready to be merged 
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by baremetalfreak** [comment]
Because of the commit hook, the CONTRIBUTING.md gets reformatted. I split my change and the reformatting into separate commits to make it easier to review what was actually changed.

**Comment by MichaelDeBoey** [comment]
Can’t we just set the `engine` field in `package.json` instead? 🤔

**Comment by lbogdan** [comment]
I also think @MichaelDeBoey's suggestion is a bit better, considering that not everybody uses `nvm` / is used to look at `.nvmrc`, whereas when setting the `engine` in `package.json` running `yarn` will hard fail with a descriptive error message. That doesn't of course mean we can't have both. 🙂

**Comment by baremetalfreak** [comment]
That would be cool. As far as I know `nvm` and `fnm` do not support `package.json`. I think the reason is that `nvm` was written as a bash script and the author did not want to parse json. And `fnm` is intended to be plug compatible replacement of `nvm`.

I think it would be a good idea for an improvement in fnm. Since it is written in reason, I do not see why it would not parse package.json

**Comment by baremetalfreak** [comment]
@lbogdan that is what I have in some of my projects + a test that verifies they are in sync

**Comment by baremetalfreak** [comment]
Someone already asked about `fnm` support of `engines` here https://github.com/Schniz/fnm/issues/39 but they did not implement it because it can be ambiguous

**Comment by baremetalfreak** [comment]
@lbogdan @MichaelDeBoey I will add the `engines` part. Do you want me to keep `.nvmrc` and add a test to verify the two are in sync or just the `engines` part?

**Comment by CompuIves** [comment]
I think we should do both, set the `package.json#engines` and `.nvmrc`. Best experience on both accounts (automatic switching and fail on install). I also saw that there were changes in `CONTRIBUTING.md`, though I think those were accidental. Could you revert the changes for that file?

**Comment by baremetalfreak** [comment]
@CompuIves I added myself to the contributor list according to your guidelines. But I can do that in a separate PR later.

**Comment by baremetalfreak** [comment]
Oops, mixed two things together. The changes in `CONTRIBUTING.md` added a note about using `nvm` or `fnm` https://github.com/codesandbox/codesandbox-client/pull/2290/commits/8c8d4e8d2282df0e79c1db47e0899455af35e951#diff-6a3371457528722a734f3c51d9238c13R44 do you want me to remove that?

**Comment by CompuIves** [comment]
Oh no that makes sense! The CONTRIBUTING.md file doesn't normally change when you add yourself to the table, just README.md and all-contributors.json.

**Comment by baremetalfreak** [comment]
@CompuIves you are right, I just noticed see my comment above https://github.com/codesandbox/codesandbox-client/pull/2290#issuecomment-521583813

**Comment by CompuIves** [comment]
Great! Let me know if you want to add the test, I'm already happy with these changes but having a test would be super nice to have.

**Comment by baremetalfreak** [comment]
Not sure where to put the test since this is a monorepo. If you tell me the right place, I'll be happy to add it.

**Comment by lbogdan** [comment]
https://github.com/codesandbox/codesandbox-client/blob/64e62e6f7f6e4c89d5cfb3cb8f5bbf0c24cefd17/package.json#L98
We should probably not make it **that** restrictive (the PR build is currently failing, because that uses `10.15`).

**Comment by baremetalfreak** [comment]
@lbogdan `v10.15.0` ?

**Comment by lbogdan** [comment]
Frankly, I'd probably test if it works on `10.0`, and use that instead. I don't know how many people keep their node version up to date (I usually don't 🙂 ), and it's annoying to have to upgrade just to be able to run a project you want to contribute to.

**Comment by CompuIves** [comment]
> If you tell me the right place,

Haha, I don't know either! Let's just merge this change in already, I think this change will be really good for new contributors.

**Comment by baremetalfreak** [comment]
Changed to 10.0..

**Comment by CompuIves** [comment]
This is perfect, thanks a lot for this change @baremetalfreak!!

**Pull request merged**
