### PR TITLE
🔨 Switch Profile/Header to use useOvermind

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Things I did:
- Put all styles into the `elements.ts` file
- Move `overmind` subscriptions as close as possible to the components itself instead of passing it through
- Export `Header` by a named export  instead of a `default export`

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3407/commits/e909cbe8ded6d4d0df2840c4f0232dab832348d1 is at https://pr3407.build.csb.dev/s/new.

**Comment by MichaelDeBoey** [comment]
@SaraVieira Fixed `ContributorsBadge`'s size 🙂

**Comment by SaraVieira** [comment]
Awesome! Looks guuuuuddd

**Comment by MichaelDeBoey** [comment]
With pleasure! 🙂

**Pull request merged**
