### PR TITLE
fix messages not visible

### LINKED ISSUE #1910: hover content is blocked when the code is at the top of the file
# 🐛 bug report

## Tooltip contents are blocked by editor tab:

image

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1557437664-2c65ca12f
| Browser          | Chrome 74.0.3729.131
| Operating System | MacOS 10.14.4

### PR DESCRIPTION
**Pull request by SaraVieira**
## What kind of change does this PR introduce?

Bug Fix

## What is the current behavior?

https://github.com/codesandbox/codesandbox-client/issues/1910

## What is the new behavior?

Messages are visible

Closes #1910

### CODE REVIEW

**Comment by CompuIves** [comment]
Does the menu bar (File, Edit) still work with this? I remember I had issues with that.

**Comment by CompuIves** [comment]
I just checked, I think this is the hard thing about it:

image

**Comment by SaraVieira** [comment]
AAAAAAAAAAAAAAAAAAAAA

**Comment by SaraVieira** [comment]
Closed due to idea not working

**Pull request closed without merging**
