### PR TITLE
Add .abell language features to vscode-extensions

### PR DESCRIPTION
**Pull request by saurabhdaware**
Hi, I am working on a static-site-generator and a template engine called [Abell](https://github.com/abelljs/abell). It adds a new extension (`.abell`) with a new syntax. I would love to see the code highlighting in codesandbox so that users can create blog from a sandbox. 

Thanks!

## What kind of change does this PR introduce?

Adds new extension for `.abell` files. 

## What is the current behavior?

`.abell` files are not highlighted

## What is the new behavior?

`.abell` files have proper highlighting and add some snippets

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

1. I ran a dev server locally
2. In http://localhost:3000/s/new, created a new file called `sample.abell`
3. Added the Abell code (You can refer to [Abell Example CodeSandbox](https://codesandbox.io/s/abell-v04-test-li1im?file=/src/index.abell) for example code)

## Checklist

- [ ] Documentation N/A
- [ ] Testing  N/A (or I am not sure how to)
- [x] Ready to be merged
      
- [x] Added myself to contributors table
      

Thank you! and let me know if something needs to be changed :D

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/4628/commits/e510c261e40a82735671a24232da00ead4163883 is at https://pr4628.build.csb.dev/s/new.

**Comment by SaraVieira** [comment]
Hey!

It seems like you did not run `yarn compile` inside the `standalone-packages/vscode-extensions`.

Mind doing that? Then it will work in the PR enviroment

**Comment by saurabhdaware** [comment]
Seem to not work in preview... I'll check I guess I didn't commit `extensions/index.js` which was somehow generated (probably after yarn compile I believe)

**Comment by saurabhdaware** [comment]
Yup working as expected now!

Screenshot of .abell file from codesandbox preview. Shows the highlighted abell code

**Comment by SaraVieira** [comment]
Nice!!! Thank you!!

**Pull request merged**
