### PR TITLE
Fix arrow overflow

### PR DESCRIPTION
**Pull request by akash-joshi**
## What kind of change does this PR introduce?

This PR fixes a styling bug on the recents page of Codesandbox-client.

## What is the current behavior?

The arrow overflows to the bottom, as shown in the image below.

Screenshot 2020-06-02 at 10 02 49 AM

## What is the new behavior?

The arrow doesn't overflow.

Screenshot 2020-06-02 at 10 04 14 AM

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

The visual testing while coding was done in the browser on the live website itself.

## Checklist

- [ ] Documentation
- [X] Testing 
- [X] Ready to be merged
      
- [X] Added myself to contributors table

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/4278/commits/cfd13ee6f92980cef4e5b3256eab6c66d5c0bf65 is at https://pr4278.build.csb.dev/s/new.

**Comment by siddharthkp** [comment]
Thanks for taking the time!

**Comment by akash-joshi** [comment]
Thanks for taking the time to review guys :)

Let me know if any fixes are needed from my side.

**Comment by SaraVieira** [comment]
Hey!

Thank you so much for the fix :)

**Comment by akash-joshi** [comment]
Thanks Sara, Bogdan and Sid !

**Pull request merged**
