### PR TITLE
fix: disable button on empty preset name

### PR DESCRIPTION
**Pull request by jyash97**
## What kind of change does this PR introduce?
Enhancement

## What is the current behavior?
We can create a custom preset with only spaces

## What is the new behavior?
Disable button if the name is empty.

image

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

1. Tested spaces
2. With valid name
3. No value

## Checklist

- [x] Testing 
- [x] Ready to be merged

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/5477/commits/94926c517c1f970e03c082e8ce0ace1252ecbfe0 is at https://pr5477.build.csb.dev/s/new.

**Comment by jyash97** [comment]
Hey @SaraVieira  👋 

Can you check this whenever you get time?

Thanks for this feature, really find it helpful while developing/learning things 🔥

**Comment by SaraVieira** [comment]
Heeey

Sorry I was in small vacations 😅

This looks super good! Thank you once again 😄

**Comment by jyash97** [comment]
Thanks for the quick review 😄

**Pull request merged**
