### PR TITLE
Added the B varaint for the A/B test

### PR DESCRIPTION
**Pull request by DannyRuchtie**
Added B variant in the homepage index.html for the A/B Test.
Ives mentioned to have two separate pages (This is a demo to show how it will look)
I commented out the old Hero, we now need to figure out how we want to handle the second page (Also  possible with Google Optimize) 

@CompuIves can you have a look and lets discuss how we want to implement

Screenshot 2020-04-14 at 17 43 12

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3898/commits/31930840400447106a82bd041cf4904e09b83c60 is at https://pr3898.build.csb.dev/s/new.

**Comment by garethx** [comment]
Maybe add some top margin to button on mobile widths? 
Screenshot 2020-04-14 at 17 04 20

**Comment by garethx** [comment]
Can we move the IDE image up a bit? Seems like a lot of wasted vertical space.
Screenshot 2020-04-14 at 17 06 17

**Comment by DannyRuchtie** [comment]
> Maybe add some top margin to button on mobile widths?
> Screenshot 2020-04-14 at 17 04 20

Added mobile css and fixed hight @garethx

**Comment by DannyRuchtie** [comment]
@CompuIves and @garethx is it useful to add an additional value to the url's so it's easier to check urls coming form the new buttons? ( for example:  .../s/new?=start)

**Comment by garethx** [comment]
@DannyRuchtie I'd like to avoid that if possible, as URL parameters are treated as different pages by crawlbots and can impact SEO. How is the two separate page approach being implemented? Will the variant get forwarded to a different URL e.g. codesandbox.io/index2.html or something?

**Pull request merged**
