### PR TITLE
fix: Blog Link and Blogs Query on Homepage

### PR DESCRIPTION
**Pull request by jyash97**
## What kind of change does this PR introduce?
Update Blog Query & Link

## What is the current behavior?
- Currently, on Homepage in the recent publication, we show medium posts I have changed it to use the current blog query.
- Update blog link from `medium` to `/blog`

## What is the new behavior?
image

## What steps did you take to test this?
Confirmed on localhost as seen in above image.

## Checklist

- [ ] Documentation
- [x] Testing 
- [x] Ready to be merged 
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
Hi @jyash97!

Thanks for taking the time to create this PR.

Unfortunately this PR will be obsolete once #2011 and it's follow-up PR's (which I'm already working on) are merged 😕

> ### Follow-ups
> - [ ] Change `/post/blog-slug` to `/blog/blog-slug` an redirect all old links to the new ones
> - [ ] Make the blog-section on the homepage work with the new Markdown files instead of only the Medium posts
> - [ ] Use the `remark-embedder` plugin in other parts (docs, ...) too (delete the `https://codesandbox.io/s/embed/...` links)

Keep up the good work tho! 👍👊
You're always welcome to suggest other improvements to the codebase 🙂

**Comment by jyash97** [comment]
Hey @MichaelDeBoey 
Great work on the PR 💯 
Any idea when the PR would be merged as currently the content is not correct on homepage and few blog links I think we should keep the content updated. And if you haven't started the follow up implementation this can be merged and can be updated on later point of time.

Thoughts ? @lbogdan @CompuIves

**Comment by MichaelDeBoey** [comment]
@jyash97 I've been working the most of the time on the main PR first, but the follow-up PR's are on their way (I already have an implementation on my local machine, but I'm not happy about it yet, but will be for the coming days 🙂)

**Comment by CompuIves** [comment]
I might want to merge this right now already, since our build system is currently clogged up because of Medium rate limiting us. My goal is to remove the dependency on Medium today already, since some important bug fixes are in the pipeline. I'll merge this already (thanks a lot @jyash97!), we can do the mentioned extra attention in a follow up PR.

**Pull request merged**
