### PR TITLE
Refactor /app/pages/Curator/index.js to use overmind (Hacktoberfest)

### PR DESCRIPTION
**Pull request by sheriallis**
## What kind of change does this PR introduce?

Refactors code for Hacktoberfest as mentioned in #2621.
@Saeris @christianalfoni

## What is the current behavior?

Cerebral is being used for state management

## What is the new behavior?

`/app/pages/Curator/index.js` was renamed to `/app/pages/Curator/index.tsx` and refactored to use Overmind  

## What steps did you take to test this? This is required before we can merge.

1. Ran `yarn test` with no errors
2. Ran `yarn lint` with no errors
3. Ran `yarn typecheck` with no errors

## Checklist

- [ ] Documentation
- [X] Testing 
- [X] Ready to be merged
      
- [ ] Added myself to contributors table
      

For some reason I couldn't run `yarn contributors:add` successfully on my system.

### CODE REVIEW

**Comment by CompuIves** [comment]
Heyo! Could you merge with master? I think there is an import issue that should be resolved on master.

**Comment by sheriallis** [comment]
I merged with master and fixed the type error relating to Curator that popped up after merging. 

The typecheck test is currently failing because of another type error coming from `src/app/pages/common/ErrorBoundary/ErrorBoundary.tsx` 

```error TS2339: Property 'location' does not exist on type 'IErrorBoundaryProps'.```

**Comment by SaraVieira** [comment]
Hey

I am so sorry but seems this alçready been merged

We have been having some issues trying to keep up with the PR's :(

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/2786/commits/95f62dca8f7d5e3616b89bb73cd976581298c199 is at https://pr2786.build.csb.dev/s/new.

**Pull request closed without merging**
