### PR TITLE
fix(router): keep existing state when replacing

### PR DESCRIPTION
**Pull request by posva**
## What kind of change does this PR introduce?

This is a proposal rather than a fix. I would say that the state should be preserved when calling `history.replaceState` instead of being deleted. I came from https://github.com/codesandbox/codesandbox-client/issues/4905 but I don't remember anymore a case where the current solution would fail...

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

1. Step A
2. Step B
3. Step C

## Checklist

- [ ] Documentation
- [ ] Testing 
- [ ] Ready to be merged
      
- [ ] Added myself to contributors table

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/5302/commits/2adeb22fa8750b5e093d9819ee6328b35e2b1044 is at https://pr5302.build.csb.dev/s/new.

**Comment by posva** [comment]
Check

**Comment by danilowoz** [comment]
Thanks for helping us clean up!

This PR does not seem to improve user or developer experience in a noticeable way, even fixing any bug. We are very sorry that you spent time on this, only to see us closing the PR. But we hope you understand our reasoning and do not feel discouraged to make other contributions 😄

**Comment by posva** [comment]
Sure. I don't remember anymore but if this `replaceState()` was called for the window on the right of code sandbox, then it should be changed with the proposal as `replaceState()` and removing the current state will break client side routing that relies on the history state like Vue Router 4.

If it's about the codesandbox application itself, then it doesn't matter

**Pull request closed without merging**
