### PR TITLE
Introduce vertical mode to embeds

### PR DESCRIPTION
**Pull request by CompuIves**
Introduces vertical mode for embeds:

image

Test can be done here: http://pr3339.build.csb.dev/embed/new?verticallayout=1

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3339/commits/0fce644d01c3c28db9da6cdc462231892a74c3f8 is at https://pr3339.build.csb.dev/s/new.

**Comment by siddharthkp** [comment]
Good start.

Here's one of the configs that was difficult to design for - 

1. [Editor only mode](https://pr3339.build.csb.dev/embed/new?view=editor&verticallayout=1&hidenavigation=1)

2. [Preview only mode](https://pr3339.build.csb.dev/embed/new?view=preview&verticallayout=1&hidenavigation=1)

The new buttons definitely make it more obvious on how to open preview

(Bug: the buttons should not be visible when the view is mixed)

**Comment by DannyRuchtie** [comment]
Screenshot 2020-01-17 at 10 14 18
@CompuIves 
Litle design detail. The Open Sandbox button in full code view is positioned to low.
Can we align this with the Preview mode?

**Comment by DannyRuchtie** [comment]
In fullscreen view when you resize the window the layout does not update.
Not a big issue when you make the screen bigger. But when making the screen less heigh you lose the switch control. 

Should the layout update on window resize? 


Screenshot 2020-01-17 at 10 17 37

**Comment by CompuIves** [comment]
> In fullscreen view when you resize the window the layout does not update.

Ah yes, this is both the case for horizontal and vertical, but I can add a recalculation in this PR for that. I'll also make sure to fix the mixed view!

**Comment by CompuIves** [comment]
Going to revive this this week!

**Comment by DannyRuchtie** [comment]
What's the status of this one?

**Pull request closed without merging**
