### PR TITLE
fix:EntryTitleInput overflow problem in workspace

### PR DESCRIPTION
**Pull request by R4M80MrX**
## What kind of change does this PR introduce?
Bug fix

## What is the current behavior?
https://github.com/codesandbox/codesandbox-client/issues/2301

## What is the new behavior?
Behave like codesandbox.io

## What steps did you take to test this?
`yarn test` and `yarn lint`

## Checklist

- [ ] Documentation N/A
- [X] Testing 
- [X] Ready to be merged 
- [X] Added myself to contributors table

### CODE REVIEW

**Comment by R4M80MrX** [comment]
And I found some problems when using Monaco Editor
批注 2019-08-19 180932
批注 2019-08-19 181155
Is it necessary to fix these problems?

**Comment by CompuIves** [comment]
So interesting that this didn't happen on production before, well, the mystery has been solved! Thanks for helping out on this!

**Comment by CompuIves** [comment]
> Is it necessary to fix these problems?

I don't think it's needed right now. Can you reproduce this consistently?

**Comment by R4M80MrX** [comment]
> > Is it necessary to fix these problems?
> 
> I don't think it's needed right now. Can you reproduce this consistently?

Thank you for your timely reply. I forgot to give the details above. 

The first problem is because the \<Cofiguration> component doesn't have `this.sandbox` on it. So when changing module from a supported config to something else, `editor.sandbox`  in `disposeModuleHandler` at `Content\index.js` Ln298 will be `undefined`. 

The second maybe because that when changing module from a no-\<Monaco> component to \<Monaco>. The editor tries to re-add the existing model. But I noticed that all models and editor itself were disposed when componentWillUnmount. So I'm a little confused and trying to figure out.

Neither of them affects the app now. I'm just learning the code.☺️

**Pull request merged**
