### PR TITLE
Fix typescript error

### PR DESCRIPTION
**Pull request by yeion7**
## What kind of change does this PR introduce?

fix

## What is the current behavior?

#2822

Possibly related

#2911 #2836

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

1. Create a React TS sandbox
2. Fork sandbox
3. Save file or add new dependency

## Checklist

- [ ] Documentation
- [ ] Testing 
- [x] Ready to be merged
      
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by yeion7** [comment]
@christianalfoni 🙏🏻

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/2913/commits/e21dc1d9be08a050138ad97a2e2040876e6e92cd is at https://pr2913.build.csb.dev/s/new.

**Comment by TrevorSayre** [comment]
@lbogdan considering the context of the PR, perhaps this link instead: https://pr2913.build.csb.dev/s/react-ts

**Comment by CompuIves** [comment]
Wow this is interesting, we decided to only do `modulePaths` as an optimization (so we don't have to send new files for every code change, as the workers only care about saved code), but it seems like we did something wrong there. Really good find @yeion7! Now I'm curious what caused this bug in the first place, I wonder what we're actually sending to the workers after adding a dependency...

**Comment by CompuIves** [comment]
Hmm, after the fork modulesByPath is very different... 
image

**Comment by CompuIves** [comment]
This could also be the cause of the sudden empty editor state (@christianalfoni). Let's merge this in now for a quick fix, and take a closer look whether we can optimize this. We prefer not to send all files on a single keypress, so this is not really sustainable.

**Comment by CompuIves** [comment]
This is an incredible find @yeion7, this is super impressive! Thanks for digging in!

**Comment by yeion7** [comment]
Thanks!

@CompuIves there are some documentation about how this (workers communication) works at CodeSandbox?

**Comment by TrevorSayre** [comment]
Just to confirm, is this not yet live? What is the best way to track when a PR is released into the wild?

**Comment by lbogdan** [comment]
> Just to confirm, is this not yet live?

@TrevorSayre We just deployed it.

> What is the best way to track when a PR is released into the wild?

We're currently working on making production always reflect `master`.

**Pull request merged**
