### PR TITLE
Feat add support for Rax

### PR DESCRIPTION
**Pull request by fyangstudio**
Support Rax: https://rax.js.org/
## What kind of change does this PR introduce?
Rax starter template feature #3345 

## What is the current behavior?
No Rax 😞

## What is the new behavior?
Get started with Rax in CodeSandbox

## Checklist

- [x] Documentation
- [x] Testing 
- [x] [Icon](https://github.com/codesandbox/codesandbox-templates/pull/30)
- [x] [Template](https://github.com/raxjs/rax-codesandbox-template)
- [x] [Importer](https://github.com/codesandbox/codesandbox-importers/pull/60)
- [x] Ready to be merged
      
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3441/commits/64c4f5c31a5b19a3d858a38478e32245ea3dd28c is at https://pr3441.build.csb.dev/s/new.

**Comment by fyangstudio** [comment]
image
https://pr3441.build.csb.dev/s/github/raxjs/rax-codesandbox-template/tree/master/

It's worked, please merge these PR first. thx a lot.
[Icon](https://github.com/codesandbox/codesandbox-templates/pull/30)
[Importer](https://github.com/codesandbox/codesandbox-importers/pull/60)

**Comment by CompuIves** [comment]
Hey! Thanks for this contribution. We recently changed how we handle templates, right now we have a list of "templates" and a list of "environments". An environment is something that redefines how the sandbox is executed and which devtools are shown.

I think in this case, for Rax, we can reuse the `node` environment and say to the importer to make everything with the Rax template a `node` environment. Then we can add Rax to the list of official templates in our Template Modal by linking the sandbox.

So my approach would be this:
Merge the other PRs that you've opened, and then add the Rax example you mentioned here to our official template list. This way it will show up as an official template.

**Comment by fyangstudio** [comment]
> Hey! Thanks for this contribution. We recently changed how we handle templates, right now we have a list of "templates" and a list of "environments". An environment is something that redefines how the sandbox is executed and which devtools are shown.
> 
> I think in this case, for Rax, we can reuse the `node` environment and say to the importer to make everything with the Rax template a `node` environment. Then we can add Rax to the list of official templates in our Template Modal by linking the sandbox.
> 
> So my approach would be this:
> Merge the other PRs that you've opened, and then add the Rax example you mentioned here to our official template list. This way it will show up as an official template.


Thanks for your reply. Can I have a preview of the dev server if I reuse the `node` environment? I see that the current `node` environment preview is the log of `node`, we need the developers to preview their Web App.
image

**Comment by yacheng** [comment]
How to reuse the `node` environment and whether there are documents？

**Comment by fyangstudio** [comment]
> We recently changed how we handle templates, right now we have a list of "templates" and a list of "environments". 

When can this project be done?  Where can i see the new documentation?


@CompuIves

**Pull request closed without merging**
