### PR TITLE
Extract MostUsedSandbox from CreateNewSandbox

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Follow-up of #3099

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3101/commits/9162953ca3a9e484af7247a6fa9babf0c1e816de is at https://pr3101.build.csb.dev/s/new.

**Comment by CompuIves** [comment]
Nice! I want to wait with this one until our templates are merged (tomorrow) to prevent merge conflicts right before release.

**Comment by MichaelDeBoey** [comment]
No problem at all 🙂

**Comment by SaraVieira** [comment]
Looks good! Thank you so much!

**Pull request merged**
