### PR TITLE
New assets for Chrome/Firefox extension

### PR DESCRIPTION
**Pull request by garethx**
## What kind of change does this PR introduce?
Updates the visual assets used by the Chrome and Firefox extensions.

- [x] Ready to be merged

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/4084/commits/2240e804d7bcfc89792bd387e07dd0f3a9388918 is at https://pr4084.build.csb.dev/s/new.

**Comment by SaraVieira** [comment]
Hey!

Should you not remove the bottom part and public in the codesandbox organization?

**Comment by SaraVieira** [comment]
Sorry, k meant in the readme the bottom says to contact me if you have any Code changes and I will deploy it 

It's also under my name on the chrome and firefox store

**Comment by garethx** [comment]
@saravieira sure, that’s why I requested your review.

**Comment by SaraVieira** [comment]
Let's talk tomorrow :)

**Pull request merged**
