### PR TITLE
[chore] Update documentation to reflect CI limitations

### PR DESCRIPTION
**Pull request by joshuaellis**
## What kind of change does this PR introduce?

This is a documentation update around the usage of the CI. This has come about from a discussion in #5872

## What is the current behavior?

n/a

## What is the new behavior?

n/a

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

n/a

## Checklist

- [x] Documentation
- [x] Testing 
- [x] Ready to be merged
      
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/5968/commits/63bbd36e34343b1ef9fff2632cc4c39c95281b7d is at https://pr5968.build.csb.dev/s/new.

**Review by smhutch — APPROVED** [review]
Thanks!

**Comment by joshuaellis** [comment]
I've just resolved the conflicts, is there something else I need to do to get this merged?

**Review by aj-foster — APPROVED** [review]
Thank you for taking the time to make this update.

**Pull request merged**
