### PR TITLE
Fix content-hash in manifest for copied assets

### PR DESCRIPTION
**Pull request by CompuIves**
The `file-manifest.json` had items like

```json
{
  "public/sse-hooks.abc.js": "public/sse-hooks.abc.js"
}
```

While the server expects:

```json
{
  "public/sse-hooks.js": "public/sse-hooks.abc.js"
}
```

Turns out that CopyWebpackPlugin doesn't support this together with ManifestPlugin. Recently they got support, but it requires Webpack 5 to work. So until then, we have this nice Map function 😅 .

### CODE REVIEW

**Comment by SaraVieira** [comment]
Is this for the console issue?

**Comment by CompuIves** [comment]
> Is this for the console issue?

Yas

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/5273/commits/e12e4f25dd3f5059fa30e747f4a7c1ba5c7189f5 failed.

**Comment by SaraVieira** [comment]
closes #5264

**Pull request merged**
