### PR TITLE
[Feature]: default new project template

### PR DESCRIPTION
**Pull request by sag1v**
Create a template projects for #564

### CODE REVIEW

**Comment by lbogdan** [comment]
Can you please merge it with master, as there were a lot of changes since your commits? Also, you have a couple of eslint errors (disregard the `no-nested-ternary` warning).

**Comment by sag1v** [comment]
@lbogdan done

**Comment by sag1v** [comment]
@lbogdan Did you have a chance to take a look? I would love to promote this feature

**Comment by CompuIves** [comment]
Aii I completely missed this @sag1v! Thanks for the contribution, I'll write the server side part this weekend and hopefully merge this in.

**Comment by sag1v** [comment]
@CompuIves Great! 
If you need anything let me know.

**Comment by sag1v** [comment]
@CompuIves Is it going well?

**Comment by sag1v** [comment]
@CompuIves you think we can go forward with this?

**Comment by CompuIves** [comment]
Yes this is perfect! I'm sorry for being so quiet here.

The biggest thing I need to implement for this is a separate view in the dashboard and "Create New Sandbox" view so we can show the templates there.

**Comment by sag1v** [comment]
@CompuIves What about the server side? we would need a new property (or new entity) to reflect this object.

**Comment by sag1v** [comment]
Closed as this feature already implemented with a different PR

**Pull request closed without merging**
