### PR TITLE
Fix dependency name overflow

### PR DESCRIPTION
**Pull request by SaraVieira**
Problem:

CleanShot 2020-06-02 at 15 00 30@2x

Now:

CleanShot 2020-06-02 at 15 00 19@2x

### CODE REVIEW

**Comment by siddharthkp** [comment]
We have a prop for that: `maxWidth` :)

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/4291/commits/758bb6b4627f0e719f694039d4ce62bef017801a is at https://pr4291.build.csb.dev/s/new.

**Comment by SaraVieira** [comment]
mean

**Comment by SaraVieira** [comment]
@siddharthkp Fixed

**Pull request merged**
