### PR TITLE
Docs/react sandpack name

### PR DESCRIPTION
**Pull request by NinoMaj**
## What kind of change does this PR introduce?
Docs update

## What is the current behavior?
In current doc there is incorrect command for installing `react-smooshpack` package and code example of importing components.

## Checklist

- [x] Documentation
- [ ] Testing  N/A
- [x] Ready to be merged
      
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3602/commits/98c1873cee6964a381e8e072cf87f0536ab8b349 is at https://pr3602.build.csb.dev/s/new.

**Comment by SaraVieira** [comment]
Thank you!!!

@all-contributors please add @NinoMaj for focs

**Comment by SaraVieira** [comment]
Thank you!!!

@all-contributors please add @NinoMaj for docs

**Comment by SaraVieira** [comment]
There was abunch of conflicts so I merged adding you to the table here: https://github.com/codesandbox/codesandbox-client/pull/4414

:)

**Pull request merged**
