### PR TITLE
Removed extra test snapshot issue:3286

### PR DESCRIPTION
**Pull request by soorajshankar**
## What kind of change does this PR introduce?
Removing unnecessary snapshots from the code repo.

This is a code cleanup activity, Housekeeping.
## What is the current behavior?
Currently, the code contains 2 snapshots for the same test.

https://github.com/codesandbox/codesandbox-client/issues/3286
## What is the new behavior?
This removes the extra snapshot file 

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

1. Validated the Jest Test.

## Checklist

- [ ] Documentation
- [ X] Testing 
- [ ] Ready to be merged
      
- [ X] Added myself to contributors table

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3303/commits/1ee1e7683d3afe2206ce90eb2b507292e52e7069 is at https://pr3303.build.csb.dev/s/new.

**Comment by soorajshankar** [comment]
Just changed the commit author name, it was showing my other account :)

**Comment by soorajshankar** [comment]
@SaraVieira Please review this.

**Comment by SaraVieira** [comment]
Hey!

Thank you! I made two by accident when changing the theme 😂

**Comment by soorajshankar** [comment]
Thanks @SaraVieira, 
It looks like you guys are doing great work. I'll do some weekend contributions from now :)

**Pull request merged**
